### ISSUE TITLE
Activate downward api

### ISSUE THREAD

**Issue by posix4e** [kubernetes/kompose#1002]
Recently we wanted to get access to our namespace as an envvar. K8s can do this via the downward api
https://kubernetes-v1-4.github.io/docs/user-guide/downward-api/
It would be trivial to allow kompose users to activate this metadata as envvar.

**Comment by hangyan** [comment]
Do you suggest we add all of these metadata to container env automatically?

**Comment by hangyan** [comment]
I have checked the document, the downward api provides a method for users to use the metadata in env, but you need use it explicitly. I don't think it's a good idea to make it default. You can always edit the generated yaml to add these envs

**Comment by posix4e** [comment]
Why not have a switch to add it? We try not to edit the y’aml too often?

**Comment by hangyan** [comment]
That sounds reasonable.  A switch to add about 7 envs. @cdrage  what's your opinion?

**Comment by xianlubird** [comment]
@posix4e 
Could you provide a detail example show that how do you use download api in your environment?
If you provide a example, we can implement it more accurate.  thanks

**Comment by posix4e** [comment]
My usecase is knowing what namespace I’m in, in the application. Do you
want me to share some downstream api code? All I’d need is a slightly
different generated manifest

**Comment by hangyan** [comment]
@posix4e  For now our main focus will still be translating compose yaml to kubernetes yaml, since the downward-api is a kubernetes specific thing, it's a very great idea to add this function to kompose, based on kompose's purpose. But If there are any contributors willing to add support for this ,we are glad to merge it in.

**Comment by posix4e** [comment]
Right you need to generate a different kubernetes manifest if you are to
Expose the namespace as an envvar. This does make a huge variety of things
easier though. I might give it a try. Do we do anything like this in
previous patches?
