### ISSUE TITLE
Glide update error

### ISSUE THREAD

**Issue by xianlubird** [kubernetes/kompose#1003]
I want to upgrade k8s vendor to a newer version. I change `github.com/openshift/origin` version from `v1.4.0-rc1` to `v3.9.0`, then run `glide update --strip-vendor`. There're many errors message

```
[ERROR]	Error looking for k8s.io/api/apps/v1beta1: Unable to get repository: Cloning into '/root/.glide/cache/src/git-github.com-openshift-kubernetes-api'...
[ERROR]	Error scanning k8s.io/api/autoscaling/v1: cannot find package "." in:
	/root/.glide/cache/src/git-github.com-openshift-kubernetes-api/autoscaling/v1
[ERROR]	Error scanning k8s.io/api/batch/v1: cannot find package "." in:
	/root/.glide/cache/src/git-github.com-openshift-kubernetes-api/batch/v1
[ERROR]	Error scanning k8s.io/api/batch/v1beta1: cannot find package "." in:
	/root/.glide/cache/src/git-github.com-openshift-kubernetes-api/batch/v1beta1
[ERROR]	Error scanning k8s.io/api/batch/v2alpha1: cannot find package "." in:
	/root/.glide/cache/src/git-github.com-openshift-kubernetes-api/batch/v2alpha1
[ERROR]	Error scanning k8s.io/api/core/v1: cannot find package "." in:
	/root/.glide/cache/src/git-github.com-openshift-kubernetes-api/core/v1
```

So I can't upgrade k8s vendor to a newer version.   I find a issue https://github.com/redhat-developer/odo/issues/377, when I clean all glide cache and vendor folder, it always show above error message.   

@cdrage @hangyan Do you have some suggestion about this ? Need help.

**Comment by kadel** [comment]
Vendoring for newer versions of Kubernetes and OpenShift can can a bit tricky :-( 

We already hit this problem in Kedge and we had to write special script to handle OpenShift vendoring [vendor-openshift.sh](https://github.com/kedgeproject/kedge/blob/master/scripts/vendor-openshift.sh). See  comments in [glide.yaml](https://github.com/kedgeproject/kedge/blob/master/glide.yaml#L43,L49).

But there is another solution for this. Kompose still imports stuff from `k8s.io/kubernetes` and from `github.com/openshift/origin`. But it should be possible to replace it with `k8s.io/client-go` and `github.com/openshif/client-go`, it is not going to be easy but it will make vendoring straingforward and it will be much easier to update to new versions.
