### ISSUE TITLE
when to support this parameter build: args?

### ISSUE THREAD

**Issue by beefee** [kubernetes/kompose#1004]
build: args not implemented yet.
need to implemented quickly.
![qq20180512-134033](https://user-images.githubusercontent.com/38183891/39954052-a982f946-55ea-11e8-9e0e-f1b267a72d26.jpg)

**Comment by beefee** [comment]
this is very import , to auto build with modules and auto deploy on openshift.

**Comment by xianlubird** [comment]
We will work on it

**Comment by xianlubird** [comment]
@beefee Could you provide a example, the source compose file and the openshift yaml file you want get. So we can implement it better. Thanks.
