### ISSUE TITLE
Kubernetes multiple volumeMounts with subPath and 1 configmap volume - onle 1 volumeMount works

### ISSUE THREAD

**Issue by mariojacobo** [kubernetes/kompose#1005]
Hello, 

ISSUE
=====
When a deployment has multiple volumeMounts and only 1 volume (from configMap), only the last volumeMount is actually being mounted in the PODs; the rest do not get mounted; I have 3 volumeMounts with subPath specified to each required file that I want mounted. 

STEPS to REPRO
============
1. create configmap: $ kubectl create configmap nginx-config --from-file=nginx.conf --from-file=default.conf --from-file=index.html 
2. create the deployment: $ kubectl create -f deployment.yaml 

deployment.yaml
=============
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html   
        ports:
        - containerPort: 80
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

Investigation
==========
1. configmap nginx-config has all 3 required sections: 
$ kubectl describe configmap nginx-config | egrep  "conf|html"
Name:         nginx-config
default.conf:
index.html:
nginx.conf:
 
2.   If I connect to the POD/s, only "index.html" has been mounted from the configMap, the rest of the files are default.  if I switch the order of the volumeMounts, then the same behavior is seen, the last entry gets mounted. 

Workaround
==========
As a workaround, I needed to create 3 separate configmaps and add 3 volumes (configmap) in the deployment spec. that seems to work properly, however it would be nice to have 1 single configmap volume to keep things tidy.

**Comment by mariojacobo** [comment]
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes version: 1.9.6

**Comment by rasoulivand** [comment]
Hey @mariojacobo

**Comment by rasoulivand** [comment]
Hey @mariojacobo ;
How did you solve this issue?

**Comment by hangyan** [comment]
@rasoulivand Have you ran into the similar issue?

**Comment by rasoulivand** [comment]
Yes @hangyan 
I've same issue

**Comment by hangyan** [comment]
@rasoulivand Can you post a simple version of you compose file?

**Comment by mariojacobo** [comment]
@rasoulivand unfortunately not, I've just been using the workaround I mentioned initially. it's not too elegant, but it works.
