### ISSUE TITLE
multiple containers in a pod sharing volume

### ISSUE THREAD

**Issue by choig** [kubernetes/kompose#1012]
When I use `kompose up` or `kompose convert`, I get each service as its own pod with single container.  One functionality I am trying to use in kubernetes is the docker-in-docker (dind) that sits along side my execution agent in the same pod.  I have this working with kubectl create if using the same `emptyDir` to share both workspace and docker.sock for both containers.  I also have this working with `docker-compose` but this does not convert over to kubernetes without multiple containers in a pod support.

I have gone thru the docs and do not see mention of multiple container pod.  Plus in other forums, I have seen the same question posted without any solution.  Thus I am posting here after seeing the RFE for service type.  Along the same lines of `kompose.service.type` that can switch to `loadbalancer`, I wondered if it would be possible to:

- use a specific label that can group services/containers together into a pod 
- and also iterate over the volume mounts that share the same location to be combined together when `--volumes emptyDir` is present

**Comment by korentsov** [comment]
I've also faced with this issue, I need to use gcePersistentDisk as ReadWriteMany in multiple containers, which is possible only with multi-container pod. 

I agree with choig, would be good to have:

+ use a specific label that can group services/containers together into a pod
+ and also iterate over the volume mounts that share the same location to be combined together when --volumes emptyDir is present

**Comment by wstewartii** [comment]
I also need this feature to be able tl consider using kompose for production deployments.

**Comment by maxdanilov** [comment]
Is there any update on adding multicontainer support?
