### ISSUE TITLE
Support imagePullPolicy via label.

### ISSUE THREAD

**Issue by mikesimos** [kubernetes/kompose#1036]
Would `kompose.image-pull-policy` be a good candidate name for this label?

**Comment by jvitor83** [comment]
The only change i make was the label name, that i use: `kompose.service.image-pull-policy`

**Comment by mikesimos** [comment]
Hi @jvitor83 ! Sorry just saw that. I was waiting for some confirmation/ guidelines for this issue from the project maintainers following contributing guidelines [here](https://github.com/kubernetes/kompose/blob/master/CONTRIBUTING.md#contributing-a-patch). I already have some work for own use on this [here](https://github.com/mikesimos/kompose/tree/add-kompose.image-pull-policy) awaiting to be PRed. Would you mind rebasing your contribution on top of this? Thanks!
The naming of the label is indeed a concern, but since imagePullPolicy isn't a docker-compose service directive, I wouldn't use the kompose.service prefix. I was rather inclined towards something like `kubernetes.`  prefix for kubernetes specific customizations. This feature focuses on very specific use cases were imagePullPolicy Never needs to be specified (ie. industrial air-gapped environments, etc). Not sure if [this (check imagePullPolicy)](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core) is helpful for you.

**Comment by mikesimos** [comment]
@cdrage @hangyan, I m creating a PR for comments/guidelines? Thanks!

**Comment by jvitor83** [comment]
@mikesimos closing my PR since your appear to do the same (only with different label).
