### ISSUE TITLE
Add official docker image build

### ISSUE THREAD

**Issue by spawnia** [kubernetes/kompose#1045]
I would like use kompose packaged as a docker image.

https://hub.docker.com/r/femtopixel/kompose/

While this works, it would be nice to either have an official image or at least have this linked in the readme.

**Comment by hangyan** [comment]
@spawnia Great idea, we will try to add one ASAP

**Comment by spawnia** [comment]
/remove-lifecycle stale

I still think this is relevant, but do not feel qualified to provide such an image. I do not know the build process well enough.

**Comment by cdrage** [comment]
@spawnia if you'd like to take this up that'd be great. Simply throw a Dockerfile in the root directory of https://github.com/kubernetes/kompose that's compatible and we'll create the docker username / repo.

**Comment by spawnia** [comment]
@cdrage how would i go about getting the binary into the image? Should i rebuild it with docker, or download the prebuilt one?

**Comment by cdrage** [comment]
@spawnia You can parse https://github.com/kubernetes/kompose/blob/master/build/VERSION within the Dockerfile and have it essentially download / update each time we do a release. 

So perhaps a "debian / alpine" Dockerfile with the binary in it that'd youd get with curl?

**Comment by spawnia** [comment]
Still relevant, as PR #1101 is still open

**Comment by hangyan** [comment]
@spawnia Thanks for you contribution
