### ISSUE TITLE
Support for PVC Access Mode ReadWriteMany

### ISSUE THREAD

**Issue by jardilio** [kubernetes/kompose#1046]
Currently, looks like convert only covers cases for ReadOnly and ReadWriteOnce, but not ReadWriteMany. Use case is when you have more than one service that share a common volume. Ideally it would pick up in docker-compose if volume is linked to multiple services and do the conversion. Alternatively, could use labels to manually map if needed.

**Comment by cjancsar** [comment]
@hangyan how could I go about implementing this in a PR?

**Comment by hangyan** [comment]
@cjancsar You can check out the source code to see how to do it, remember to add some tests.
I will also keep up with this
