### ISSUE TITLE
imagePullPolicy: is there way of specifying this

### ISSUE THREAD

**Issue by mbana** [kubernetes/kompose#1052]
https://kubernetes.io/docs/concepts/containers/images/#updating-images

Is the above supported, if not, is there a way of attaching arbitrary metadata to a container?

**Comment by hangyan** [comment]
@mbana Since compose doest not have this settings, so no for now. We use the default settings for this in kubernetes

**Comment by ArtemAlagizov** [comment]
would be noice to have

**Comment by kominoshja** [comment]
Since compose now supports [pull_policy](https://docs.docker.com/compose/compose-file/05-services/#pull_policy), i believe this issue should be reopened
