### ISSUE TITLE
Init Containers

### ISSUE THREAD

**Issue by edvorg** [kubernetes/kompose#1053]
Hi is there a way to specify init containers for pods in docker-compose.yml?
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by hangyan** [comment]
@edvorg Since docker compose does not have this feature, our main focus for now is still on docker-compose spec.

**Comment by edvorg** [comment]
Understood! Shall we close the ticket?

**Comment by hangyan** [comment]
@edvorg Close it now

**Comment by SvenBrunk** [comment]
Since docker-compose has this feature since docker-compose.yml file format version 2 (beginning of 2017) (depends_on + restart: no), can we have it now? ;)

**Comment by nathanweeks** [comment]
`depends_on` isn't semantically equivalent to initContainers (see https://github.com/docker/compose/issues/6855)

**Comment by dennohpeter** [comment]
Can we now have labels to set in containers on the docker-compose file?
