### ISSUE TITLE
kompose webside is outdated

### ISSUE THREAD

**Issue by florianrusch** [kubernetes/kompose#1057]
On the startpage of the kompose website (http://kompose.io/) is still the install instruction for the version `1.13.0`. And maybe it's time to upgrade to https. 😉

![image](https://user-images.githubusercontent.com/1724759/43370571-80a61f60-9381-11e8-813a-9fe0abdf0d74.png)

**Comment by hangyan** [comment]
@cdrage Isn't this auto-updated?

**Comment by cdrage** [comment]
@hangyan Looks like someone put a protective status on the `gh-pages` branch (or it could of been done automatically recently).

Here was the latest error:
```sh
setup.md already contains Jekyll format
Adding Jekyll file format to user-guide.md
[gh-pages 8cf9b17] Update docs
 3 files changed, 9 insertions(+), 9 deletions(-)
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.        
To github.com:kubernetes/kompose.git
 ! [remote rejected] gh-pages -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'git@github.com:kubernetes/kompose.git'
```

I'm going to remove the protected branch status and then force a re-run of docs update.

**Comment by cdrage** [comment]
There we go! It's been updated, see: http://kompose.io/installation/

Closin'
