### ISSUE TITLE
Unable to load yaml/json file

### ISSUE THREAD

**Issue by jjankar** [kubernetes/kompose#1072]
Output of Terminal:
$ kompose convert -f docker-compose.yml
FATA Unable to load yaml/json file for version parsing: yaml: line 26: found unexpected end of stream 
janis@jk:~$ cat docker-compose.yml
version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair:v2.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060:6060"
      - "6061:6061
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]

But docker compose command is working and all is setup. What could go wrong with this file?

**Comment by vdemeester** [comment]
@jjankar pretty sure there is a `"` missing here `- "6061:6061`. Not sure why `docker-compose` would work though…

**Comment by jjankar** [comment]
@vdemeester  sorry and thank you :)
