### ISSUE TITLE
hostPath volumes?

### ISSUE THREAD

**Issue by kadel** [kubernetes/kompose#109]
We use `hostPath` in volumes?
This doesn't really makes sense to me. When you are deploying to Kubernets cluster `hostPath` will **never** contain files that you have on your local machine from which you are running `kompose`. Unless you somehow copy them manually.
Another thing with `hostPath` is that even if you somehow upload you files to it, whenever pod is rescheduled to another node `hostPath` can contain completely different files.

Because of above I think that `hostPath` can confuse users instead of helping.

Ideally user should  be able to choose which type of volume he/she wants (this will usually depend on his environment setup (gcePersistentDisk, awsElasticBlockStore, nfs ....)).

For now I propose using emptyDir, and displaying warning or some message explaining why this is. And that right now you can't copy content of local directory to cluster volume.

**Comment by janetkuo** [comment]
> For now I propose using emptyDir, and displaying warning or some message explaining why this is. And that right now you can't copy content of local directory to cluster volume.

You're right. Let's remove `hostPath`.

**Comment by xiaoping378** [comment]
i need the hostPaht, even if i copy them manually.
can i push a merged about adding --hostPath option?

**Comment by surajnarwade** [comment]
@xiaoping378 , can you please explain your use case ?

**Comment by xiaoping378** [comment]
@surajnarwade 
i'm try to run hyperledger fabric on the k8s, but the [fabric samples](https://github.com/hyperledger/fabric-samples/blob/release/balance-transfer/artifacts/docker-compose.yaml) has too many volumes,  if kompose don't write hostpath, i will so plain to edit the k8s yaml.

**Comment by cdrage** [comment]
Hey @kadel @surajnarwade @xiaoping378 

I'm re-opening this issue for discussion.

As volumes are a very difficult area for converting, I suggest we add a different parameter, preferably, `--volumes`

For example, we'd have:

```
--volumes [none|host-path|empty,etc.]
```

What do you think?

**Comment by surajssd** [comment]
@cdrage how does it help?
Or what is the requirement that will be solved with this feature? Adding this is only supporting anti-pattern in k8s world?

**Comment by cdrage** [comment]
@surajssd Not exactly an anti-pattern, but more in regards to filling in the "blanks" between Kompose and its heavy use of volumes and the "PersistentVolumeClaim" method for Kubernetes.

Since we already have one parameter (emptyvols), it makes sense to combine them all into one parameter (volumes) so we don't have multiple similar params.

**Comment by surajssd** [comment]
In most cases `hostPath` and `emptyDir` will behave the same because pod would not be scheduled on same node. 

*Behave the same* means that it will most probably have empty storage.

Also `hostPath` is more error prone because user will have to make sure that path on the k8s node exists and container runtime has permissions to write there.

**Comment by cdrage** [comment]
@kadel thoughts?

**Comment by kadel** [comment]
Adding ` --volumes [none|host-path|empty,etc.]` and removing `--emptyvols` is good idea.
I would use Kubernetes naming so it should be `emptyDir` and `hostPath`.

But this will have one big limitation that might confuse pepole a bit.
If we add option for hostPath it means that all the volumes in given Dockerfile will be converted to hostPaths volumes. We need properly document and explain it in `--help`
I'm definetly agains adding some magic label or other logic that will allow specify this on per volume basic.
But global flag is OK.

**Comment by cdrage** [comment]
@kadel 

Okay, I will go through with it. First off is refactoring the code to `--volumes` and deprecating --emptyvols I shall also update and notify https://github.com/kubernetes/kompose/pull/734

**Comment by cdrage** [comment]
This has been fixed in https://github.com/kubernetes/kompose/pull/957
