### ISSUE TITLE
k.Transform failed archive/tar: write too long

### ISSUE THREAD

**Issue by wuestkamp** [kubernetes/kompose#1093]
When running `kompose up -vvv` I'm getting:

```
INFO Building image 'eu.gcr.io/project/php:latest' from directory 'project_dir' 
DEBU Created temporary file /var/folders/yt/9pghpn1s5sq0bvnw0hmwljfr0000gn/T/kompose-image-build-069005223 for Docker image tarballing 
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service php: Unable to create a tarball: archive/tar: write too long 
```

I can push manually though without issues using `docker push eu.gcr.io/project/php:latest`

Why is this a problem here?
What is tarball used for?
Can I disable tarballing?

I saw #656 but is closed so wanted to open a new one. I'm having a Symfony project and removed already the vendor folder, no change.

Thanks,
Kim

**Comment by wuestkamp** [comment]
So this only happens if I do this in my `docker-compose.yml`:

```
    php:
        build:
          context: .
          dockerfile: ./php-fpm/Dockerfile
```

if I leave it like this no error:

```
    php:
        build: ./php-fpm
```

But I need to use the context setting because I want to copy files in my `Dockerfile`:

```
ADD php-fpm/symfony.ini /etc/php7/conf.d/
ADD php-fpm/symfony.ini /etc/php7/cli/conf.d/
ADD php-fpm/xdebug.ini  /etc/php7/conf.d/

ADD php-fpm/symfony.pool.conf /etc/php7/php-fpm.d/

CMD ["php-fpm7", "-F"]

WORKDIR /var/www/symfony
COPY symfony .
```

Anyone got an idea?

**Comment by wuestkamp** [comment]
Ok, this was because there were still deeply hidden symlinks in the context folder. So symlinks was the issue :)

**Comment by hangyan** [comment]
related to #969

**Comment by rashad** [comment]
Sorry for dumb question but I don't get what the issue is with symlinks and what should one do in case he has some (I do) ? 

Thanks for your help :)
