### ISSUE TITLE
Support kompose up build with no push

### ISSUE THREAD

**Issue by rqc** [kubernetes/kompose#1105]
Hi,

I am trying out `kompose up` to run some containers in a `docker-compose.yml` file. One of them needs to be built locally. From the docs, it seems that the build support also pushes the image to a remote registry. How can I disable the `docker push` if I am just interested in building the image and running the containers locally?

Thanks!

**Comment by hangyan** [comment]
@rqc what's your image name format ? @cdrage Seems we can check on the image name format to detected push or not

**Comment by rqc** [comment]
@hangyan thanks for responding.

I have the following in my `docker-compose.yml` file:

```
...yaml
    build: .
    image: myapp:dev
...
```

I am just interested in having `myapp:dev` be picked up by `kompose` as expected during a `kubectl create` or `kubectl run`, etc. My local workflow is to build the image in the `minikube` `docker` environment, `kubectl` seems to look for the image in the current environment before looking in `Docker Hub` or other registries.

Thanks!

**Comment by usgmgratiphied** [comment]
We are also running into this.  docker-compose build doesn't do a push; that is a separate command (docker-compose push).

**Comment by croensch** [comment]
While i don't mind pushing my experiments i would say this is a security issue. If one wants to use minikube + kompose instead of docker-compose and just does the convert & up it should keep images local as docker-compose does. Otherwise company externals might get pushed by accident. Feel free to play with my example https://github.com/croensch/klaus/commit/f6c1901f2b61035fa6ccd1fe7e3d31bface0d077

**Comment by orkenstein** [comment]
Please, add functionality to perform build without push. It's useful for local kubernetes setup!

**Comment by hangyan** [comment]
@orkenstein I have create a PR to fix this, but it will need some time to merge in. You can check the the source code in my repo and build it from source if you are in a hurry

**Comment by YannickFricke** [comment]
@hangyan Any updates on this?

**Comment by hangyan** [comment]
PR has been merged. close this issue

**Comment by jar145** [comment]
I couldn't find any documentation on this, so if anyone is curious about the flag to be used here it is.

`kompose up --push-image=false`

**Comment by hangyan** [comment]
@jar145 my mistake, i will update the doc.

**Comment by jouellnyc** [comment]
thumbs up. Worked for me.

**Comment by gargankur2008** [comment]
Thanks @jar145
