### ISSUE TITLE
Fix dep

### ISSUE THREAD

**Issue by hangyan** [kubernetes/kompose#1119]
I have checked the dep management situation, it's hard to update the packages and support new compose versions. May be we can drop openshift support for a while and try to fix the dep issue first?
If things worked out, we can add openshift support back? 

@cdrage

**Comment by hangyan** [comment]
This may not be a good idea, but i got no luck to update the vendor package versions...

**Comment by cdrage** [comment]
Ahhh I'd vote against it, do you have problems updating dependencies when you're using Glide? 

Unfortunately OpenShift is a requirement for Kompose (well, I work for Red Hat so kind of implied haha). We have some critical software using Kompose for OpenShift conversion.

Usually I use this guide when doing dependency updates, do you have an error you can post?

https://github.com/kubernetes/kompose/blob/master/docs/development.md#glide-glide-vc-and-dependency-management

**Comment by hangyan** [comment]
@cdrage Yeah, i know, it's a bad idea. I have tried a fews times to update docker/cli version to support compose version higher than 3.4(3.5,3.6,3.7), but the code does't match, failed to build, it's a dependency hole. It's hard to find a version that match all the scenarios

**Comment by cdrage** [comment]
@hangyan It does as well especially since https://github.com/docker/libcompose is no longer maintained...

It's a pain in the butt haha
