### ISSUE TITLE
kompose up not working on windows?

### ISSUE THREAD

**Issue by devnewton** [kubernetes/kompose#1122]
kompose up failed on windows with the following message:

`FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service xxx: Unable to build image. For more output, use -v or --verbose when converting.: dial unix /var/run/docker.sock: connect: not supported by windows`

Is there a workaround?

**Comment by hangyan** [comment]
@devnewton yes, we doest't have a windows environment to test this project.

**Comment by cdrage** [comment]
@devnewton Can you post your docker compose yaml file? Also, are you running docker with `Docker on Windows`?

**Comment by devnewton** [comment]
I'm using Docker Desktop Community 2.0.0.3.

My docker compose file looks like:

```yaml
version: "3"
services:
  myproject-nginx:
    build:
      context: ./myproject-nginx
    image: myproject-nginx
    depends_on:
      - myproject-gui
    ports:
      - "80:80"
  myproject-ws:
    build:
      context:  ./myproject-ws
    image: myproject-ws
    ports:
      - "60000:60000"
  myproject-gui:
    build: 
      context:  ./myproject-gui
    image: myproject-gui
    depends_on:
      - myproject-ws
    ports:
      - "50000:50000"
`

Where myproject-nginx is a simple reverse proxy, myproject-gui and myproject-ws are classic Spring boot java projects.

**Comment by cjancsar** [comment]
@devnewton did you resolve this?

**Comment by cjancsar** [comment]
@cdrage did you have any suggestions for @devnewton ? I am running into the same issue. Currently I need to just use `kompose convert` and then deploy with `kubectl`

**Comment by devnewton** [comment]
No I leave kompose and the idea to simplify our development toolchain.

**Comment by GabrielBB** [comment]
Dissapointed

**Comment by hangyan** [comment]
Update doc about windows in the README. close this for now.
