### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by montanaflynn** [kubernetes/kompose#1124]
```
go get -u github.com/kubernetes/kompose

# cd /Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose; git submodule update --init --recursive
Cloning into '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm'...
fatal: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
fatal: clone of 'https://src.fedoraproject.org/cgit/rpms/kompose.git' into submodule path '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm' failed
Failed to clone 'build/rpm'. Retry scheduled
Cloning into '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm'...
fatal: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
fatal: clone of 'https://src.fedoraproject.org/cgit/rpms/kompose.git' into submodule path '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm' failed
Failed to clone 'build/rpm' a second time, aborting
package github.com/kubernetes/kompose: exit status 1
```

**Comment by anarcat** [comment]
I can reproduce this. When I rerun go-get, it somehow ignores the submodules (!) and carries forward without problems.

**Comment by fentas** [comment]
same here. Tried to add it via `dep`
```
  ✗ failed to fetch source for github.com/kubernetes/kompose: failed to fetch source for https://github.com/kubernetes/kompose: unable to get repository: Cloning into '/home/user/go/pkg/dep/sources/https---github.com-kubernetes-kompose'...
POST git-upload-pack (gzip 1765 to 943 bytes)
remote: Enumerating objects: 236, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 16359 (delta 21), reused 233 (delta 21), pack-reused 16123
Receiving objects: 100% (16359/16359), 20.84 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (8588/8588), done.
Submodule 'build/rpm' (https://src.fedoraproject.org/cgit/rpms/kompose.git) registered for path 'build/rpm'
Cloning into '/home/user/go/pkg/dep/sources/https---github.com-kubernetes-kompose/build/rpm'...
fatal: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
fatal: clone of 'https://src.fedoraproject.org/cgit/rpms/kompose.git' into submodule path '/home/user/go/pkg/dep/sources/https---github.com-kubernetes-kompose/build/rpm' failed
Failed to clone 'build/rpm'. Retry scheduled
Cloning into '/home/user/go/pkg/dep/sources/https---github.com-kubernetes-kompose/build/rpm'...
t status 1

adding dependencies failed
```

**Comment by cdrage** [comment]
Hey sorry for the late reply,

I'm cruious why it's cloning from `'https://src.fedoraproject.org/cgit/rpms/kompose.git/` ? Did you originally git clone the RPM path (in the first place) and then try doing go get?

**Comment by fentas** [comment]
Sorry, I am not quite sure if I understand you correctly but I never tried to clone `fedoraproject` directly.
What I tried was (in order)
```sh
dep ensure --add github.com/kubernetes/kompose/pkg/loader/compose
# ➜ failed
go get github.com/kubernetes/kompose
# ➜ failed
go get github.com/kubernetes/kompose
# ➜ succeeded
dep ensure --add github.com/kubernetes/kompose/pkg/loader/compose
# ➜ succeeded

# then replaced the version 0.4.0 with v1.18.0
dep ensure
# ➜ failded
```

**Comment by cdrage** [comment]
We use Glide for dependencies and I don't believe `go get` will work correctly with the `fedoraproject`.

**Comment by fentas** [comment]
Then `go get` and `dep` are unsupported for now?
I would argue both are the most used out there.

**Comment by cdrage** [comment]
@fentas `go get` is supported. 

I didn't run into any issues doing: `go get -u github.com/kubernetes/kompose`

`go dep` is undeed unsupported as we still highly use `glide` in order to manage both our OpenShift and Kubernetes repository conflicts.

If someone wants to convert our current glide dependency management to `go dep`, they can always open up a pull-request. At the moment I don't have much time to maintain the project :disappointed:

**Comment by fentas** [comment]
Indeed. Glide itself says to migrate to `dep`.

> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

I would like but I have no time either at the moment. :/

**Comment by seanwessmith** [comment]
I narrowed it down to cloning the incorrect fedoraproject url
old: git clone https://src.fedoraproject.org/cgit/rpms/kompose.git
working: git clone https://src.fedoraproject.org/rpms/kompose.git
