### ISSUE TITLE
Error when i'm trying to convert my docker-compose

### ISSUE THREAD

**Issue by mathieurbl** [kubernetes/kompose#1130]
Hello,
I'm trying to convert a docker-compose for kubernetes with kompose but it's not working. (The docker-compose works fine).

So I've started minikube with `minikube start` and when I go to the dashboard after doing `kompose up` I get this :
![image](https://user-images.githubusercontent.com/47533125/57676784-a4aa4300-7625-11e9-9bc2-1d49e2d8646c.png)

I have some WARNS in my terminal : 
![image](https://user-images.githubusercontent.com/47533125/57676942-f357dd00-7625-11e9-83d7-62c24beb75f4.png)

Here is what my docker compose contains:

version: '2'
services:
  
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    container_name: logstash_70
    command: -f /usr/share/logstash/pipeline/first-pipeline.conf --config.reload.automatic
    volumes:
      - '\~/Bureau/Docker/ELK7.0/logstash/pipeline/:/usr/share/logstash/pipeline/'
      - '\~/Bureau/Docker/ELK7.0/logstash/config/:/usr/share/logstash/config/'
    networks:
      - esnet

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.0
    container_name: filebeat_70
    command: -e -c /usr/share/filebeat/config/filebeat.yml -d "publish"
    volumes:
      - '~/Bureau/Docker/ELK7.0/filebeat/:/usr/share/filebeat/config/'
      - '/var/log/suricata/:/var/log/suricata/'
    networks: 
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - esnet

  suricata:
    image: d9d9/suricata
    container_name: suricata_413
    command: -i wlp2s0
    volumes:
      - '/var/log/suricata/:/var/log/suricata/'
      - '\~/Bureau/Docker/ELK7.0/suricata/config/suricata.yaml:/etc/suricata/suricata.yaml'
      - '\~/Bureau/Docker/ELK7.0/suricata/rules/my_own.rules:/var/lib/suricata/rules/my_own.rules'
      - '~/Bureau/Docker/ELK7.0/suricata/rules/misp.rules:/var/lib/suricata/rules/misp.rules'
    network_mode: "host"    

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:

PS : I've already tried to remove networks  and ulimits fields and to run `kompose up docker-compose.yml --volumes hostPath` instead of `kompose up` but it does not working anymore and 2 WARNS are persisting : 
WARN Unsupported root level volumes key - ignoring 
WARN Unsupported network_mode key - ignoring

**Comment by pbalaguer19** [comment]
Same here!

**Comment by justinfx** [comment]
Any info on this? I hit the same issue with a root level `volumes` key
