### ISSUE TITLE
Upgrade Deployment and DaemonSet

### ISSUE THREAD

**Issue by fentas** [kubernetes/kompose#1133]
Deployment **extensions/v1beta1** is depricated. ➜ **apps/v1**
https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_deployment

DaemonSet **extensions/v1beta1** is depricated. ➜ **apps/v1**
https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_daemonset

**Comment by hangyan** [comment]
I thinks use the old version can support more kubernetes cluster versions
