### ISSUE TITLE
add support for Alias

### ISSUE THREAD

**Issue by shrek20** [kubernetes/kompose#1134]
Hi . i tried converting a docker-compose file  with alias section.   -- Didnt get correctly mapped yaml file which had alias

[docker-compose.yml.txt](https://github.com/kubernetes/kompose/files/3226710/docker-compose.yml.txt)

**Comment by hangyan** [comment]
kompose doest not have much support for network and network alias for now. . 
Do you have any thoughts what the network alias should map to ?

**Comment by udartsev** [comment]
/reopen
```
kompose version
1.21.0 (992df58d8)

```

The reason that we need it: because OpenShift DeploymentConfig doesn`t support for example dots (".") in **hostname** :
