### ISSUE TITLE
Unknown flag: from

### ISSUE THREAD

**Issue by gubing2020** [kubernetes/kompose#1140]
kompose version:
1.18.0 (06a2e56)
Docker-compose version:
 '3.3'
My Dockerfile contains the below:
FROM nginx
COPY --from=0 /app/dist /usr/share/nginx/html

When I tryed kompose up to run some containers in a docker-compose.yml file I saw the error of "For more output, use -v or --verbose when converting.: Unknown flag: from ". For details please refer to the following log.
 
INFO Successfully pushed image 'library/dashboard_django:latest' to registry '10.66.12.163' 
WARN Volume mount on the host "/root/gb/MF-CRT-dashboard-dev/backend" isn't supported - ignoring path on the host 
INFO Build key detected. Attempting to build and push image '10.66.12.163/library/dashboard_nginx' 
DEBU Compose file dir: /root/gb/MF_CRT_dashboard_dev 
INFO Building image '10.66.12.163/library/dashboard_nginx' from directory 'MF_CRT_dashboard_dev' 
DEBU Created temporary file /tmp/kompose-image-build-093838583 for Docker image tarballing 
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service nginx: Unable to build image. For more output, use -v or --verbose when converting.: Unknown flag: from

**Comment by hangyan** [comment]
can you provide more details? for example your dockerfile and compose file(strip the sensitive data)
