### ISSUE TITLE
redis-slave not found

### ISSUE THREAD

**Issue by edewit** [kubernetes/kompose#1143]
using the example:
`wget https://raw.githubusercontent.com/kubernetes/kompose/master/examples/docker-compose.yaml`

and then:
`kompose up`

I get the following error in the frontend:
```
<br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168
Stack trace:
#0 /usr/local/lib/php/Predis/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /usr/local/lib/php/Predis/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection-&gt;createResource()
#3 /usr/local/lib/php/Predis/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection-&gt;connect()
#4 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection-&gt;connect()
#5 /usr/local/lib/php/Predis/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection-&gt;getResour in <b>/usr/local/lib/php/Predis/Connection/AbstractConnection.php</b> on line <b>168</b><br />
```

This might be introduced by https://github.com/kubernetes/kompose/pull/1123 guess it needs some changes in the frontend images as well `gcr.io/google-samples/gb-frontend:v4` or maybe an other version?

**Comment by medmedchiheb** [comment]
needs access to `google-samples` on GCP.

**Comment by edewit** [comment]
I have all the service running so the images are downloaded, but the frontend has an error connecting this error is from the console log of the browser and because of it the example doesn't work. Even when I use docker-compose it doesn't work, I get the same error

**Comment by medmedchiheb** [comment]
offcourse, because as you mentioned service 'redis-slave' replaced to 'redis-node'  and in source code host of  `redis-node`  in `guestbook.php` does not changed yet.

**Comment by edewit** [comment]
ahh okay when you said: "needs access to google-samples", you meant to fix it in the frontend. I though that you meant, that my error was due to me being unable to connect to the google-samples

**Comment by medmedchiheb** [comment]
ahh NO, needs access to project 'google-samples' to push new image.

/help

**Comment by hangyan** [comment]
ref to #1145

**Comment by hangyan** [comment]
@edewit @medmedchiheb The revert pr has been merged, you can try it out on the master branch
