### ISSUE TITLE
kompose.image-pull-secret label not recognized by MicroK8s 1.14

### ISSUE THREAD

**Issue by feered** [kubernetes/kompose#1146]
I'm new to MicroK8s and not unsure if this is also an issue with earlier versions but the `kompose.image-pull-secret` label is not recognized. This requires you to `kompose convert` and manually add the `imagePullSecrets` configuration in each service. I understand this is an isolated issue with MicroK8s / containerd but it is worth mentioning here.

[This is a similar request](https://github.com/kubernetes/kompose/issues/897). Is there a way to convert this label into an actual configuration that MicroK8s would understand?

**Comment by hangyan** [comment]
Are you use the latest version? I have test it and it works.

**Comment by feered** [comment]
I will double check. I forgot to mention that the repository I am accessing is an official Docker repository that is private. This works for you? We had two instances of MicroK8s running and neither were able to pull the images. However, the label works on my ECK instance.

**Comment by feered** [comment]
I have updated my version of kompose (apparently we had 1.17 installed) and it worked. Thank you for your time!
