### ISSUE TITLE
fabric8:deploy - unable to access cluster

### ISSUE THREAD

**Issue by narsinallamilli** [kubernetes/kompose#1162]
I am trying to follow http://kompose.io/maven-example/ every thing went well however issue is with deploy step throwing error,

narsi-macbook-pro:kompose-maven-example nnallam$ mvn fabric8:deploy
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< io.fabric8:springboot-docker-compose >----------------
[INFO] Building Fabric8 Maven :: Sample :: Springboot Docker compose 3.5
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> fabric8-maven-plugin:3.5.28:deploy (default-cli) > install @ springboot-docker-compose >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ springboot-docker-compose ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/nnallam/IdeaProjects/kompose-maven-example/src/main/resources
[INFO] skip non existing resourceDirectory /Users/nnallam/IdeaProjects/kompose-maven-example/src/main/resources
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.28:resource (fmp) @ springboot-docker-compose ---
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/igcluster doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-jboss-openjdk8-jdk:1.2 as base / builder
[INFO] F8: converting docker compose file /Users/nnallam/IdeaProjects/kompose-maven-example/docker-compose.yml to kubernetes resource descriptors
[INFO] F8: conversion completed successfully : 2 resource descriptors generated
[INFO] F8: using resource templates generated from compose file
[INFO] F8: spring-boot-health-check: Adding readiness probe on port 8080, path='/health', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: spring-boot-health-check: Adding liveness probe on port 8080, path='/health', scheme='HTTP', with initial delay 180 seconds
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: f8-icon: Adding icon for deployment
[INFO] F8: f8-icon: Adding icon for service
[INFO] F8: validating /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/openshift/springboot-service-route.yml resource
[INFO] F8: validating /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/openshift/springboot-service-deploymentconfig.yml resource
[INFO] F8: validating /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/openshift/springboot-service-svc.yml resource
[INFO] F8: validating /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/kubernetes/springboot-service-deployment.yml resource
[INFO] F8: validating /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/kubernetes/springboot-service-svc.yml resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ springboot-docker-compose ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ springboot-docker-compose ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/nnallam/IdeaProjects/kompose-maven-example/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ springboot-docker-compose ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ springboot-docker-compose ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ springboot-docker-compose ---
[INFO] Building jar: /Users/nnallam/IdeaProjects/kompose-maven-example/target/springboot-docker-compose-3.5.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:repackage (default) @ springboot-docker-compose ---
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.28:helm (fmp) @ springboot-docker-compose ---
[INFO] F8: Creating Helm Chart "springboot-docker-compose" for Kubernetes
[INFO] Building tar: /Users/nnallam/IdeaProjects/kompose-maven-example/target/springboot-docker-compose-3.5-helm.tar.gz
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.28:build (fmp) @ springboot-docker-compose ---
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/ig doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[INFO] F8: Building Docker image in Kubernetes mode
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/ig doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/ig doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-jboss-openjdk8-jdk:1.2 as base / builder
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/ig doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/ig doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[INFO] Copying files to /Users/nnallam/IdeaProjects/kompose-maven-example/target/docker/fabric8/springboot-docker-compose/3.5/build/maven
[INFO] Building tar: /Users/nnallam/IdeaProjects/kompose-maven-example/target/docker/fabric8/springboot-docker-compose/3.5/tmp/docker-build.tar
[INFO] F8: [fabric8/springboot-docker-compose:3.5] "spring-boot": Created docker-build.tar in 119 milliseconds
[INFO] F8: [fabric8/springboot-docker-compose:3.5] "spring-boot": Built image sha256:221e6
[INFO] F8: [fabric8/springboot-docker-compose:3.5] "spring-boot": Removed old image sha256:9125e
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ springboot-docker-compose ---
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/target/springboot-docker-compose-3.5.jar to /igUsers/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5.jar
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/pom.xml to /Users/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5.pom
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/openshift.yml to /Users/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5-openshift.yml
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/openshift.json to /Users/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5-openshift.json
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/kubernetes.yml to /Users/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5-kubernetes.yml
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/target/classes/META-INF/fabric8/kubernetes.json to /Users/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5-kubernetes.json
[INFO] Installing /Users/nnallam/IdeaProjects/kompose-maven-example/target/springboot-docker-compose-3.5-helm.tar.gz to /Users/nnallam/.m2/repository/io/fabric8/springboot-docker-compose/3.5/springboot-docker-compose-3.5-helm.tar.gz
[INFO] 
[INFO] <<< fabric8-maven-plugin:3.5.28:deploy (default-cli) < install @ springboot-docker-compose <<<
[INFO] 
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.28:deploy (default-cli) @ springboot-docker-compose ---
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/ig doesn't have permission. forbidden: User "system:anonymous" cannot get path "/".
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.845 s
[INFO] Finished at: 2019-08-09T19:05:38+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:deploy (default-cli) on project springboot-docker-compose: Failure executing: GET at: https://f3cc1b112ec1fa8eae3a9ad684edabfa.yl4.us-east-1.eks.amazonaws.com/. Message: Forbidden! User arn:aws:eks:us-east-1:415867864530:cluster/igcluster doesn't have permission. forbidden: User "system:anonymous" cannot get path "/". -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
narsi-macbook-pro:kompose-maven-example nnallam$

**Comment by hangyan** [comment]
Seems likes a RBAC issue. Are you familar with kubernetes' RBAC ?
