### ISSUE TITLE
Kompose not replacing environment variables from .env file

### ISSUE THREAD

**Issue by mahgo** [kubernetes/kompose#1164]
I'm using Kompose version 1.18.0 on Windows 10.

When I run kompose convert on my docker compose file, it replaces it with nothing. This is despite docker compose detecting and using the .env file correctly.

```
image: test:${tag}
container_name: test-${tag}
```

becomes:

```
 containers:
      - image: 'test:'
        name: test-
```
This is my .env file:
`tag=test123`

If I set the tag environment variable in my Windows environment variables, it does pick it up however. Is there something I'm missing?

Edit: using docker compose v3

**Comment by bialas1993** [comment]
@mahgo you should try this ```docker-compose config > docker-compose-resolved.yaml && kompose convert -f docker-compose-resolved.yaml```

**Comment by mahgo** [comment]
Thanks @bialas1993 !
