### ISSUE TITLE
Just delete Windows from your installation guide...

### ISSUE THREAD

**Issue by GabrielBB** [kubernetes/kompose#1167]
This thing doesn't work on Windows (Check issue #1122. I'm having the same problem). What's the point in having Windows as supported OS?

**Comment by hangyan** [comment]
I'm truly sorry for your condition..We don't have windows env and enough devopers to make any progress on windows support for now..

**Comment by jaredallard** [comment]
@cdrage Are you working on this? If not, I can take a crack at it

**Comment by cdrage** [comment]
@jaredallard Sure! Go ahead. I tried to work on it but to be honest got caught up with work.
