### ISSUE TITLE
FATA Unable to load yaml/json file for version parsing: open docker-compose.yml: permission denied

### ISSUE THREAD

**Issue by jjghub** [kubernetes/kompose#1172]
Goom Morning

I am trying to do a kompose (**kompose -f docker-compose.yml up**) to convert this docker-compose.yml file:

_version: '3'
services:
    angular:
        image: nginx:alpine
        ports:
          - "4200:80"
        volumes:
          - ./front/dist:/usr/share/nginx/html  
    postgres:
        image: postgres:11
        container_name: portpostgres
        ports:
          - "5432:5432"
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_PORT=5432
        volumes:
            - ./bbdd/import-postgres.sql:/docker-entrypoint-initdb.d/import-postgres.sql    
    portabcjetty:
        image: jettyabc
        container_name: jettyabc
        build: ./abc
        ports:
            - "8080:8080"          
    portloginjetty:
        image: jettylogin
        container_name: jettylogin
        build: ./login
        ports:
            - "8081:8080"_                     
          

The **error** that it is throwing is: 

_FATA Unable to load yaml/json file for version parsing: open docker-compose.yml: permission denied_

I make a chown -R root:root ./dockerabcproy/  and a chmod -R 664 ./dockerabcproy  

_drw-rw-r-- 2 root    root    4096 oct 11 06:31 dockerabcproy_

I'm pretty lost and I don't know what to do. Please, Tell me what more information you need. 

Thank you!

**Comment by jjghub** [comment]
Now with chmod -R 774:


root@ABCdocker:/home/ABC/dockerABC# kompose -f docker-compose.yml convert
WARN Volume mount on the host "/home/ABC/dockerABC/front/dist" isn't supported - ignoring path on the host
WARN Volume mount on the host "/home/ABC/dockerABC/bbdd/import-postgres.sql" isn't supported - ignoring path on the host
INFO Kubernetes file "angular-service.yaml" created
INFO Kubernetes file "portcrmjetty-service.yaml" created
INFO Kubernetes file "portloginjetty-service.yaml" created
INFO Kubernetes file "postgres-service.yaml" created
INFO Kubernetes file "angular-deployment.yaml" created
INFO Kubernetes file "angular-claim0-persistentvolumeclaim.yaml" created
INFO Kubernetes file "portcrmjetty-deployment.yaml" created
INFO Kubernetes file "portloginjetty-deployment.yaml" created
INFO Kubernetes file "postgres-deployment.yaml" created
INFO Kubernetes file "postgres-claim0-persistentvolumeclaim.yaml" created

root@ABCdocker:/home/ABC/dockerABC# kompose -f docker-compose.yml up
WARN Volume mount on the host "/home/ABC/dockerABC/front/dist" isn't supported - ignoring path on the host
INFO Build key detected. Attempting to build and push image 'jettycrm'
INFO Building image 'jettycrm' from directory 'crm'
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service portcrmjetty: Unable to build image. For more output, use -v or --verbose when converting.: dial unix /var/run/docker.sock: connect: permission denied

Why can I do?

Regards

**Comment by hasanakg** [comment]
Hello,

You need to use `sudo` with `kompose up` or if you don't want to do this just add you user to `docker` group so you can use `docker` without `sudo`:

```bash 
sudo usermod -aG docker <your-user>
```

**Note:** After running this command you should log out and back in for this to take effect.

You can find further information on docker documentation: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by lucasmfdotcom** [comment]
In my case, i try to convert a docker-compose.yml with KOMPOSE, but fails.
Solved starting minicube.

# kompose convert -f docker-compose.yml 
# FATA Unable to load yaml/json file for version parsing: open docker-compose.yml: no such file or directory 

# minikube start
