### ISSUE TITLE
Provide checksum file for releases

### ISSUE THREAD

**Issue by tprasadtp** [kubernetes/kompose#1173]
Currently  checksums are in the release description, but I think it would be better if they are (also) provided as checksum files. Its much simpler to get the checksums file than getting it from release description for automated installations.
Eg. for Ansible `get_url` provides a way to verify checksums

**Comment by cdrage** [comment]
Hey @tprasadtp check out the new release! I've uploaded a CHECKSUM file for comparison / checks :)

https://github.com/kubernetes/kompose/releases

**Comment by tprasadtp** [comment]
@cdrage  That was quick! Thanks!

**Comment by tprasadtp** [comment]
@cdrage v1.21.0 is missing checksums file again, though it looks like the release script has not changed. Could you please take a look at it? On a side note, don't you think its better to use goreleaser? I will be happy to submit PR if you are willing to accept it.
