### ISSUE TITLE
Clean up outside collaborators

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kompose#1176]
Hey there @kubernetes/kompose-admins,

One of the github-admins here. -- We have a [longstanding issue] on cleaning up outside collaborators, and are now actively planning on removing them on December 1st.

At this point, people that are actively contributing to the Kubernetes project should be promoted to [org members][mem], and any repo specific permissions should be managed through their associated configuration in [kubernetes/org].

With that in mind, the following people are listed as outside collaborators:

- @containscafeine 
- @piyush-garg 
- @pradeepto 
- @surajnarwade 

They have been inactive (<5 [devstats] recorded contributions in the past year across all Kubernetes orgs), and I'd opt for removal from direct repo permissions. 

Just a general reminder, not having direct permissions **does not stop** folk from contributing. It just means they'd have less permissions (would need  `/ok-to-test` on PRs etc).

If you have any questions or comments, please don't hesitate to ask in here or feel free to poke me in slack 👍 

Thanks!

Assigning to kompose admins:
/assign @cdrage @janetkuo @kadel @ngtuna @sarahnovotny @sebgoa

/sig contributor-experience
/priority important-soon

[longstanding issue]: https://github.com/kubernetes/community/issues/3178
[mem]: https://github.com/kubernetes/community/blob/master/community-membership.md#member
[kubernetes/org]: https://github.com/kubernetes/org
[devstats]: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by cdrage** [comment]
@mrbobbytables Done!

I've removed everyone that I can as "outside contributors" from the repo (collaborators).

I do however have no permission to remove them from the following teams:
- https://github.com/orgs/kubernetes/teams/kompose-admins
- https://github.com/orgs/kubernetes/teams/kompose-maintainers
- https://github.com/orgs/kubernetes/teams/kompose-contributors

**Comment by mrbobbytables** [comment]
@cdrage It's all good, those groups are managed via peribolos where they're required to be org members :) 
The config for them is here:
https://github.com/kubernetes/org/blob/d6a90ee600549ccb8e391a7580e7289e61a0f175/config/kubernetes/org.yaml#L1498-L1527

The `kompose-contributors` team can probably be removed, they're setup with `read` permissions  on the repo and that's the default for any kubernetes org member.

**Comment by cdrage** [comment]
@mrbobbytables Thanks!

I've opened up a PR: https://github.com/kubernetes/org/pull/1359

**Comment by mrbobbytables** [comment]
outside collaborators cleaned up ✔️ 
teams cleaned up ✔️ 

Thanks @cdrage :)

/close
