### ISSUE TITLE
Convert Helm to Docker-compose

### ISSUE THREAD

**Issue by Formartha** [kubernetes/kompose#1183]
Hi,

We got a use case where we need to convert helm charts into Docker-compose ones.
I didn't find any way of doing it in the manual - is there such ability that I've missed?

Thanks,
-M

**Comment by hangyan** [comment]
kompose can convert docker-compose to helm charts.

**Comment by ChanderG** [comment]
@Formartha, kompose is meant for going from docker-compose to k8s/helm/openshift, not the other way around.

**Comment by hangyan** [comment]
close for now. @Formartha If you have further questions, feel free to open this issue again
