### ISSUE TITLE
Create route for openshift - targert port should be a string

### ISSUE THREAD

**Issue by kkonopka123** [kubernetes/kompose#1184]
Hi, first time ever creating an github issue on public forum. Please be forgiving.
I am trying to convert docker-compose.yml to openshift yml configuration files. When I specified port and label kompose.service.expose='true', the route that is being created has a target port as an integer. The openshift complains about not seeing the port exposed on the service. When I manually change the port on openshift route configuration to string, the route finds the port on the service.

It would be super awesome if we could have this port to be transformed into a string.

I attached pictures showing some of my configuration. 

![Screen Shot 2019-11-19 at 12 31 53 PM](https://user-images.githubusercontent.com/41640598/69170842-cb5f9f80-0ac8-11ea-98e3-ddb00b9d3025.png)
![Screen Shot 2019-11-19 at 12 31 42 PM](https://user-images.githubusercontent.com/41640598/69170844-cb5f9f80-0ac8-11ea-95c5-969d38f2d31e.png)
![Screen Shot 2019-11-19 at 12 31 31 PM](https://user-images.githubusercontent.com/41640598/69170845-cbf83600-0ac8-11ea-934d-6887d43fb14b.png)

**Comment by hangyan** [comment]
You mean the port should be converted to a string but the result is a int?

**Comment by kkonopka123** [comment]
Yes, sorry if i wasn't clear.
