### ISSUE TITLE
Follow docker compose conventions for merging top level keys

### ISSUE THREAD

**Issue by ChanderG** [kubernetes/kompose#1185]
Top level keys apart from `services` such as `networks`, `volumes`, `secrets` etc should be merged from multiple files (new files over-writing sub key/values as needed). This is the way `docker-compose` works.

In `kompose`, all other keys apart from `services` from subsequent files are simply being ignored.

**Comment by hangyan** [comment]
close by #1187. Thanks @ChanderG
