### ISSUE TITLE
Follow docker compose conventions for service fields merge

### ISSUE THREAD

**Issue by ChanderG** [kubernetes/kompose#1186]
According to https://docs.docker.com/compose/extends/, 

1. multi-value options such as `ports`, should be concatenated.
2. Some specific keys should be merged, eg `environment`. 

Currently, in `kompose`, all fields are over-written.

**Comment by ChanderG** [comment]
Previous related issues: #1081

**Comment by hangyan** [comment]
@ChanderG Since there are not so many maintainers by now, if i create a PR, there will be no other guys review it for now. So if you can create a PR for this, that will be great and i will be review it ASAP

**Comment by ChanderG** [comment]
@hangyan Sure, will do so soon.

**Comment by hangyan** [comment]
* Merge
- [] environment

**Comment by ChanderG** [comment]
I have actually already coded out the feature. Have not pushed anything yet as I have to update/write the tests. Will hopefully get around to that by next week.

**Comment by hangyan** [comment]
@ChanderG Great, i will focus on other issues for now

**Comment by hangyan** [comment]
I have merged a lot of PRs these days, you may need to rebase it first..

**Comment by hangyan** [comment]
close by #1226
