### ISSUE TITLE
charts reporting errors generated by helm3 version installation

### ISSUE THREAD

**Issue by fengshunli** [kubernetes/kompose#1194]
![image](https://user-images.githubusercontent.com/18587688/69841554-a9210b00-129a-11ea-8f71-13f774242de9.png)

yaml files
![image](https://user-images.githubusercontent.com/18587688/69841816-b7235b80-129b-11ea-96c9-aae2c491613a.png)

**Comment by hangyan** [comment]
This is a issue related to #1158. If not a working one, since the code change is massive. We are still looking for some other solutions, for now you can mannuly change the `apiVersion` of all the workload resource(Deployment....) to `apps/v1`

**Comment by fengshunli** [comment]
You can replace extensions/v1beta1, with sed batch but also add selector, and io.kompose.service: web's labels is still dynamic, the value of this io.kompose.service can not be written to death, it is very inconvenient to deploy microservices, it is recommended to optimize
