### ISSUE TITLE
Helm lint throws errors on chart.yaml

### ISSUE THREAD

**Issue by nabhavs** [kubernetes/kompose#1200]
Helm lint command fails on helm files created due to following issues:
- [ERROR] Chart.yaml: directory name (XXX_DIR) and chart name (A new XXX project) must be the same
- [ERROR] Chart.yaml: apiVersion is required. The value must be either "v1" or "v2"

We could fix these issues and contribute to the project. Please let us know if we could create a PR for this.

**Comment by hangyan** [comment]
Yes, of course. This is a great improvement
