### ISSUE TITLE
Error while deploying application: Get http://localhost:8080/api: dial tcp [::1]:8080: connect: connection refused 

### ISSUE THREAD

**Issue by ryannix123** [kubernetes/kompose#1201]
Latest build of kompose, 1.19.0. This is for an Openshift 3.11 cluster.

**Comment by hangyan** [comment]
This is because most of the early version of kubernetes have 8080 port open ,but not anymore in the latest versions, These settings is hard-coded  in the library kompose ref to ,we are still trying to find some solutions..

**Comment by hangyan** [comment]
Can you try `export KUBERNETES_MASTER=<url>` first?

**Comment by walter211** [comment]
run this in new terminal tab：
`kubectl proxy --port=8080`

**Comment by glafir** [comment]
`└─[0] <> kubectl proxy --port=8080
Starting to serve on 127.0.0.1:8080
`
`export KUBERNETES_MASTER=https://127.0.0.1:8080`
`../bin/./kompose up`

I get this error too (((
`FATA Error while deploying application: Get https://127.0.0.1:6443/api: x509: certificate is valid for 10.96.0.1, 10.50.2.250, not 127.0.0.1`

**Comment by gargankur2008** [comment]
I also have similar issue on the latest kompose . My error is:
`FATA Error while deploying application: Get "https://127.0.0.1:6443/api": dial tcp 127.0.0.1:6443: connect: connection refused `

**Comment by gargankur2008** [comment]
Duplicate of #1131

**Comment by hangyan** [comment]
close by #1297
