### ISSUE TITLE
doesn't work out of box with the tutorial on the website

### ISSUE THREAD

**Issue by kundeng** [kubernetes/kompose#1202]
A lot of things are outdated? Is this project dead?

kubectl create -f redis-master-deployment.yaml -f redis-master-service.yaml
unable to recognize "redis-master-deployment.yaml": no matches for kind "Deployment" in version "api/v1"

After correcting it, it still doesn't work:
kubectl create -f redis-master-deployment.yaml -f redis-master-service.yaml
error validating "redis-master-deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

Even with validate=false, it still doesn't work:
reate -f redis-master-deployment.yaml -f redis-master-service.yaml --validate=false
Error from server (Invalid): error when creating "redis-master-deployment.yaml": Deployment.apps "redis-master" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"io.kompose.service":"redis-master"}: `selector` does not match template `labels`]

**Comment by michielglibert** [comment]
See #1180 for fix

**Comment by hangyan** [comment]
I will create a new PR for this these days...So sorry for this inconvenient
