### ISSUE TITLE
start_period causes FATA start_period Additional property start_period is not allowed

### ISSUE THREAD

**Issue by vsmadhu** [kubernetes/kompose#1224]
Team,

I want to wait for my health-check command so I use start_period in my docker compose file.
When I try to use  kompose to convert my file I keep getting error 
FATA start_period Additional property start_period is not allowed

I know start_period is supported from version 3.4 for docker-compose. so I tried to set the file version to 3.7 which is the actual version i use in my docker compose file, but was given a message saying I can only use 1, 2 & 3 so I used version: '3' but I am still getting the error

How do I get **start_period** to be part of the input file.
My docker-compose version is **docker-compose version 1.25.1-rc1, build d92e9bee**
Example
version: '3'

networks:
  example:
    driver: overlay

services:

  reverseproxy:
    image: nginx:stable
    healthcheck:
      test: service nginx status | grep running || exit 1
      interval: 2s
      retries: 2
      start_period: 6s      
      timeout: 1s
    ports:
      - "80:80"
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - versions.html:/etc/nginx/html/versions/index.html
    networks:
      - example

**Comment by hangyan** [comment]
which version of `kompose` do you use ?

**Comment by hangyan** [comment]
after set docker-compose version to `3.7`, it works fine on the latest `1.19.0` version of `kompose`. Can you give it a try?

**Comment by vsmadhu** [comment]
kompose version I am using is 1.18.0 ()
Let me try version 1.19.0 to see if it fixes the issue.
I will update this post once it's done.

**Comment by vsmadhu** [comment]
Using the below command if I download kompose I am still getting version 1.18.0 ()
How do I get version 1.19.0 for my mac running 10.14.6 (18G103) Mojave

curl -L https://github.com/kubernetes/kompose/releases/download/v1.20.0/kompose-darwin-amd64 -o kompose

**Comment by hangyan** [comment]
Are you sure you are using the right `PATH`, i just verfied the url, it works fine.
Can you run `which kompose` to make sure?

**Comment by vsmadhu** [comment]
Hangyan

Thank you, you were right, I was downloading the kompose latest version from git to the folder were my docker file was and assuming that I was running the file from that location

running the which command showed me that actually I was executing kompose from /usr/local/bin/

I moved the file to the correct location now and the version is showing up as 1.20.0 (f3d54d784)
let me try executing the the convert command now and see how it goes.

**Comment by vsmadhu** [comment]
@hangyan Thank you for the help
I was was able to complete the process with start_period in docker_compose file
On other question 
I have a 
WARN Volume mount on the host "/Users/USERNAME/GitLab/App-Name/reverse-proxy/nginx.conf" isn't supported - ignoring path on the host 
Is there a preferred method of loading a flie ?

what I doing in the compose file is 
 volumes:
      - ../../reverse-proxy/nginx.conf:/etc/nginx/nginx.conf

**Comment by hangyan** [comment]
You can check the `--volumes` flag, i think `hostPath` is the best option for now. 
Althogh on the master build of `kompose` ,i have add support for `configMap`,  the volumes files will be read into configmaps and mounted to the pod, you can try it if you are willing to

**Comment by vsmadhu** [comment]
The start_period issue was resolved by using the latest version of kompose.
