### ISSUE TITLE
How do I start a POD with my transformed files

### ISSUE THREAD

**Issue by vsmadhu** [kubernetes/kompose#1234]
Hello 

I am seeing 3 files being created for a single docker run command in my file 
for example the first set called reverseproxy shown created 3 files.
the next webapp created 3 more files.

My question is how do I start a pod with all my images running in it  

version: '3.7'

networks:
  app:
    driver: overlay

services:

  reverseproxy:
    image: ngnix:latest
    healthcheck:
      test: service nginx status | grep running || exit 1
      interval: 2s
      retries: 2
      start_period: 6s
      timeout: 1s
    ports:
      - "80:80"
    volumes:
      - ../../reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app

  webapp:
    image: somewebapp:latest
    healthcheck:
      test: curl --fail -s -k http://localhost || exit 1
      interval: 2s
      retries: 2
      start_period: 6s
      timeout: 1s
    ports:
      - "9000:80"
    networks:
      - app

& so on
reverseproxy-claim0-persistentvolumeclaim.yaml
reverseproxy-deployment.yaml
reverseproxy-service.yaml

**Comment by hangyan** [comment]
Sorry i didn't follow, could you explain you intention again?

**Comment by vsmadhu** [comment]
Hello Hang

When I convert my docker compose file to kubernetes using kompose, I am getting 3 files for each docker container mentioned in the file.

I have attached my docker file. Once you run kompose convert -f sample-docker-compose.txt
My question is how can I go about creating the objects in kubernetes with the transformed files ?

[sample-docker-compose.txt](https://github.com/kubernetes/kompose/files/4031063/sample-docker-compose.txt)

**Comment by hangyan** [comment]
try `kompose up -f sample-docker-compose.txt`

**Comment by vsmadhu** [comment]
I tired that am seeing a error 
Error while deploying application: Get http://localhost:8080/api: dial tcp [::1]:8080: connect: connection refused like mentioned in the issue https://github.com/kubernetes/kompose/issues/1201

My environment is 
I am running minikube
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392

kubeclt version 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hangyan** [comment]
This is a known issue, you can try
`KUBERNETES_MASTER=https://127.0.0.1:6443 kompose...`,  https://127.0.0.1:6443 shoule be your kubernetes api server's url
