### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by gjcarneiro** [kubernetes/kompose#1236]
This is generating: 
```
apiVersion: extensions/v1beta1 
kind: Deployment
```

This Deployment version was deprecated and no longer works in recent versions of k8s (e.g. 1.16).

Now you have to specify `apiVersion: apps/v1` and modify slightly the template (labelSelector field needed).

**Comment by hangyan** [comment]
This issue has been fixed by pr #1207 . It will be released in the next month. Sorry for you inconvenient

**Comment by mash1t** [comment]
fyi Workaround for minikube (until release):
`minikube start --extra-config=apiserver.runtime-config=apps/v1beta1=true,extensions/v1beta1/deployments=true`

**Comment by gajdot** [comment]
Still no solution for this? /remove-lifecycle stale

**Comment by jbresciani** [comment]
https://kompose.io/installation/ still references 1.19.0 which contains this bug, that page should be updated to reference 1.21.0 which contains the fix for this issue.

curl -L https://github.com/kubernetes/kompose/releases/download/v1.21.0/kompose-darwin-amd64 -o kompose

**Comment by lmsurpre** [comment]
I hit this one today for this same reason, who can update https://kompose.io/installation/ ?

**Comment by mash1t** [comment]
@hangyan are you the person to address to update the doc?

**Comment by mash1t** [comment]
@hangyan bump for updating the docs

**Comment by SamsonNelson** [comment]
+1
