### ISSUE TITLE
[Feature]: Validation of supported attributes within a docker-compose file

### ISSUE THREAD

**Issue by jbmcfarlin31** [kubernetes/kompose#1237]
Given the [conversion matrix](https://github.com/kubernetes/kompose/blob/master/docs/conversion.md), it would be nice to have a feature within the `kompose` utility to be able to validate a `docker-compose` file to see what attributes defined in that yaml will be converted, versus which attributes will not be supported.

As an example, if a `docker-compose` file has the attribute `security_opt` defined, the matrix says "Kubernetes uses its own container naming scheme", the command might be:
```
kompose validate -f docker-compose.yaml
```
And when it reaches the attribute `security_opt`, it might error with:
```
[FAIL]: the option `security_opt` is not supported <additional metadata here potentially>?
```
The use case for this is using `kompose` within a GitOps pipeline, we are taking users compose files and converting them on their behalf so they don't need to know kubernetes, however, there currently is no way to easily relay to them what is a supported element within the compose file.

If we had the ability to validate the compose file with `kompose`, we could potentially write our own wrapper around the output of the `kompose validate` command to be able to tell the user "_Hey, you used security_opt, which is something we don't support_".

Thoughts and discussion are welcome surrounding this, and if I can help in anyway please let me know. I am mainly a Python user, but know _some_ Golang. 

Thanks!

**Comment by hangyan** [comment]
@jbmcfarlin31  This is a good idea, i will work on this ASAP. It will be include into the next release

**Comment by jbmcfarlin31** [comment]
@hangyan is there any update on this? Thanks!
