### ISSUE TITLE
Instructions Corporate CLA

### ISSUE THREAD

**Issue by fetzerch** [kubernetes/kompose#1241]
@hangyan We'd like to contribute a few patches to Kompose. According to [CONTRIBUTING.md](https://github.com/kubernetes/kompose/blob/5633b7bff587c7ff11434470fabd3d19cd1840f6/CONTRIBUTING.md#contributor-license-agreements) we need to sign the corporate CLA and ask on slack for access and instructions. You mentioned it's difficult to reach you on slack. Therefore I'm filing this issue here. Can you help out please?

**Comment by hangyan** [comment]
@fetzerch  You can just file the PR, a robot will do the check and give in insturctions about how to sign the CLA. It's very straightforward

**Comment by fetzerch** [comment]
Thanks. I'll try to get it working.
