### ISSUE TITLE
Release 1.12.0 is missing windows exe

### ISSUE THREAD

**Issue by fmotrifork** [kubernetes/kompose#1250]
The release notes for v1.12.0 refers to the following url for the windows binary: `https://github.com/kubernetes/kompose/releases/download/v1.21.0/kompose-windows-amd64.exe`

The kompose-windows-amd64.exe binary is also listed in the Checksums table. But this binary not released as part of the assets in this release.

See: https://github.com/kubernetes/kompose/releases/tag/v1.21.0

**Comment by bastianeicher** [comment]
Also, the description text for the release says "Kompose 1.23.0", despite the release being 1.21.0.

**Comment by hangyan** [comment]
@cdrage

**Comment by cdrage** [comment]
@bastianeicher @fmotrifork Sorry about that! I had a brain fart with regards to the description text.

I've also re-uploaded the binaries. Looks like I uploaded it at just the right time when the GitHub API went down, so half the binaries dissapeared.

The release now has the correct binaries. Thanks for bringing this to my attention!
