### ISSUE TITLE
Losing quotes when converting "yes" and "no"

### ISSUE THREAD

**Issue by azkore** [kubernetes/kompose#1253]
Before this commit https://github.com/kubernetes/kompose/commit/88a3a27ca8c2c2e3df52f2304cf6fd26e9163065 kompose converted quoted "yes" and "no" values of environment variables to the same values in the resulting helm chart. For example:

    environment:
      APP_CREATE_TESTUSERS: "no"

was converted to:

        env:
        - name: APP_CREATE_TESTUSERS
          value: "no"

But after the change the conversion loses quotes:

        env:
        - name: APP_CREATE_TESTUSERS
          value: no

which leads to errors like 

"The request is invalid: patch: Invalid value: 
...
unrecognized type: string"

when trying to apply the converted manifests (probably due to https://github.com/kubernetes/kubernetes/issues/34146)

"true" and "false", on the other hand, are still properly quoted even after the change

**Comment by hangyan** [comment]
I will look up into it

**Comment by hangyan** [comment]
Seems caused by the change of yaml library we are using. To be honest, yaml is a bad desgined language and it's very complicated. Hope we can find a good library to support both indent and the new standard. If not, or more users are reporting this issue, we will rollback this commit.

**Comment by campos-ddc** [comment]
Having the same issue with`"off"` string being converted to `off`, which apparently can also be interpreted as a boolean `false` depending on yaml implementation (!)

**Comment by hangyan** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/3939015/97952390-296bbc80-1dd8-11eb-8bd6-516499775ae8.png">

Tested it on 1.22, seems fixed. Feel free to notify me to reopen this issue if it's not working
