### ISSUE TITLE
Getting user and password prompt while doing Kompose up

### ISSUE THREAD

**Issue by vpuria** [kubernetes/kompose#1269]
I am getting below Prompt while running Kompose up where as when i directly run kompose convert its converting the deployment file with the web service but not the redis .
**********************************************************************************
# kompose up
INFO We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 
 
Please enter Username:

**Comment by moluzhui** [comment]
did you find any solution? I have the same situation with you. @vpuria

**Comment by mbernasocchi** [comment]
did anyone find a solution? it only happens with 1.21.0 (992df58d8). 1.20.0 works as expected

**Comment by hangyan** [comment]
close by #1297

**Comment by RichardBronosky** [comment]
I had this issue too even though my `kubectl` calls were fine. Turns out that the root user did not have the access needed. so I copied the ~/.kube/config file to the root user's home.

```
sudo mkdir -p /root/.kube; sudo cp ~/.kube/config /root/.kube/
ip="$(ip route get 1 | awk 'NR==1{print $7}')"
sudo -H kompose up --server https://$ip:6443
```
