### ISSUE TITLE
Deprecating kompose up and kompose down in favor of only kompose convert

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1275]
So... a few issues:

1. We're using an old library and it's very hard / a LOT of changes in order to go from the old golang kubernetes library to the new one. (ex: https://github.com/kubernetes/kompose/issues/1264)
2. Lot's of issues with regards to connecting to local servers (minikube isn't port 8080 anymore..)
3. `kompose convert` is *very* popular in terms of converting. Most people using `kompose convert -o foobar && kubectl apply -f foobar/`
4. We do not have enough maintainers to maintain using `kompose up` and `kompose down`, using only `kompose convert` would reduce the amount of work and maintainability will be easier.

Should we just deprecate `kompose down` and `kompose up`?

Ping @kubernetes/kompose-admins @kubernetes/kompose-maintainers @kadel @hangyan @surajnarwade @surajssd @hangyan @ngtuna

**Comment by surajnarwade** [comment]
I agree , +1 from my side

**Comment by trawler** [comment]
Since we started exploring Kompose I can only agree with the above. `kompose up/down` was never an option for us, but we love the convert + helm functionality.
So +1  👍

**Comment by cdrage** [comment]
Thanks all, even though it's only been 24 hours, I've got nothing but praise in the e-mail as well as this issue.

I'll change this in **one week** in order to give a **lazy consensus** in terms of removing `kompose up` and `kompose down`.

**Comment by hangyan** [comment]
+1

**Comment by kaceo** [comment]
New to Kubernetes stack, so my opinion is only from a docker-compose user.  Is it correct to say the tool currently only handles partial conversion?  I am thinking about the use of persistent volume, ingress, depends on, secrets, environment vars, etc. these need further tweaking before sending to kubectl?  If so, it is probably better to make this tool only focus on convert, and add hints and lints to help the compose user fill in the missing gaps.  As a new Kubernetes user I am most interested to convert a fully working docker app into Kubernetes with least amount of re-architecting, and so far this tool has helped me but still left a lot of the puzzle.

**Comment by gargankur2008** [comment]
I agree. My `kompose convert` created about 15 yaml files, is there a way to apply all of them without putting them in terminal ?

**Comment by cdrage** [comment]
Sorry for the delay, I'm looking at implementing this shortly.

**Comment by gargankur2008** [comment]
> Sorry for the delay, I'm looking at implementing this shortly.

No rush on my side. I just wanted to add a possible improvement. Thanks for the work you are doing.

**Comment by croensch** [comment]
> is there a way to apply all of them without putting them separately in terminal every time?

As the first comment mentions `kompose convert -o foobar/` and `kubectl apply -f foobar/` does bring up everything. @gargankur2008

**Comment by gargankur2008** [comment]
> > is there a way to apply all of them without putting them separately in terminal every time?
> 
> As the first comment mentions `kompose convert -o foobar/` and `kubectl apply -f foobar/` does bring up everything. @gargankur2008

Hi @croensch, thanks for th clarification.
