### ISSUE TITLE
kompose up seems to not use the build context's .dockerignore file

### ISSUE THREAD

**Issue by michaeldbianchi** [kubernetes/kompose#1278]
When attempting to run `kompose up`, I run into a build error referenced in issue [656](https://github.com/kubernetes/kompose/issues/656) saying:

```
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service wrangler: Unable to create a tarball: read /Users/michaelbianchi/workspace/mercury-platform/wrangler/_build/dev/lib/certifi/ebin: is a directory
```

While the other issue states `kompose` doesn't handle symlinks well, this directory should never be included in the build context due to being ignored in the `.dockerignore` file. If `kompose` is going to handle the building of images, it should respect things handled by `docker-compose` such as `.dockerignore`.

It's also possible I have this poorly setup, but everything else looks right. `kompose convert` works. Source code is held in https://github.com/michaeldbianchi/mercury-platform

Verbose:
```
 λ on minikube in ~/workspace/mercury-platform on  master [!?] kompose -f docker-compose.yml -v up
DEBU Docker Compose version: 3
WARN Volume mount on the host "/Users/michaelbianchi/workspace/mercury-platform/data" isn't supported - ignoring path on the host
INFO Build key detected. Attempting to build image 'michaeldbianchi/wrangler:dev'
DEBU Build image working dir is: /Users/michaelbianchi/workspace/mercury-platform
DEBU Build image context is: /Users/michaelbianchi/workspace/mercury-platform/wrangler
INFO Building image 'michaeldbianchi/wrangler:dev' from directory 'wrangler'
DEBU Created temporary file /var/folders/65/6cd8mczj1d198sxvrq2vb7v40000gp/T/kompose-image-build-475960662 for Docker image tarballing
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service wrangler: Unable to create a tarball: read /Users/michaelbianchi/workspace/mercury-platform/wrangler/_build/dev/lib/certifi/ebin: is a directory
```

**Comment by michaeldbianchi** [comment]
Note that if I delete the _build and deps directories (which are in the .dockerignore), `kompose up` worked just fine. However, since elixir builds creates directories with symlinks, it makes kompose almost unusable since every time I run tests or a dev server, those directories are populated.

**Comment by hangyan** [comment]
close by #1297
