### ISSUE TITLE
kompose convert with openshift option is ignoring hyphens in docker image name

### ISSUE THREAD

**Issue by ltutar** [kubernetes/kompose#1282]
Hi,

When I convert a docker-compose file with the command
`kompose --file gitlab-runner-docker-compose.yml convert
`
I get the result with the correct image name i.e.

> 
>     spec:
>       containers:
>       - image: gitlab/gitlab-runner:alpine
>         name: gitlab-runner 
>  

However when I use the command
`kompose --file gitlab-runner-docker-compose.yml --provider openshift convert
`
i.e. with openshift as provider,
then I get the image name 

>    containerNames:
>       - gitlab-runner
>       from:
>         kind: ImageStreamTag
>         name: runner:alpine
> 

It looks like the hyphens are ignored.

Using kompose version 1.19.0.

I also attached the files.

[gitlab-runner-docker-compose.yml.txt](https://github.com/kubernetes/kompose/files/4824758/gitlab-runner-docker-compose.yml.txt)
[openshift-runner-deploymentconfig.yaml.txt](https://github.com/kubernetes/kompose/files/4824759/openshift-runner-deploymentconfig.yaml.txt)
[kubernetes-runner-deployment.yaml.txt](https://github.com/kubernetes/kompose/files/4824760/kubernetes-runner-deployment.yaml.txt)

**Comment by hangyan** [comment]
This was by design, It's the service name
