### ISSUE TITLE
Handle minor versions

### ISSUE THREAD

**Issue by vertti** [kubernetes/kompose#1283]
Docker-compose documentation warns that using `version: '3'` will NOT use the latest 3.x series, but instead use `3.0`. Trying to run `kompose convert` using explicit version like `3.8` will throw:

```
FATA Version 3.8 of Docker Compose is not supported. Please use version 1, 2 or 3
```

I think this is in clear conflict with how docker-compose handles versioning.

**Comment by vertti** [comment]
Ok, turns out it's just `3.8` that isn't supported, using `3.7` works just fine. But then I have to say that the error message is super misleading (`use 1, 2 or 3`). It should then list all supported version tags.

**Comment by jongio** [comment]
I ran into this today as well.  Is 3.8 support coming soon?


azsdke2e

**Comment by advaithm** [comment]
yeah is docker 3.8 support in the works?
