### ISSUE TITLE
Kompose up with remote Openshift

### ISSUE THREAD

**Issue by vertti** [kubernetes/kompose#1284]
I have a Openshift cluster running (not locally). My kubectl connects to it correctly. But running 

```
kompose --provider=openshift --volumes emptyDir --build build-config up
```
fails to connect to localhost, where it definitely shouldn't be connecting in the first place:

```
FATA Error while deploying application: Get https://127.0.0.1:6443/api: dial tcp 127.0.0.1:6443: connect: connection refused
```

Does everyone just use `kompose` with local minikube etc, or what am I doing wrong?

**Comment by hangyan** [comment]
close by #1297
