### ISSUE TITLE
Unsupported config option for service: `init` --- is there a kubernetes equivalent?

### ISSUE THREAD

**Issue by MarkIannucci** [kubernetes/kompose#1290]
I'm trying to convert a docker compose file to kubernetes yaml files.  The file I'm converting is version 2.2 and it uses the `init:true` [config option](https://docs.docker.com/compose/compose-file/compose-file-v2/#init).  The functionality was added to docker compose in version 2.2 and re-added in version 3.7.

Unfortunately, those minor versions are not supported in version 1.21.0.  If I change my file version to 3, I get an error which reads:
    
    Unsupported config option for service: `init` 

Is there a kubernetes equivalent to setting `init:true` in a docker compose file that I can use in the meantime?

**Comment by hangyan** [comment]
see this issue: https://github.com/docker/libcompose/issues/459. There is not much thing we can do now to support this feature. And kubernetes does not have a equivalent feature to this
