### ISSUE TITLE
Kompose down fails due to a failed connection to https://127.0.0.1:6443/api

### ISSUE THREAD

**Issue by guyarb** [kubernetes/kompose#1293]
I used `kompose up` and got `FATA Error while deleting application: Get https://127.0.0.1:6443/api: dial tcp 127.0.0.1:6443: connect: connection refused`, after short lookup in google, I've found the flag `--server`.
When I tried using `kompose down` I got the same error, but I didn't see the same flag in `kompose down -h`.
I'm using kompose of version `1.21.0 (992df58d8)`  on ubuntu 18.04 machine.

**Comment by fullkomnun** [comment]
I had the same issue, try to check if that is the port for the API server in '~/.kube/config'
and if necessary use the '--server' flag to explicitly specify it

**Comment by hangyan** [comment]
close by #1297.
