### ISSUE TITLE
Wrong version number for NetworkPolicy with new k8s version

### ISSUE THREAD

**Issue by arslanabbasi** [kubernetes/kompose#1294]
Hi,

Kubernetes has changed the apiVersion of Network Policy to `apiVersion: networking.k8s.io/v1`. When kompose generates the NetworkPolicy files, it is still using the old api version `apiVersion: extensions/v1beta1` due to which creating the network policy fails with the following error 

`error: unable to recognize "selenium_hub-net-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"`

Please let me know if more clarification is required for this issue.

**Comment by hangyan** [comment]
Yes, due to our very old kubernetes dep code, this is not very correct output for now. I will try to fix this
