### ISSUE TITLE
support podman

### ISSUE THREAD

**Issue by heylix** [kubernetes/kompose#1296]
It would be cool if kompose could support podman, similar to what [containers/podman-compose](https://github.com/containers/podman-compose) does.

Is that possible?

**Comment by hangyan** [comment]
Since kompose has remove the `up` and `down` comand and only do `convert`, there is no need to add this support for now

**Comment by eoli3n** [comment]
I do have ``up`` and ``down``
```
~  
➜ kompose version                                                                                                                                                            22:32:13
1.21.0 (992df58d8)

~  
➜ kompose --help                                                                                                                                                             22:32:22
Kompose is a tool to help users who are familiar with docker-compose move to Kubernetes.

Usage:
  kompose [command]

Available Commands:
  completion  Output shell completion code
  convert     Convert a Docker Compose file
  down        Delete instantiated services/deployments from kubernetes
  help        Help about any command
  up          Deploy your Dockerized application to a container orchestrator.
  version     Print the version of Kompose

Flags:
      --error-on-warning    Treat any warning as an error
  -f, --file stringArray    Specify an alternative compose file
  -h, --help                help for kompose
      --provider string     Specify a provider. Kubernetes or OpenShift. (default "kubernetes")
      --suppress-warnings   Suppress all warnings
  -v, --verbose             verbose output

Use "kompose [command] --help" for more information about a command.
```
> An implementation of docker-compose with Podman backend. The main objective of this project is to be able to run docker-compose.yml unmodified and rootless.

So can you reconsider adding a default search for ``podman-compose.yml`` file in current dir when using kompose ?

**Comment by hangyan** [comment]
@eoli3n i'm looking into it.

**Comment by hangyan** [comment]
@eoli3n  Is `podman-compose.yml` some kind of standard? i can not find any ref to it

**Comment by eoli3n** [comment]
It seems that podman-compose chose ``container-compose.yml`` as strandard instead of ``podman-compose.yml``.
See https://github.com/containers/podman-compose/issues/167
