### ISSUE TITLE
✨ Kompose converts into Pod instead of Deployment

### ISSUE THREAD

**Issue by segersniels** [kubernetes/kompose#1301]
### Issue
In some cases Kompose converts certain `docker-compose.yml` files into `Pod` kinds instead of `Deployment` resulting in errors such as:

```
Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```

It would be helpful if we could enforce Kompose to convert using `kind: Deployment` instead of `kind: Pod` to prevent issues like this.

### Reproduce
An example `docker-compose.yml` file that doesn't work: https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml

**Comment by hangyan** [comment]
The `Pod` object is create by the use of `on-failure` restart policy. For now this is no cmd flags to overwrite this behaiour. But i think this sould be changed to allow the cmd flags(`controller`) to let the use choose the pod contorller, directly use Pod seems not a good idea.
