### ISSUE TITLE
docker-compose Version 3.4+ Support

### ISSUE THREAD

**Issue by jm241825** [kubernetes/kompose#1304]
I've just recently found your tool, and would like to utilize it, but an application that I need it for utilizes docker-compose version 3.4.  When do you think kompose will support version 3.4 (and higher)?

**Comment by hangyan** [comment]
It's do support 3.4-3.7 now

**Comment by jm241825** [comment]
Can you provide some more detailed installation steps for the tool?  I keep getting the following error when I try to use it:

`ERRO Could not parse config for project kompose2 : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `3` into config.RawService
FATA composeObject.Parse() failed, Failed to load compose file: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `3` into config.RawService`

When I check the version, it says the installed version is "0.7.0 (c25b7e8)".  I pulled the most recent release from GitHub, but it will not update or install the latest version.  I've tried from the terminal in VSCode and from Windows administrator shell.

**Comment by hangyan** [comment]
dup of #1309
