### ISSUE TITLE
kompose convert --volumes=configMap does not add binary data.

### ISSUE THREAD

**Issue by rpsperera** [kubernetes/kompose#1308]
Im trying to add a tar file on to the configMap but when i use the above mentioned I get the following error ,

error in marshalling the List: error converting JSON to YAML: yaml: control characters are not allowed.

**Comment by hangyan** [comment]
Can you provide a example compose yaml and other necessary files?

**Comment by DonPerera** [comment]
Please find the attached. And does kompose support generation of ingress files.

[configs.tar.zip](https://github.com/kubernetes/kompose/files/5040951/configs.tar.zip)

[docker-compose.txt](https://github.com/kubernetes/kompose/files/5040955/docker-compose.txt)

**Comment by hcho1989** [comment]
Ran into the very same issue.
Please reconsider implementing this feature as kubernetes already supports adding binary file as configMap since 1.10

**Comment by chris-peerman** [comment]
/remove-lifecycle rotten
I've also recently fallen fowl of this issue. I need a JKS (Java Key Store file) as a config map however I get the error "error converting JSON to YAML: yaml: control characters are not allowed"

**Comment by chris-peerman** [comment]
I've also had this issue. I need to include a known Java Key Store file (JKS) but I get the error "FATA error converting JSON to YAML: yaml: control characters are not allowed" when I icnlude them.

/remove-lifecycle rotten
/reopen

**Comment by hangyan** [comment]
@top  Can you take a look of this issue?

**Comment by hangyan** [comment]
close by #1418
