### ISSUE TITLE
How do you download this

### ISSUE THREAD

**Issue by jm241825** [kubernetes/kompose#1309]
No matter what installation method I try, it always installs version 0.7.0 (c25b7e8), even though I specify that I want version 1.21.0.  What do I need to do to get the latest version?  I'm trying to use this with VSCode, so do I need to install it from my Windows CMD tool?

**Comment by jing2uo** [comment]
maybe you have the kompose binary file of version 0.7.0 in the PATH and it has high priority, you can use ` where kompose ` in cmd to find it, then download the latest version from  [release page](https://github.com/kubernetes/kompose/releases/tag/v1.21.0) and replace the old version file. this tool: [everything](https://www.voidtools.com/zh-cn/downloads/) , also help.
