### ISSUE TITLE
problems converting docker-compose file using local environment variables

### ISSUE THREAD

**Issue by yelhouti** [kubernetes/kompose#1314]
I have the following error:

FATA Invalid interpolation format for "environment" option in services "kurento": "${NETWORK_INTERFACE:-}". You may need to escape any $ with another $.

When I try to convert compose files that local environment variables with default values like:

```
    environment: 
      KMS_NETWORK_INTERFACES: ${NETWORK_INTERFACE:-}
```
or
```
    environment: 
      EXTERNAL_IPv6: ${EXTERNAL_IPv6:-::1}
```

If possible, this should be intercepted IMO and these values stored in some values.yml to be used by helm or something like that.

**Comment by hangyan** [comment]
@yelhouti Can you try the latest v1.22 version, it should fix this problem. About the helm charts, this is a good idea, although it's hard to impl in the current code base, will keep an eye on it.
