### ISSUE TITLE
Need to update the api version in the auto-generated network policy

### ISSUE THREAD

**Issue by saehan-suh** [kubernetes/kompose#1318]
When using the `kompose` to convert a docker-compose file(I'm using the version 1.21), the generated network policy file has the following API version:

```
apiVersion: extensions/v1beta1
```

This API version is deprecated since the Kubernetes 1.15-16. Hence, it causes the error when applying the resulting network policy file to a K8s cluster; it causes the following error:

```
error: unable to recognize "foo-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"
```

It should be changed to:
```
apiVersion: networking.k8s.io/v1
```

I noticed this was a [closed issue](https://github.com/kubernetes/kompose/issues/1294), but the update is still not reflected in the latest version, e.g., 1.21.0.

**Comment by devniel** [comment]
Hello, I'm also getting the problem
```
➜  kompose git:(master) cat custom-network-networkpolicy.yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: custom-network
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/custom-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/custom-network: "true"
➜  kompose git:(master) ls
custom-network-networkpolicy.yaml  spots-api-deployment.yaml  spots-ui-deployment.yaml  spots-ui-service.yaml
➜  kompose git:(master) kubectl apply -f custom-network-networkpolicy.yaml
error: unable to recognize "custom-network-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"
```

Changing to `apiVersion: networking.k8s.io/v1` fixes the problem, thank you.

**Comment by hangyan** [comment]
@devniel @saehan-suh Can you try the latest 1.22 version. It should fixed this problem

**Comment by hangyan** [comment]
feel free to reopen this issue if v1.22 does not fix your issues
