### ISSUE TITLE
Build args not working

### ISSUE THREAD

**Issue by shivamSharmaMWP** [kubernetes/kompose#1319]
when build args are placed inside docker-compose.yaml,   docker-compose executable is able to build the docker images, but same command for kompose executable doesn't work.

**Comment by shivamSharmaMWP** [comment]
____ inside docker-compsoe
  simple_app:
    image: myImae:vv

    build:
      args:
        - APP_VERSION=app-0.5.2
      context: /home/abstract/app



______________ my docker file

ARG APP_VERSION
FROM respository/app:$APP_VERSION
RUN echo "print this $APP_VERSION"



this doesn't build at all. by kompose

**Comment by hangyan** [comment]
can you try the `--build` option?
