### ISSUE TITLE
Kompose up : no basic auth credentials

### ISSUE THREAD

**Issue by Chris92ch** [kubernetes/kompose#1322]
Hello ! 

I've pulled a compose file from a private repo and I would like to apply it on my K8s cluster. Sadly, everytime I try to `kompose up` , I'm receiving this output : 

`FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service core: Unable to build image. For more output, use -v or --verbose when converting.: Get https://xxx.xxx.io/v2/wildfly/wildfly-openj9/manifests/10.1.0: no basic auth credentials `

I used the docker login command before and the login was successful. Sadly, it doesn't seem that Kompose is using the infos that has been written in `/.docker/config.json`.

Did you ever experienced this ? 

Best regards
Chris.

**Comment by hangyan** [comment]
close by #1297 
release: 1.22
