### ISSUE TITLE
Related to #1271, volume mount on host not supported

### ISSUE THREAD

**Issue by mkbhanda** [kubernetes/kompose#1323]
Related to #1271 that was closed because of time rot
Here is a docker-compose file that I was trying to use with kompose on a single node kind cluster. PVCs stay pending
https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-redis-no-secty.yml
WARN Volume mount on the host "/var/run/docker.sock" isn't supported - ignoring path on the host

**Comment by hangyan** [comment]
kompose have a flag `volumes` when convert, do you think that will match your needs?
