### ISSUE TITLE
Tutorial, please add a line ...

### ISSUE THREAD

**Issue by guettli** [kubernetes/kompose#1325]
Please add something to the "getting started" tutorial:

https://kompose.io/getting-started/

```
....
Run kompose convert in the same directory as your docker-compose.yaml file.

$ kompose convert                           
INFO Kubernetes file "frontend-service.yaml" created         
INFO Kubernetes file "redis-master-service.yaml" created     
INFO Kubernetes file "redis-slave-service.yaml" created      
INFO Kubernetes file "frontend-deployment.yaml" created      
INFO Kubernetes file "redis-master-deployment.yaml" created  
INFO Kubernetes file "redis-slave-deployment.yaml" created 
```

Please add (for stupid new comers like me) what to do next. The files got created,
but how can I start them in minikube?

**Comment by hangyan** [comment]
The current doc has add the `Run kompose convert in the same directory as your docker-compose.yaml file.`. It that confused?

**Comment by hangyan** [comment]
The home page of https://kompose.io/ and `Getting Started` has docs about using ` kubectl apply -f ` to install these resources

**Comment by guettli** [comment]
ok.
