### ISSUE TITLE
Helm v3 conversion

### ISSUE THREAD

**Issue by SvenDowideit** [kubernetes/kompose#1328]
I _think_ the conversion code is outputting not-v3 - https://github.com/kubernetes/kompose/blob/a994d6bc04e907b6849cb996cb80d1bec2979b4d/pkg/transformer/kubernetes/k8sutils.go#L91

but I also can't find any documentation that tells the user what helm chart versions the conversion does

so maybe its a small documentation change?

**Comment by hangyan** [comment]
the chart version is compatible with helm3/helm2. Since it not use any particular features that are specified  to helm v2 or v3
