### ISSUE TITLE
"kubectl apply -f *.yaml" results in error: Unexpected args: [file1.yaml file2.yaml]

### ISSUE THREAD

**Issue by germanafro** [kubernetes/kompose#1346]
as portraied in https://kompose.io/

> $ wget https://raw.githubusercontent.com/kubernetes/kompose/master/examples/docker-compose-v3.yaml -O docker-compose.yaml
> 
> $ kompose convert
> 
> $ kubectl apply -f *.yaml
> 
> $ kubectl get po
> NAME                            READY     STATUS              RESTARTS   AGE
> frontend-591253677-5t038        1/1       Running             0          10s
> redis-master-2410703502-9hshf   1/1       Running             0          10s
> redis-slave-4049176185-hr1lr    1/1       Running             0          10s

I convert my docker-compose, which results in multiple .yaml files
I would expect apply to work with multiple yaml files but instead i get the output:

> error: Unexpected args: [file1.yaml file2.yaml ...]

**Comment by hangyan** [comment]
This is a litle confusing. The correct sytax for kubectl is `kubectl apply -f .`, it will look up in the target dir and read all the yaml files to apply

**Comment by germanafro** [comment]
> 
> 
> This is a litle confusing. The correct sytax for kubectl is `kubectl apply -f .`, it will look up in the target dir and read all the yaml files to apply

TY! That worked out just fine.
I guess the documentation needs to be updated on this one.
