### ISSUE TITLE
Windows Binaries for 1.22 not updated correctly

### ISSUE THREAD

**Issue by holzkeil** [kubernetes/kompose#1347]
Hi, it seems the windows binaries are not updated correctly and they are on 1.21.

The sha256 hash of kompose-windows-amd64.exe 1.22 and 1.21 is 0a01f3eb0cb810b61a4d7aaa5b59824e829f2e9042f061ff27f3c419822f08d3

See
https://github.com/kubernetes/kompose/releases/tag/v1.22.0
https://github.com/kubernetes/kompose/releases/tag/v1.21.0

the download confirms this.

**Comment by hangyan** [comment]
@cdrage

**Comment by Lerke** [comment]
I ran into this as well. As a workaround, running kompose in WSL works fine.

**Comment by dav1d8** [comment]
I ran into this as well. Could you please fix this issue?
