### ISSUE TITLE
GitHub Actions instead of Travis CI

### ISSUE THREAD

**Issue by namusyaka** [kubernetes/kompose#1352]
According to https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing, travis ci has changed their pricing model, and it affects on our development cycle.
In fact, some of tests are waiting for quite a while, it will lead our development cycle to be slow. 

Thus, could we plan to migrate the CI from Travis CI to something like GitHub Actions?

Any thoughts on this?

**Comment by hangyan** [comment]
Good idea. Travis ci is much slower now. If you are intrested, feel free to create a PR to address this.

**Comment by namusyaka** [comment]
Will do

**Comment by namusyaka** [comment]
Please keep opening this as there are a few remaining tasks for integrating with GitHub Actions.
