### ISSUE TITLE
convert access_key and secret key using kompose

### ISSUE THREAD

**Issue by raiz-manjur** [kubernetes/kompose#1358]
Hi 
i am unable to convert aws access_key or secret key from docker-compose.yml to kompose.yml in below format

version: '3.5'

services:
  admin:
    build:
      args:
        - DECRYPT_SECRETS_DRIVER=oss
    labels:
      - app_role=admin
    environment:
      - ACCESS_KEY_ID=jhkjshdfjkhkjkjhkYlkjshdfkj
      - ACCESS_KEY_SECRET=kjhsdflkjhlskjdfhlkjh

* docker-compose -f docker-compose.yml -f xyz/abc/docker-compose.dev.yml config > kompose.yaml
*  kompose -f kompose.yaml convert

**converting as below**
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app_role: admin
    kompose.cmd: kompose -f kompose.yaml convert
    kompose.image-pull-policy: Always
    kompose.image-pull-secret: docker-cloud-credentials
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    app_role: admin
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  strategy: {}
  template:
    metadata:
      annotations:
        app_role: admin
        kompose.cmd: kompose -f kompose.yaml convert
        kompose.image-pull-policy: Always
        kompose.image-pull-secret: docker-cloud-credentials
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: admin
    spec:
      containers:
      - env:
        - name: ACCESS_KEY_ID
          value: kjshfdljklkjshldfkjh

**want to achieve**
           env:
            - name: "ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: "ACCESS_KEY"
            - name: "SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: "SECRET_KEY"

or 

apiVersion: v1
kind: Secret
metadata:
  name: secret_key
data:
  ACCESS_KEY: jhsdkfjhlksjfhlkjshlfks
  SECRET_KEY: j,hslkdfjhlksjhfd

**Comment by OneCricketeer** [comment]
The variables are treated like any other environment variable. It shouldn't be kompose's responsibility to scan and detect which variables you're using in order to relocate them to k8s secrets
