### ISSUE TITLE
--build should not automatically push

### ISSUE THREAD

**Issue by mrvisser** [kubernetes/kompose#1363]
I'm concerned that the default configuration for `kompose` if you want kompose to build your images for you is to attempt to push company intellectual property to a public server.

Is it worth having a breaking change that defaults to not push?

Folks may be well-versed in contributing open source containers and have the configuration to deploy to dockerhub. Then they want to learn kubernetes and transfer their knowledge. They come across https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/ and see they can get their company's private docker repos running locally on kubernetes pretty easily. They follow the instructions and run `kompose convert --build local` just like in the docs to build locally and their intellectual property goes to a public server.

The kompose documentation says you can use --build to build and push your containers. But despite that I don't think anyone expects the default functionality of a "build" step is to push it to a public server.

Thankfully I don't have credentials to push to docker.io :)

**Comment by joebowbeer** [comment]
There is a `--push-image` boolean option, but it is `true` by default.

I would also like the default to be `false`.
