### ISSUE TITLE
Do you handle Dockerfile ?

### ISSUE THREAD

**Issue by BATTLEROYALXS** [kubernetes/kompose#1367]
Hello does Kompose handle dockerfile ? cause i'm forced to use an upload image to dockerhub instead of my dockerfile ?

Thanks for the library

**Comment by hangyan** [comment]
In the old versions, kompose tend to be fullly-featured. Recently we are fouing on the `convert`  command and trying to do it rigiht. But it stdill support build the dockerfile and push the docker image. This is the default beahaivor in the old times, and can be turned off by using '--push-image=false'

**Comment by BATTLEROYALXS** [comment]
Thank you very much for your explenation, i will try this this week end, again thank for you work and the librairy which i hope will continue to be developped.
