### ISSUE TITLE
Kompose doesn't handle volumes

### ISSUE THREAD

**Issue by samcov** [kubernetes/kompose#1368]
I was under the impression that Kompose would generate Persistent Volume Claims, but none appear to be created. Here is what I do., it's in the mariadb section that a volume is specified, but it comes back as null(see below). **Am I missing a flag in convert or something?**

**Convert cmd line**: kompose convert -o deploy/

**This docker-compose**:
version: '3.4'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"
  logging:
    build:
      context:  .
      dockerfile: LoggindDockerfile.sam
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8011:80"
    links:
      - app
  **mariadb**:
    image: mariadb:10.5
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: saroot
      MYSQL_DATABASE: app_db
      MYSQL_USER: samcov
      MYSQL_PASSWORD: cvi2000
    ports:
      - "6033:3306"
    expose:
      - "3306"
    volumes:
      - ./data/db:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "amcrabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=samcov
      - RABBITMQ_DEFAULT_PASS=mouser
    labels:
      NAME: "IvcEventBus"

**The output mariadb deployment yaml looks like this**:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\dapr\kompose.exe convert -o deploy/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\dapr\kompose.exe convert -o deploy/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - args:
        - --lower_case_table_names=1
        env:
        - name: MYSQL_DATABASE
          value: app_db
        - name: MYSQL_PASSWORD
          value: cvi2000
        - name: MYSQL_ROOT_PASSWORD
          value: saroot
        - name: MYSQL_USER
          value: samcov
        image: mariadb:10.5
        imagePullPolicy: ""
        name: mariadb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      **volumes**: null
status: {}

**Comment by hangyan** [comment]
Can you post a formated verion of the source yaml file?

**Comment by samcov** [comment]
Here it is, zip attached.
[docker-compose.zip](https://github.com/kubernetes/kompose/files/6121616/docker-compose.zip)

**Comment by aiyijing** [comment]
Error due to window Path. It seems that the same problem will happen when volumes=hostPath 

```bash
C:/abc/abc:
```
It will cause an error here
https://github.com/kubernetes/kompose/blob/94bff75a159497f00eab26782b4a87be0c954bb8/pkg/transformer/utils.go#L88-L111

**Comment by aiyijing** [comment]
It seem that there used kubernetes in docker desktop on windows.
Actually，the runtime run in wsl like Linux.
