### ISSUE TITLE
kompose convert permission denied ?

### ISSUE THREAD

**Issue by garyng2000** [kubernetes/kompose#1370]
Why would I see such error ? isn't it just some read then write operation ? 

note that docker-compose works

the only thing that may be odd is instead of one single docker-compose.yml file, it is splitted into multiple(one for environment variable, another the actual compose). The author(not me) then use a shell script to wrap them as multipe -f to docker-compose.

Is that the reason ?

**Comment by hangyan** [comment]
Can you post a screenshot of the error ?

**Comment by garyng2000** [comment]
found the problem it is snap, not about kompose. I tried snap install but  run it at non-home location. then removed it and do the good old download binary directly and it works fine. sorry for the trouble.
