### ISSUE TITLE
Change the default PVCRequestSize through command line argument / configuration file

### ISSUE THREAD

**Issue by remyleone** [kubernetes/kompose#1374]
At the moment all non-specified PVCs are created using 100Mi which is below the minimum size for block storage with some providers (eg Scaleway).

Could it be possible to have the feature to pass the default PVCRequestSize through the command line? This would allow having a handy default that could be raised to the minimal size required by a vendor.
I would like to avoid having to fill it in the docker-compose because locally some volume can get to very diverse size so leaving it unspecified in the docker-compose is handy.

**Comment by hangyan** [comment]
close by #1406
