### ISSUE TITLE
Introduction page : command does not work

### ISSUE THREAD

**Issue by dlucasd** [kubernetes/kompose#1381]
Hi,

There is a mistake in the introduction page, this command does not work :  
```sh
$ kubectl apply -f *.yaml
```

According to the [kubernetes documentation](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/), we can apply a list of files : 
```sh
$ kubectl apply -f file1.yaml -f file2.yaml
```

or a directory : 
```sh
$ kubectl apply -f my-dir
```

So I suggest you this modification : 
> ### It's as simple as 1-2-3
> 
> 1. [Use an example docker-compose.yaml file](https://raw.githubusercontent.com/kubernetes/kompose/master/examples/docker-compose-v3.yaml) or your own
> 2. Run `kompose convert`
> 3. Run `kubectl apply` and check your Kubernetes cluster for your newly deployed containers!
> 
> ```sh
> $ wget https://raw.githubusercontent.com/kubernetes/kompose/master/examples/docker-compose-v3.yaml -O docker-compose.yaml
> 
> $ kompose convert
> 
> $ kubectl apply -f .
> 
> $ kubectl get po
> NAME                            READY     STATUS              RESTARTS   AGE
> frontend-591253677-5t038        1/1       Running             0          10s
> redis-master-2410703502-9hshf   1/1       Running             0          10s
> redis-slave-4049176185-hr1lr    1/1       Running             0          10s
> ```

**Comment by hangyan** [comment]
Seems like starts with some kubectl version, it does not support this kind of usage any more. The docs should be updated.
