### ISSUE TITLE
Kompose github page have wrong urls in menu

### ISSUE THREAD

**Issue by krubenrc** [kubernetes/kompose#1383]
Hello, i detected that in the github page, the navigation menu have wrong urls.

Example, in the menu:

The link: "Getting Started" goes to https://kompose.io/getting-started/ but it returns 404, the correct url is https://kompose.io/docs/getting-started.html

And the same error for the all links:
|link|actual url|correct url|
|---|---|---|
Installation | https://kompose.io/installation/ | https://kompose.io/docs/installation.html
User Guide | https://kompose.io/user-guide/ | https://kompose.io/docs/user-guide.html
Conversion Matrix | https://kompose.io/conversion/ | https://kompose.io/docs/conversion.html
Architecture | https://kompose.io/architecture/ | https://kompose.io/docs/architecture.html
Integrations | https://kompose.io/integrations/ | https://kompose.io/docs/integrations.html

Regards.

**Comment by awehrung** [comment]
All the links you posted under the "correct url" column return 404 for me, and all the links under "actual url" return the expected page. Maybe this problem has been fixed already?

Best regards

**Comment by krubenrc** [comment]
Yes, it seems they already fixed the urls.
Close the issue.

Regards.
