### ISSUE TITLE
'Support for readinessProbe' is not include Kompose 1.22.0

### ISSUE THREAD

**Issue by james-song** [kubernetes/kompose#1384]
I saw `Support for readinessProbe #1262` in https://github.com/kubernetes/kompose/blob/master/CHANGELOG.md

but i think is not include

release hash 955b7812425d15207fc23f396591f21c98a377b3

support readinessProve commit is 0036f0c32b37d0a521421b76e58b580b7574c127

it's really confused kompose versions

could you have a next release plan ?

**Comment by raphaelauv** [comment]
1.23.0 is out https://github.com/kubernetes/kompose/releases/tag/v1.23.0
