### ISSUE TITLE
--build that requires private registry does not authenticate

### ISSUE THREAD

**Issue by abrobston** [kubernetes/kompose#1387]
In kompose version 1.22.0 on MacOS, using `kompose convert --build local` seems to fail when a relevant `Dockerfile` needs to pull an image from a private registry requiring authentication.  For example:

```
% kompose convert --build local --out k8s --push-image=false --verbose
DEBU Checking validation of provider: kubernetes
DEBU Checking validation of controller:
DEBU Docker Compose version: 3.0
[skipping a lot of lines...]
INFO Build key detected. Attempting to build image 'my-service'
DEBU Build image working dir is: /Users/andrew/some-dir
DEBU Build image context is: /Users/andrew/some-dir/docker/services/my-service
INFO Building image 'my-service' from directory 'my-service'
DEBU Created temporary file /var/folders/gh/t_0dmtqs1l78q_28ny_1wl7w0000gn/T/kompose-image-build-241078629 for Docker image tarballing
DEBU Image my-service build output:
Step 1/4 : ARG BASE_IMAGE_TAG=latest
Step 2/4 : FROM ############.dkr.ecr.us-east-1.amazonaws.com/my-base-image:$BASE_IMAGE_TAG
FATA Unable to build Docker image for service my-service: Unable to build image. For more output, use -v or --verbose when converting.: Head https://############.dkr.ecr.us-east-1.amazonaws.com/v2/my-base-image/manifests/latest: no basic auth credentials
```

I have credentials stored via `kubectl create secret docker-registry`, and I have labels in `docker-compose.yml` including `kompose.image-pull-secret` with the name of the relevant secret.  It appears to me that authenticated access to public Dockerhub happens to work, but for ECR, the credentials aren't being passed in any way in: https://github.com/kubernetes/kompose/blob/0b331d9e5dede975d62ca382b2dd7dff89019f6e/pkg/utils/docker/build.go#L66-L72  The Docker client in Go appears to expect `Auth` and/or `AuthConfigs` options in https://github.com/fsouza/go-dockerclient/blob/9446432cf94d2409b4d4dc452c5ab042ffea1c83/image.go#L531.

What I would expect to happen is _some_ way of authenticating to ECR.  Maybe I'm missing some method, but from looking at the Docker client code, I'm not seeing it.

**Comment by hangyan** [comment]
The image pull secret label is used for k8s speficfic using, check the doc at: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod. Sadlly it has noting to do with the docker build function. Have you tried docker login the private registry first and then do the kompose convert step?

**Comment by abrobston** [comment]
Yes, I tried logging into the private repository (ECR) from the shell where I ran the command.  That worked for `docker pull`, but not for `kompose convert`.
