### ISSUE TITLE
docker-compose 3.8

### ISSUE THREAD

**Issue by maxkraft7** [kubernetes/kompose#1396]
I want to switch to kubernetes and this tool seems perfect for it. However: I'm using version 3.8 of docker-compose. Which is not yet covered by kompose. Is there a plan an when it will be able to convert it?

**Comment by tk42** [comment]
@maxkraft7
I think you can convert docker-compose v3.8 format by compiling from HEAD of master branch. (v3.8 is supported from #1334 on 31 Oct 2020 but few days earlier the current version v1.22.0 was tagged.)

**Comment by hangyan** [comment]
See the latest releases.
