### ISSUE TITLE
how to add labels to services

### ISSUE THREAD

**Issue by ucarbehlul** [kubernetes/kompose#1397]
Labels entries under service adds annotations to a service and it is not clear from documentation how to add labels to a service.

**Comment by kferrone** [comment]
Why do the labels in docker compose translate to annotations in kubernetes instead of translating to labels? I find this quite weird as well.

**Comment by hangyan** [comment]
yeah it's a little weird...

**Comment by hangyan** [comment]
Maybe a cmd flags can help this, let the user choose which one
