### ISSUE TITLE
determine which containers should be in the same pod

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/kompose#14]
e.g., the ones share the same volume should be in the same pod; the ones link to each other may or may not be in the same pod

**Comment by ngtuna** [comment]
Ref: https://github.com/redhat-developer/henge/blob/master/pkg/transformers/kubernetes/generate.go#L142

**Comment by surajssd** [comment]
Will be working on this one!

**Comment by ngtuna** [comment]
@surajssd feel free to update `priority/P1` label if you are working on it now. That would be great to have it implemented in the next release.

**Comment by surajssd** [comment]
#131 right now only addresses `volumes_from` directive!

**Comment by ngtuna** [comment]
Should we close this ?

**Comment by surajssd** [comment]
@ngtuna we have not implemented it yet so lets keep it.

**Comment by kadel** [comment]
Do we know about another case which would resolve in putting two containers to the same pod?

**Comment by surajssd** [comment]
we should not do anything that deviates from the base docker-compose file format so let's not do this one!

**Comment by cdrage** [comment]
@surajssd agreed, let's close
