### ISSUE TITLE
Completion Support for `fish`

### ISSUE THREAD

**Issue by HerrNaN** [kubernetes/kompose#1403]
Hi!
I would like to have completions support for the shell `fish`. As far as I  can tell `cobra` already has support for generating completions for `fish` (`cmd.Root().GenFishCompletion(w io.Writer, includeDesc bool)`) in a similar way as it's currently generated for `bash`.

Is this something you would like to have included in the project? Why/Why not?

**Comment by hangyan** [comment]
Sounds a good idea. Will try.

**Comment by top** [comment]
https://github.com/kubernetes/kompose/pull/1407

**Comment by top** [comment]
https://github.com/kubernetes/kompose/pull/1412

It's now supported.

**Comment by hangyan** [comment]
close by #1412. Thanks @top
