### ISSUE TITLE
compatability issue with 64-bit version of windows

### ISSUE THREAD

**Issue by kish0620** [kubernetes/kompose#1415]
I just downloaded kompose, but when I try to run it I get an error saying it's not compatibility with the 64 bit version of windows. I've tried running this in compatibility mode as well, but this didn't solve the issue. Does anyone know how to fix this?

**Comment by hangyan** [comment]
I will working on this to find out what wrong

**Comment by hangyan** [comment]
@kish0620 Which version of kompose do you use?

**Comment by hangyan** [comment]
I just try the v1.23 of kompose file and it works fine.

**Comment by kish0620** [comment]
I ran go get -u github.com/kubernetes/kompose

**Comment by kish0620** [comment]
Actually it was this one: curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-windows-amd64.exe -o kompose.exe

**Comment by hangyan** [comment]
@kish0620 Will check on that release. You can use v1.23 first.

**Comment by kish0620** [comment]
After running that curl command, I run kompose in my terminal but that's when I get the error message. Is that the correct way to run the program?

**Comment by hangyan** [comment]
Manully update v1.23 and v1.24's windows release, you can get it on choco now, or download it directly. Feel fee to reopen it if you encounterd other problems
