### ISSUE TITLE
Support the platform of darwin/arm64？

### ISSUE THREAD

**Issue by aiyijing** [kubernetes/kompose#1416]
Have any plan to support the platform of darwin/arm64？
Although the arm mac has  rosetta，but the performance is not well。

**Comment by sbs2001** [comment]
@aiyijing  I think this should be pretty straightforward to do. Could you try building kompose as mentioned at https://github.com/kubernetes/kompose#development-and-building-of-kompose ,  while using go 1.16+ .  

I managed to cross compile `kompose` for darwin/arm64 without any issue from my linux laptop, but have no access to m1 machine. Let us know here how it goes :)

**Comment by hangyan** [comment]
close by #1455
