### ISSUE TITLE
Missing exe extension for windows release

### ISSUE THREAD

**Issue by majkinetor** [kubernetes/kompose#1433]
This started to happen from v1.23. 

This is the reason latest version is not on choco. Here is the relevant part of [bot report](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors)

```
Can't validate URL
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.":https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-windows-amd64.exe
```

**Comment by hangyan** [comment]
Thanks ,will fix this.

**Comment by hangyan** [comment]
I have manually update v1.24.0's windows file. If choco can fetch this version correctly, will update v1.23.0 later.

**Comment by hangyan** [comment]
Fixed. See https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors
