### ISSUE TITLE
Investigate how to use HCL/Nomad as input object

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kompose#144]
In Nomad you define a containerized apps as a Job  in HCL:

https://www.nomadproject.io/docs/jobspec/index.html

we technically could convert from HCL jobs into deployments/services.

**Comment by ngtuna** [comment]
I would like to take this one.

**Comment by bgrant0607** [comment]
If you're going to branch out from Compose format, you may want to join forces with https://github.com/micahhausler/container-transform

**Comment by cdrage** [comment]
Honestly, considering that this tool is now in the Kubernetes org as well as been clearly defined with Kubernetes / OpenShift usage, I say that we close this issue for now. When the need arises (Nomad hasn't reached *that* large of user acquisition yet) we could possibly split this into a different tool / add new features.
