### ISSUE TITLE
Failed to convert docker-compose with profiles

### ISSUE THREAD

**Issue by Roman-Bober** [kubernetes/kompose#1458]
Hi,
Please see below error , when I add profiles to my docker compose file
The docker-compose file is attached
Please help
[docker-compose.txt](https://github.com/kubernetes/kompose/files/7506270/docker-compose.txt)

Roman
```
c:\work\github\kafka>kompose.exe  -f docker-compose.yaml convert
FATA services.rest-proxy Additional property profiles is not allowed
```

version
```
c:\work\github\kafka>kompose.exe version
1.24.0 (7c629530)
```

**Comment by hangyan** [comment]
Looking into this

**Comment by hangyan** [comment]
related to #1448
