### ISSUE TITLE
Account takeover of linked example

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kompose#1462]
https://github.com/kubernetes/kompose/blob/master/docs/maven-example.md links to a non-existent account, which was identified by a security researcher and reported to us through the Kubernetes bug bounty program. Please fix the reference:

````
__1. Clone the example project from GitHub__
```bash
$ git clone https://github.com/piyush1594/kompose-maven-example.git
```
````

**Comment by hangyan** [comment]
Sure

**Comment by tallclair** [comment]
/remove-lifecycle stale

This is still an issue.

**Comment by tallclair** [comment]
If you can find the original project, https://github.com/piyush1594/kompose-maven-example.git, it should be moved to the examples directory in this repo, and the documentation should be updated to use that code.
