### ISSUE TITLE
Add support for compose.yml/compose.yaml

### ISSUE THREAD

**Issue by sebdanielsson** [kubernetes/kompose#1463]
Kompose should support compose.yml/compose.yaml in addition to the currently supported docker-compose files.

https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file

**Comment by sergeyshevch** [comment]
@SebDanielsson I guess it will be done in https://github.com/kubernetes/kompose/pull/1440. I'm trying to finish it in my free time. But there is still many work
