### ISSUE TITLE
Allow conversion of compose files where version is omitted

### ISSUE THREAD

**Issue by SebDanielsson** [kubernetes/kompose#1464]
I was unable to convert my compose files. After some investigation it seems like the problem was that I didn't specify version: on top of the file. According to the compose-spec the version property is deprecated.
https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element

**Comment by cdrage** [comment]
Oooofff, i don't like how Compose removed that. Was a good way to determine what we could or couldn't convert.

For now, please add: `version: 3.3` to the top of your `docker-compose.yaml` until we're able to fix this. 

Kompose should by default try to convert as much as it can / warn the user with what it can't.

**Comment by fhennig** [comment]
I also just ran into this, and kompose gave me no good errors that the version was missing. Maybe that could be something to implement?
