### ISSUE TITLE
Cannot pull image

### ISSUE THREAD

**Issue by ScottLinnn** [kubernetes/kompose#1510]
I convert a `docker-compose.yaml` into a single file and tried to run it by using `kubectl apply -f my-kompose.yaml`. However, most of my services failed to run. The error message displayed in minukube dashboard is:  
`Failed to pull image "my-service": rpc error: code = Unknown desc = Error response from daemon: pull access denied for my-service, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`  
I have tried `docker login` before conversion, but this error persists. Are there any possible ways to fix this?  
Thanks!!

**Comment by AhmedGrati** [comment]
Hey @ScottLinnn, Could you please provide us with the docker-compose file, so that we can help you with this issue? 🎉

**Comment by ScottLinnn** [comment]
It's solved. Thanks

**Comment by JamesCalleja** [comment]
how did you solve it ScottLinnn? It would be a big help  

thanks
