### ISSUE TITLE
port mapping issue

### ISSUE THREAD

**Issue by ResmiArjun** [kubernetes/kompose#1514]
Kompose v1.26.1

The conversion of port mapping from docker-compose to manifest not working correctly for larger port numbers.
For example the docker-compose file

version: '3'
services:
  sample:
    image: test1:latest
    container_name: test1
    restart: "none"
    environment:
      URL: http://test:8080
    ports:
      - '55564:55564'
      - '55563:55563'
    volumes:
      - /target:/target

is converted to 

      name: test1
      ports:
      - containerPort: 55564
       resources: {}

in the deployment part which seems to be missing port 55563. But the service part has both the ports as shown below.

       ports:
       - name: '55564'
        port: 55564
        targetPort: 55564
        - name: '55563'
        port: 55563
        targetPort: 55563

Tried with several combinations but mostly it is missing ports when the port numbers are larger than 10000. Is there any restrictions on the port numbers that can be used with Kompose.

**Comment by cdrage** [comment]
Fixed via https://github.com/kubernetes/kompose/pull/1515
