### ISSUE TITLE
FATA (root) Additional property name is not allowed

### ISSUE THREAD

**Issue by ypadlyak** [kubernetes/kompose#1518]
getting:
FATA (root) Additional property name is not allowed

for the following compose file:
version: '3.8'

name: t***o**
services:
  m****:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file:
      - .env  
    environment:
      - MIX_ENV=dev
      # - SECRET_KEY_BASE=********
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
    networks:
      - back-tier

  db:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db-data: {}

networks:
  front-tier: {}
  back-tier: {}  %

**Comment by mrangjunboon2017s** [comment]
thanks.

from mrangjunboon2017

**Comment by cdrage** [comment]
Can you post the gist of the YAML file? Hard to diagnose with your current yaml @ypadlyak
