### ISSUE TITLE
Cannot install kompose via Go because of one or more replace directives

### ISSUE THREAD

**Issue by valaparthvi** [kubernetes/kompose#1522]
It is not possible to install kompose via `go install` because of multiple replace directives.

```sh
$ go version
go version go1.19.1 linux/amd64

$ go install github.com/kubernetes/kompose@latest
go: github.com/kubernetes/kompose@latest (in github.com/kubernetes/kompose@v1.26.1):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

This is a known issue(https://github.com/golang/go/issues/44840) with Go, but I am opening this issue if there is a possibility to replace the replace directives.

**Comment by sivchari** [comment]
I'm also having trouble with the same error.

**Comment by fleadope** [comment]
Me too!

**Comment by cdrage** [comment]
Didn't we fix this @AhmedGrati or am I remembering this wrong 🤣

**Comment by AhmedGrati** [comment]
@cdrage isn't this issue fixed by [this PR](https://github.com/kubernetes/kompose/pull/1552)?

**Comment by cdrage** [comment]
Yeah, this is fixed now! Closing
