### ISSUE TITLE
Kompose doesn't work with 3.9

### ISSUE THREAD

**Issue by marouamghar** [kubernetes/kompose#1523]
It used to, but doesn't anymore. It logs :
FATA version 3.9 of Docker Compose is not supported. Please use version 1, 2 or 3

**Comment by cdrage** [comment]
Yeah, this is a known issue and we'll have to update our matrix here: https://kompose.io/conversion/ for it. As of right now we only support up to 3.3 which is quite an old version of compose.

**Comment by mrsangjunboon2018** [comment]
u lier.
