### ISSUE TITLE
can this helm install  this  yaml

### ISSUE THREAD

**Issue by summer-father** [kubernetes/kompose#1542]
can this helm install  this  yaml

**Comment by AhmedGrati** [comment]
Hello @summer-father, can you please share with us the YAML file?

**Comment by summer-father** [comment]
this  is a  idea,  no  yaml  yet

2022年12月1日 16:53，AhmedGrati ***@***.***> 写道：



Hello @summer-father<https://github.com/summer-father>, can you please share with us the YAML file?

**Comment by OneCricketeer** [comment]
This repo doesn't generate Helm related files.

Helm can deploy plain resource files (AKA template files with no templating), sure, but there's no real point vs `kubectl apply`

**Comment by summer-father** [comment]
This component will be more convenient to integrate in Portainer and Kubernetes dashbord

2022年12月1日 23:27，Jordan Moore ***@***.***> 写道：



This repo doesn't generate Helm related files.

Helm can deploy plain resource files (AKA template files with no templating), sure, but there's no real point vs kubectl apply

**Comment by OneCricketeer** [comment]
What component?

**Comment by summer-father** [comment]
kompose

2022年12月2日 02:39，Jordan Moore ***@***.***> 写道：



What component?

**Comment by OneCricketeer** [comment]
If you'd like to see kompose added to those tools, feel free to open issues / feature requests in those repos instead.

**Comment by summer-father** [comment]
OK,tahnk  you,i  hope

2022年12月2日 21:04，Jordan Moore ***@***.***> 写道：

If you'd like to see kompose added to those tools, feel free to open issues / feature requests in those repos instead.

**Comment by OneCricketeer** [comment]
Refer https://github.com/portainer/portainer/issues/7514
