### ISSUE TITLE
Possibility to add externalTrafficPolicy property to the generated service

### ISSUE THREAD

**Issue by ZakariaNaaija** [kubernetes/kompose#1543]
To solve the issue stated [here](https://github.com/docker/roadmap/issues/157), I figured out I can add externalTrafficPolicy: Local to the nginx service so that the client ip is preserved as stated [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip). How can we mention that while using Kompose to convert docker compose file?
Thank you!

**Comment by AhmedGrati** [comment]
I think that now, according to the docs, we are not currently supporting that, but I think we could implement it using some custom labels, as we did for the `Ingress` resource.

**Comment by ZakariaNaaija** [comment]
Would be nice to add a custom label to add properties to the spec's service. Like kompose.service.spec.{property} = { value }

**Comment by AhmedGrati** [comment]
Closed as resolved by #1544.
