### ISSUE TITLE
Update default branch name 

### ISSUE THREAD

**Issue by bcdady** [kubernetes/kompose#1554]
I see this project is still using 'master' as the default branch name.

See [github/renaming](https://github.com/github/renaming)

I'd be happy to push a new branch with updates such as `s/master/main/g`, but a maintainer would need to update the project settings.

**Comment by kundan2707** [comment]
@bcdady  agree with you as branch should be as per guideline in every repo

**Comment by cdrage** [comment]
@bcdady @kundan2707 done! renamed to main.

@AhmedGrati @Lctrs @hangyan FYI! hopefully it doesn't break anything.

**Comment by kundan2707** [comment]
@cdrage  Thank you
