### ISSUE TITLE
Epic: Go from Docker inspect configuration file to Docker Compose to Kubernetes

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1570]
Not many tools out there do this.

Would be awesome to go from a `docker inspect` configuration, straight to Kubernetes..

Example:

kompose convert | docker inspect redis minio wordpress 

Or something like that and it'll convert it it to docker-compose and then to Kubernetes.

I'm going to research some libraries / tools to try and get us there...

First step is to take https://github.com/Red5d/docker-autocompose and convert it to a golang file.

**Comment by cdrage** [comment]
Limited research so far brought me to this script: https://github.com/Red5d/docker-autocompose which can extract a docker-compose config from already running containers... but nothing from the actual "docker run" file.

**Comment by AhmedGrati** [comment]
@cdrage I suggest doing it directly without the `docker inspect ....`. e.g: `kompose convert -c redis`. wdyt?

**Comment by cdrage** [comment]
That'd be awesome! Although we'd have to make sure whatever library we use is up to date. As we've had issues in the past with the Kubernetes library constantly changing lol. 

PS. I'll review your other PR this upcoming week, been side tracked by work lately.

**Comment by AhmedGrati** [comment]
I think that I won't rely on any library. Instead, I'll try to implement it by myself, as I don't see any tool that can help us, maybe I'm missing something. LMK If you find something useful.
