### ISSUE TITLE
enhancement: integrate netlify deployment in our CI pipelines

### ISSUE THREAD

**Issue by AhmedGrati** [kubernetes/kompose#1571]
**What would you like to be added?**

Integrating the netlify deployment in our CI pipelines so that we can easily review changes made on markdown files, without any need to run that manually. It will facilitate the review process for maintainers and approvers.

**Comment by AhmedGrati** [comment]
@cdrage I think this is important to move forward on the documentation issues. Would you happen to have an idea about the organizational process on how to set up Netlify for this project?

**Comment by cdrage** [comment]
@AhmedGrati no idea unfortunatley, but I can research it as I've had coworkers do it before on other projects. would be helpful with regards to previewing the site before meriging in changes.
