### ISSUE TITLE
New logo for Kompose

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1573]
With the help of Midjourney and many variations / edits in Gimp I made a new logo for Kompose.

Other projects use their own logo, and were one of the only ones still using the Kubernetes placeholder.

What do you guys think? @AhmedGrati @hangyan ?

I decided to use an "Octopus" since it has many arms which kinda shows how we convert to Kubernetes.

I've kept the Septagon in the background as well as incorporated the same-blue-ish as Kubernetes projects.

![logo](https://user-images.githubusercontent.com/6422176/217543409-453d57d7-6961-4f47-9608-a50d072545ac.png)

**Comment by AhmedGrati** [comment]
I really like it, it's awesome 🤩

**Comment by cdrage** [comment]
Closed via #1574
