### ISSUE TITLE
Design diagram document is not visible in architecture.md

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/kompose#1622]
### Expected Behavior

Design diagram image is not visible in https://github.com/kubernetes/kompose/blob/main/docs/architecture.md

### Actual Behavior

Diagram not visible

### Kompose Version

```Text
1.28
```

**Comment by kundan2707** [comment]
changes path in design document link as default branch in repo is main

**Comment by AhmedGrati** [comment]
Thank you @kundan2707 for reporting this, but it's a duplicate of #1600.

**Comment by kundan2707** [comment]
Closing as it dublicate of #1599
