### ISSUE TITLE
Add health checks

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#163]
Automatically generate readiness and liveliness probes!

**Comment by kadel** [comment]
This would be nice. But user will have to provide additional information for kompose, there is no health check information in docker-compose :-(

**Comment by ngtuna** [comment]
Any chance for kompose label ?

**Comment by kadel** [comment]
> Any chance for kompose label ?

Yes, labels are probably only option here.

**Comment by surajssd** [comment]
We can use `docker-compose` construct `depends_on` along with labels to define health checks.

**Comment by containscafeine** [comment]
We have [heathcheck](https://docs.docker.com/compose/compose-file/#/healthcheck) in docker compose v2.1, should I go ahead and pick this up?

**Comment by cdrage** [comment]
@containscafeine Should be easily mapped, we have https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ available for us which (mostly) maps 1-1 to what compose has.

**Comment by surajssd** [comment]
@containscafeine I think this is possible if `libcompose` have added support for it? Isn't it?

**Comment by containscafeine** [comment]
@cdrage @surajssd yep, if libcompose has support for this, this can be mapped directly. I didn't try this out yet.

**Comment by kadel** [comment]
problem is that libcompose is not yet supporting 2.1

**Comment by surajnarwade** [comment]
@kadel , @surajssd can you please add label `compose v2.1` here ?

**Comment by surajssd** [comment]
@surajnarwade libcompose supports this?

**Comment by kadel** [comment]
https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck

**Comment by surajssd** [comment]
@kadel my question was more in respect of libcompose because it is the upstream for us and if they have added support for it then we can go forward with supporting this one as well

**Comment by kadel** [comment]
ah, I don't know if libcompose supports that. 

But we could add healthchecks for v3, we don't use libcompose for that.

**Comment by surajnarwade** [comment]
@kadel @surajssd libcompose don't support health checks

**Comment by cdrage** [comment]
However, `docker/cli` supports it as well as using the `healthcheck` key in Version 3.

**Comment by surajnarwade** [comment]
@cdrage , are you working on this issue ?

**Comment by cdrage** [comment]
@surajnarwade Yes

**Comment by cdrage** [comment]
There is work on this at #759

**Comment by cdrage** [comment]
#759 has been merged! Closing.
