### ISSUE TITLE
[Feature]: Support HPA configuration

### ISSUE THREAD

**Issue by AhmedGrati** [kubernetes/kompose#1631]
### What would you like to be added?

I would like to introduce scalability features, by working on the basic version of the HPA, `minReplicas`, `maxReplicas`, `cpu`, and `memory` metrics.

### Why is this needed?

Make users' life easier when it comes to deploying production-ready applications, using the scalability features.

**Comment by AhmedGrati** [comment]
@hangyan @cdrage your input is really valuable.

**Comment by cdrage** [comment]
@AhmedGrati I 100% agree on adding this, but is there the Compose equivalent in the spec for this? Or should we throw all of this into labels (like we already do?).

Or even the CLI?

I'm curious what you're thinking

**Comment by AhmedGrati** [comment]
I'm thinking about labels to customize the HPA configuration at the container level, which offers more customization and flexibility. Do you have other suggestions?

**Comment by cdrage** [comment]
I was thinking labels too.. As we cannot use `deploy` section from compose really since it's meant for cloud-based deployment.. The best way would probably just to use labels as we already are able to configure replica size, etc.
