### ISSUE TITLE
Specify a namespace with convert?

### ISSUE THREAD

**Issue by ryannix123** [kubernetes/kompose#1657]
### What would you like to be added?

Hello,

I'm writing up some documentation on how to use Konvert with the OpenShift Developer Sandbox. However, when I convert my docker-compose file then run `oc apply -f`, I get a bunch of errors around the Deployment Config and a missing namespace.

Is there anyway to fix this during the `convert` process?

```
oc apply -f ocp/
persistentvolumeclaim/databasevolume created
persistentvolumeclaim/logvolume01 created
service/openemr configured
persistentvolumeclaim/sitevolume created
resource mapping not found for name: "mysql" namespace: "" from "ocp/mysql-deploymentconfig.yaml": no matches for kind "DeploymentConfig" in version "v1"
ensure CRDs are installed first
resource mapping not found for name: "mysql" namespace: "" from "ocp/mysql-imagestream.yaml": no matches for kind "ImageStream" in version "v1"
ensure CRDs are installed first
resource mapping not found for name: "openemr" namespace: "" from "ocp/openemr-deploymentconfig.yaml": no matches for kind "DeploymentConfig" in version "v1"
ensure CRDs are installed first
resource mapping not found for name: "openemr" namespace: "" from "ocp/openemr-imagestream.yaml": no matches for kind "ImageStream" in version "v1"
ensure CRDs are installed first
```

### Why is this needed?

We want to make this as easy possible for those convert docker-compose files to a Kubernetes namespace/OpenShift project.

**Comment by AhmedGrati** [comment]
@ryannix123 Just to confirm my thoughts you want to have something like this
```bash
kompose convert -f docker-compose.yaml -n app
```
and then a namespace app would be generated?

**Comment by ryannix123** [comment]
Wow, that was quick. Thanks, @AhmedGrati!
