### ISSUE TITLE
[BUG] hostPort defined on container ports from "expose"

### ISSUE THREAD

**Issue by albanm** [kubernetes/kompose#1691]
### Expected Behavior

The [expose keyword's documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#expose) is pretty clear: "Expose ports without publishing them to the host machine".

A port defined in expose should be declared as simple container port, a service should be created to allow access by others pods, but it should not be bound to the host.

### Actual Behavior

The container port is created with "hostPort".

### Steps To Reproduce

1. create docker-compose with a service with `expose:  - "8080"`
2. use kompose convert
3. check the deployment, it contains hostPort

### Kompose Version

```Text
1.30.0 (9d8dcb518)
```

### Docker-Compose file

```YAML
version: '3'
services:
  test:
    image: test/test
    expose:
      - "8080"
```

**Comment by serverwentdown** [comment]
Caused by the introduction of `hostPort` support in #1558. The code will always set `hostPort` to the port provided.

**Comment by riain0** [comment]
Hi @AhmedGrati / @cdrage - when do you think this fix will be released, currently I need to do a work around to fix this, thanks!

**Comment by cdrage** [comment]
Hi @riain0 I'll get a fix out Friday :) 

You can always compile the repo by using `make bin` for now until the release
