### ISSUE TITLE
[BUG] v1.31.0 build failed

### ISSUE THREAD

**Issue by SergeyDjam** [kubernetes/kompose#1715]
### Expected Behavior

make build exit 0

### Actual Behavior

`go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
pkg/kobject/kobject.go:25:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
pkg/transformer/kubernetes/kubernetes.go:39:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
pkg/transformer/openshift/openshift.go:29:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
pkg/transformer/openshift/openshift.go:30:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
make: *** [Makefile:42: bin] Error 1
`

### Steps To Reproduce

+ /bin/gzip -dc /home/builder/rpmbuild/SOURCES/kompose-1.31.0.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd kompose-1.31.0
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.58090
+ umask 022
+ cd /home/builder/rpmbuild/BUILD
+ cd kompose-1.31.0
+ '[' 1 -eq 1 ']'
+ '[' 1 -eq 1 ']'
+ export GOPROXY=direct
+ GOPROXY=direct
+ /usr/bin/make -j8
fatal: not a git repository (or any parent up to mount point /home/builder)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CGO_ENABLED=0 GO111MODULE=on go build  -ldflags="-w -s -X github.com/kubernetes/kompose/pkg/version.GITCOMMIT=" -o kompose main.go
go: downloading github.com/compose-spec/compose-go v1.19.0
go: downloading k8s.io/apimachinery v0.28.2
go: downloading github.com/openshift/api v3.9.0+incompatible
go: downloading k8s.io/api v0.28.2
go: downloading github.com/fsouza/go-dockerclient v1.9.7
go: downloading github.com/deckarep/golang-set v1.8.0
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/mattn/go-shellwords v1.0.12
go: downloading golang.org/x/tools v0.13.0
go: downloading github.com/novln/docker-parser v1.0.0
go: downloading k8s.io/klog/v2 v2.100.1
go: downloading github.com/distribution/reference v0.5.0
go: downloading github.com/docker/docker v23.0.3+incompatible
go: downloading golang.org/x/exp v0.0.0-20230713183714-613f0c0eb8a1
go: downloading github.com/imdario/mergo v0.3.16
go: downloading github.com/klauspost/compress v1.11.13
go: downloading github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
pkg/kobject/kobject.go:25:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
pkg/transformer/kubernetes/kubernetes.go:39:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
pkg/transformer/openshift/openshift.go:29:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
pkg/transformer/openshift/openshift.go:30:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
make: *** [Makefile:42: bin] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.58090 (%build)

### Kompose Version

```Text
1.31.0
```

**Comment by mshedsilegx** [comment]
It is still happening in release 1.31.2

```
--- go.mod.dist 2023-10-12 07:54:11.000000001 -0500
+++ go.mod      2023-11-03 13:10:03.667396038 -0500
@@ -12,7 +12,7 @@
        github.com/joho/godotenv v1.5.1
        github.com/mattn/go-shellwords v1.0.12
        github.com/novln/docker-parser v1.0.0
-       github.com/openshift/api v3.9.0+incompatible
+       github.com/openshift/api v0.0.0-20200117162508-e7ccdda6ba67
        github.com/pkg/errors v0.9.1
        github.com/sirupsen/logrus v1.9.3
        github.com/spf13/cast v1.5.1
--- go.sum.dist 2023-10-12 07:54:11.000000001 -0500
+++ go.sum      2023-11-03 13:10:36.418398026 -0500
@@ -224,8 +224,8 @@
 github.com/opencontainers/runc v1.1.5/go.mod h1:1J5XiS+vdZ3wCyZybsuxXZWGrgSr8fFJHLXuG2PsnNg=
 github.com/opencontainers/runtime-spec v1.0.3-0.20210326190908-1c3f411f0417/go.mod h1:jwyrGlmzljRJv/Fgzds9SsS/C5hL+LL3ko9hs6T5lQ0=
 github.com/opencontainers/selinux v1.10.0/go.mod h1:2i0OySw99QjzBBQByd1Gr9gSjvuho1lHsJxIJ3gGbJI=
-github.com/openshift/api v3.9.0+incompatible h1:fJ/KsefYuZAjmrr3+5U9yZIZbTOpVkDDLDLFresAeYs=
-github.com/openshift/api v3.9.0+incompatible/go.mod h1:dh9o4Fs58gpFXGSYfnVxGR9PnV53I8TW84pQaJDdGiY=
+github.com/openshift/api v0.0.0-20200117162508-e7ccdda6ba67 h1:3Ocfy2IImlqqNHmWKn0WwLVR2npJuRVXWQYgvEwJEMk=
+github.com/openshift/api v0.0.0-20200117162508-e7ccdda6ba67/go.mod h1:fT6U/JfG8uZzemTRwZA2kBDJP5nWz7v05UHnty/D+pk=
 github.com/pelletier/go-toml/v2 v2.0.8 h1:0ctb6s9mE31h0/lhu+J6OPmVeDxJn+kYnJc2jZR9tGQ=
 github.com/pelletier/go-toml/v2 v2.0.8/go.mod h1:vuYfssBdrU2XDZ9bYydBu6t+6a6PYNcZljzZR9VXg+4=
 github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
```

**Comment by AhmedGrati** [comment]
@cdrage seems to be a problem with RPM. Can you take a look at this ? (I don't have an RPM-based env)

**Comment by cdrage** [comment]
Weird, we don't support RPM anymore.

I do not have a machine with RPM based env either at the moment. I'll spin one up and try it out.

**Comment by SergeyDjam** [comment]
RPM has nothing to do with it

**Comment by cdrage** [comment]
I'm closing this for now as it's unreproduceable, I was able to build 1.31.0 fine with `make bin`
