### ISSUE TITLE
[BUG] .deb/rpm files no longer generated in releases

### ISSUE THREAD

**Issue by mikecarr** [kubernetes/kompose#1720]
### Expected Behavior

deb and .rpm files available to download

### Actual Behavior

Since version [v1.27.0](https://github.com/kubernetes/kompose/releases/tag/v1.27.0), .deb and .rpm files no longer available

### Steps To Reproduce

Navigate to releases, view assets

### Kompose Version

```Text
v1.27.0 to latest
```

**Comment by cdrage** [comment]
On purpose, sorry! It started to become unmaintaineable as the software we use to generate them constantly changed, as well as the fact that statistically not many people were downloading them. 

I'd advise downloading the binaries instead.
