### ISSUE TITLE
[BUG] COMPOSE_FILE env var is not honored

### ISSUE THREAD

**Issue by olivierdalang** [kubernetes/kompose#1728]
### Expected Behavior

kompose should honor the [COMPOSE_FILE ](https://docs.docker.com/compose/environment-variables/envvars/#compose_file) env var.

In short, this envvar allows to define which yamls to load by default instead of the default docker-compose.yml if no `-f` params are given. It is a nice alternative to explicitly set them with `-f` each time you run a `docker compose` command.

### Actual Behavior

Currently kompose ignores `COMPOSE_FILE ` (and just defaults to docker-compose.yml if -f is not set)

### Steps To Reproduce

1. Create a `docker-compose.yml` and a `docker-compose.alternative.yml` configs that have visible differences
2. Run `COMPOSE_FILE=docker-compose.alternative.yml kompose convert -o output.yml`
3. See that the docker-compose.yml was converted

### Kompose Version

```Text
1.31.1 (46dcb9181)
```

### Docker-Compose file

```YAML
# docker-compose.yml
version: "3"
services:
  test:
    image: debian
---
# docker-compose.alternative.yml
version: "3"
services:
  test:
    image: alpine
```

**Comment by AhmedGrati** [comment]
I would say it's a feature rather than a bug.
/assign
