### ISSUE TITLE
Clean up the terminal output / add emojis / remove [INFO]

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1732]
### What would you like to be added?

We output to multiple files and we simply just put:

```
kompose convert
INFO Kubernetes file "frontend-service.yaml" created
INFO Kubernetes file "redis-master-service.yaml" created
INFO Kubernetes file "redis-replica-service.yaml" created
INFO Kubernetes file "frontend-deployment.yaml" created
INFO Kubernetes file "redis-master-deployment.yaml" created
INFO Kubernetes file "redis-replica-deployment.yaml" created
```

We should:

- [ ] Remove INFO and replace with an emoji / something colourful
- [ ] Add more information BEFORE (example, "Converting file: compose.yaml to Kubernetes")
- [ ] Add information AFTER (What do I do next? Tell them to run `kubectl apply -f .` to the files, etc.) as well as link to the user guide.
- [ ] If there are any warnings / failure, output them nicely.

A good example is how KIND does it:

![kind-create-cluster (1)](https://github.com/kubernetes/kompose/assets/6422176/fa163344-ee16-4a35-bb5c-2c29d8422f6b)

### Why is this needed?

Clean up terminal mess

**Comment by cdrage** [comment]
@AhmedGrati Do you mind if I pick this up? Been wanting to do some visual contributions lately :)

**Comment by AhmedGrati** [comment]
Yes sure!
/assign @cdrage
