### ISSUE TITLE
[BUG] Generated ConfigMap name too long

### ISSUE THREAD

**Issue by ThijsBroersen** [kubernetes/kompose#1738]
### Expected Behavior

A kubernetes resource name has a limit of 63 chars. When converting a docker-compose file with a `env_file` attribute it uses the full path of the resource as the name. This quickly exceeds the 63 char limit.

### Actual Behavior

It should restrict the name to filename or relative path (relative to the compose file) and stay withing 63 chars.

### Steps To Reproduce

have a docker-compose with a service.
Add to this service a `env_file` attribute.
convert with kompose
Result is a ConfigMap where the name is a reflection of the full file path. 

If the configmap name exceeds 63 then the resources cannot be deployed.

### Kompose Version

```Text
1.31.2
```

**Comment by cdrage** [comment]
@AhmedGrati I noticed this too and the naming is way too long, especially when you execute the file in a nested folder.

**Comment by ThijsBroersen** [comment]
Tried to make a fix: https://github.com/kubernetes/kompose/pull/1743

**Comment by StanleyP** [comment]
This is really breaks many workflows, it was bad mistake to use absolute filename for configmap naming - not only that its potentially too long.
Can we hope for some fix?

**Comment by cdrage** [comment]
> This is really breaks many workflows, it was bad mistake to use absolute filename for configmap naming - not only that its potentially too long.
> 
> Can we hope for some fix? @AhmedGrati 
> 
> 

Hi Stanley, we will get this in within a week :) there is a PR for this
