### ISSUE TITLE
[BUG] Kompose should raise and error when profiles are required

### ISSUE THREAD

**Issue by s33kers** [kubernetes/kompose#1748]
### Expected Behavior

Resources generated with compose

`kompose convert -f docker-compose.yaml -c -v` (version 1.29)
output
```
kompose convert -f docker-compose.yaml -c -v
DEBU Checking validation of provider: kubernetes
DEBU Checking validation of controller:
INFO Network ***-default is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
DEBU Target Dir: docker-compose
INFO Kubernetes file "docker-compose/templates/web-service.yaml" created
INFO Kubernetes file "docker-compose/templates/web-deployment.yaml" created
INFO Kubernetes file "docker-compose/templates/***-default-networkpolicy.yaml" created
INFO chart created in "docker-compose/"
```

### Actual Behavior

No resources generated with compose

`kompose convert -f docker-compose.yaml -c -v`
output
``` 
DEBU Checking validation of provider: kubernetes
DEBU Checking validation of controller:
DEBU Target Dir: docker-compose
INFO chart created in "docker-compose/"
```

### Steps To Reproduce

1. Create `docker-compose.yaml` with service and profile
2. `kompose convert -f docker-compose.yaml -c`
3. no templates created

### Kompose Version

```Text
1.31.2 (a92241f79)
(not working 1.30.0 (9d8dcb518))
(works fine 1.29.0 (997957870))
```

### Docker-Compose file

```YAML
version: '3'
services:
  web:
    image: nginx
    profiles:
      - test
    ports:
      - 80:80
```

**Comment by cdrage** [comment]
@axel7083 @AhmedGrati

**Comment by axel7083** [comment]
What if you use `--profile test` ?

**Comment by s33kers** [comment]
Yes, that helped, thanks. I was checking changelog between versions but wasn't aware of such change.

**Comment by AhmedGrati** [comment]
After doing some investigations, it seems that `compose-go/cli` should raise an error when no profile is found, so it's not a behavior that is controlled by Kompose.

**Comment by cdrage** [comment]
IMHO it is an error and it currently breaks functionality. `kompose convert` will not show any output if a profile is not found. Kompose should at least error when trying to convert.

**Comment by s33kers** [comment]
Yes, I would agree with @cdrage as output now is not informative enough. I would say behavior should be same as with `docker compose --profile` printing `no service selected` (e.g. with docker-compose.yaml provided in a description). So something similar could be here 🤷

**Comment by axel7083** [comment]
From my memories (need to be fact check) the library used for converting does not allow to know if nothing is output, we could probably some kind of work around to ensure something is produced

or

Parse before using the library, and check if some services have a profile set, and intersect with yhe given --profile arguments and produce warning if none matches or none are provided
