### ISSUE TITLE
[EPIC] Use kubernetes/client-go

### ISSUE THREAD

**Issue by kadel** [kubernetes/kompose#175]
It should be possible to use  [kubernetes/client-go](https://github.com/kubernetes/client-go) instead of digging through whole k8s.io/kubernetes.

As a result we might get smaller dependencies and it could  solve whole problem of conflicting kubernetes/kubernetes vs. openshift/kubernetes see: https://github.com/skippbox/kompose/pull/157#issuecomment-249858757

**Comment by cdrage** [comment]
I marked the title as [EPIC] but lets keep this issue open. Would massively reduce the size of the binary.

**Comment by mattlandis** [comment]
Hi, I am curious as to the progress here.  While debugging an [issue](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/137) with someone trying to use kompose on EKS getting prompted for username and password I found the version of client-go vendored here is out of date and does not include the new exec based authentication type.

Does it make sense to open a new issue for just for client-go vendor upgrade or include it as part of this EPIC?

**Comment by cdrage** [comment]
@mattlandis 

To be honest, we don't have much development time to implement client-go (it's a huge task that involves refactoring a ton of code / libraries). However, we are more than open to PR's. We will most likely re-visit `client-go` in the future.
