### ISSUE TITLE
[BUG] main example isn't working for compose

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1757]
### Expected Behavior

To be able to access port :80

### Actual Behavior

Unable to access / it comes up port 3000

### Steps To Reproduce

1. Download https://raw.githubusercontent.com/kubernetes/kompose/main/examples/docker-compose.yaml
2. Try running docker compose up
3. Unable to actually access port :80 (since it's actually listening on 3000...)

### Kompose Version

```Text
N/A
```

**Comment by cdrage** [comment]
@AhmedGrati Please bug me if this hasn't been fixed within a week haha. Right now I've got a modified guestbook-go example we can use.

**Comment by kundan2707** [comment]
@cdrage is this bug still present ?

**Comment by cdrage** [comment]
@kundan2707 Yes, I have a fix with a new example I'll need to push, sorry for the wait.
