### ISSUE TITLE
[BUG] changelong not updated for multiple release

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/kompose#1764]
### Expected Behavior

changelog should be updated

### Actual Behavior

not updated

### Kompose Version

```Text
1.31.2
```

**Comment by kundan2707** [comment]
page to update:
https://github.com/kubernetes/kompose/blob/main/CHANGELOG.md

/assign

**Comment by cdrage** [comment]
Hi, let's just delete it as we do not update it / we use GitHub release model for changelog generation anyways.

**Comment by kundan2707** [comment]
@cdrage  are you asking to delete changelog.md file?

**Comment by cdrage** [comment]
> @cdrage are you asking to delete changelog.md file?

yes

**Comment by kundan2707** [comment]
@cdrage  OK
I will raise PR for the same
