### ISSUE TITLE
Add label for initContainers

### ISSUE THREAD

**Issue by dennohpeter** [kubernetes/kompose#1772]
### What would you like to be added?

Add 
`kompose.init-contaners.name: "foo"`,
`kompose.init-contaners.image: "bar"`, 
`kompose.init-contaners.command: []` labels

### Why is this needed?

This will ease the migration from docker-compose to kubernetes and will remove the need to manually edit the generated yaml files.

**Comment by cdrage** [comment]
Closed in https://github.com/kubernetes/kompose/pull/1840
