### ISSUE TITLE
the image used in the https://kompose.io/user-guide/ is broken & has to be replaced  

### ISSUE THREAD

**Issue by Mohamed-AH** [kubernetes/kompose#1789]
### Expected Behavior

the image  (gcr.io/google_samples/gb-frontend:v4)  in https://kompose.io/user-guide is broken and results in image pull error, it could be changed to us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5

### Actual Behavior

the image  (gcr.io/google_samples/gb-frontend:v4)  in https://kompose.io/user-guide is broken and results in image pull error, it could be changed to us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5

### Kompose Version

```Text
1.31.2 (a92241f79)
```

**Comment by cdrage** [comment]
Fixed via https://github.com/kubernetes/kompose/pull/1803
