### ISSUE TITLE
Create ConfigMaps automatically from existing docker-compose volume mounts.

### ISSUE THREAD

**Issue by eldondevat** [kubernetes/kompose#1794]
### What would you like to be added?

ConfigMaps can be created and mounted into pods where docker-compose mounts config files local to the host into containers.

### Why is this needed?

I recently ran kompose to convert the docker-compose file from (/fleetdm/fleet) to something I could run on k3s. Several of the containers are configured via single-file mounts from the source directory of fleet into the accessory containers. While some (such as the docker socket) don't make sense, many are static configuration files (certificates, etc), which could make sense as ConfigMap contents.

**Comment by wzrdtales** [comment]
yeah also just wondered about this. Host files should converted to configmaps straight forward
