### ISSUE TITLE
[BUG] Update README.md doc

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/kompose#1822]
### Expected Behavior

Kompose package not available on Ubuntu ( Jammy or Focal release ) repositories ( can be searched [here](https://packages.ubuntu.com) ). Kompose binary available on Opensuse seems to be [1.30](https://software.opensuse.org/package/kompose) and on NixOS [1.26.1](https://search.nixos.org/packages?channel=23.11&show=kompose&from=0&size=50&sort=relevance&type=packages&query=kompose).

Latest release can be easily installed using scripts.

### Actual Behavior

As installation instruction for these Distros are already unavailable on Ubuntu/debian, NixOS and OpenSuse.

### Kompose Version

```Text
1.32
```

### Docker-Compose file

```YAML
None
```

### Anything else?

None

**Comment by utkarsh-singh1** [comment]
Also seems like For EPEL, installation binary is only available in EPEL version 7 not on 8.

**Comment by utkarsh-singh1** [comment]
- EPEL 7 repo - https://repo.extreme-ix.org/epel/7/SRPMS/Packages/k/
- EPEL 8 repo - https://repo.extreme-ix.org/epel/8/Everything/SRPMS/Packages/k/

**Comment by cdrage** [comment]
Closed via https://github.com/kubernetes/kompose/pull/1823 thank you so much for the update!
