### ISSUE TITLE
Support for `network_mode: service:`*

### ISSUE THREAD

**Issue by jan-hudec** [kubernetes/kompose#1846]
### What would you like to be added?

When a service has `network_mode` of the form `service:`*anotherservice*, it should be added as a second container into the deployment of *anotherservice* instead of getting its own deployment. Because this specification means the services will see each other on `localhost`, which roughly corresponds to being in the same pod in kubernetes.

### Why is this needed?

I tried to convert https://github.com/dehydr8/elevation-of-privilege/blob/master/docker-compose.yml to Kubernetes, but the resulting manifest can't be used as is, because the two containers are set up so the `client` one, working as reverse proxy for `server`, references the server at three fixed addresses `ws://localhost:8000`, `http://locahost:8001` and `http://localhost:8002` and if they are started in separate pods, they can't.

**Comment by devinrhode2** [comment]
I think This just saved me the trouble of trying to use kompose, and instead what ill need to do, until this issue is resolved, is try to directly author a pod which runs two containers

**Comment by devinrhode2** [comment]
Actually looks like this issue can be closed based on this PR: https://github.com/kubernetes/kompose/pull/1848

**Comment by devinrhode2** [comment]
I'm not able to close, can you try @jan-hudec ?

**Comment by cdrage** [comment]
I'll close! Feel free to try out our newest release with network mode.
