### ISSUE TITLE
[BUG] Update Kompose completion 

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/kompose#1966]
### Expected Behavior

kompose completion generate a script that introduces a completion for the shell but this feature does not work for new instance of shell. 

### Actual Behavior

Added a suggestion to add these commands to shell configuration file to enable completion permanently.

### Kompose Version

```Text
1.34
```

**Comment by utkarsh-singh1** [comment]
Also, commands can be improved to make them directly add to the config file.

Ex.

```shell
echo "source <(kompose completion bash)" >> ~/.bashrc
  
echo "source <(kompose completion zsh)" >>  ~/.zshrc
 
echo "kompose completion fish | source" >> ~/.config/fish/config.fish
```

**Comment by cdrage** [comment]
Hi, I tested all three and it still works. Your PR only adds comments.
