### ISSUE TITLE
kompose logo

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#274]
It would be great to have a logo for kompose project!

**Comment by ericchiang** [comment]
If recommend holding off on this until kompose either graduates from the incubator or finds a different home. If it becomes an official kubernetes project I'm sure some of the kubernetes design folks will have opinions about a logo.

**Comment by aditya-konarde** [comment]
@surajssd I was just browsing through the issues, does Kompose has a logo now? If it doesn't, good time to get one as its now an official Kubernetes project and has graduated :)

**Comment by 030** [comment]
![kompose](https://user-images.githubusercontent.com/7524528/61406108-7eca4480-a8db-11e9-8c2c-23bffae0828d.png)
