### ISSUE TITLE
support adding kompose label for bundle file

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/kompose#276]
$title

**Comment by procrypt** [comment]
@ngtuna can you please assign it to me.

**Comment by procrypt** [comment]
Thanks @pradeepto

**Comment by kadel** [comment]
@cdrage If I'm not mistaken support for Docker bundle format was removed from Kompose. Is that true @cdrage?

**Comment by cdrage** [comment]
@kadel yeah, *way* too many issues with bundling and it's still an experimental feature. We all agreed that we would stop development on it until Docker accepts it as mainline. See: https://docs.docker.com/compose/bundles/

**Comment by cdrage** [comment]
Although I believe we should keep this open :+1:

**Comment by hangyan** [comment]
close this. Since we don't support bundle anymore
