### ISSUE TITLE
Improve logging messages in unit tests

### ISSUE THREAD

**Issue by containscafeine** [kubernetes/kompose#351]
If would be great if unit tests throw better log messages while bring run, this would help in better troubleshooting which tests are failing and which are passing.

**Comment by surajnarwade** [comment]
@surajssd , we can close this.

**Comment by cdrage** [comment]
Yup, This is merged.

**Comment by surajssd** [comment]
I don't think this is fixed, #350 was not for this issue.

**Comment by cdrage** [comment]
@containscafeine @surajssd can we close this?
