### ISSUE TITLE
Add support for s2i in buildconfigs for OpenShift

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#353]
right now the build startegy is Docker only, it would be great if s2i is also supported.

**Comment by kadel** [comment]
I don't think it makes sense to add support for S2I to Kompose.
I defies purpose of Kompose. Kompose is tool that helps docker-compose users move to Kubernetes.

S2I is replacement for Dockerfiles. And everyone who is using docker-compose with `build` is building images using Dockerfiles. 

I just don't se a way how we can support s2i builds and also making sure that same docker-compose.yml file with same build directory will still with `docker-compose` tool.

On the other side, supporting s2i builds is great usecase for https://github.com/redhat-developer/opencompose

**Comment by stephanosbacon** [comment]
What about in effect generating an s2i builder image given a Dockerfile?  Or if the base image in the Dockerfile is a builder image, then the rest of the Dockerfile takes the place of the assemble and run scripts of the builder image?

**Comment by surajssd** [comment]
@stephanosbacon AFAIK builder images are generic enough to have things needed to run code, and people using docker-compose generally do have steps in Dockerfile where code is copied from local repo into the image, so I don't think using that Dockerfile to generate builder image makes sense.

>Or if the base image in the Dockerfile is a builder image, then the rest of the Dockerfile takes the place of the assemble and run scripts of the builder image?

I don't understand this part can you explain it?

**Comment by stephanosbacon** [comment]
@surajssd Sure, they can be generic, but why not generate one on the fly?  Take a generic node.js builder image for example - it's assemble script will likely copy all the subdirectories under . (as the ones that I've seen do), but suppose I don't want that and in my Dockerfile I control exactly what I want copied (e.g. my unit tests).  I may want my unit test code built into a separate container, for example.  What I was thinking was that given a Dockerfile, one has a lot of the information one needs to generate a builder on the fly so to speak.

re the second part - as I mentioned above, in some sense a Dockerfile does what the assemble script does in a Dockerfile, doesn't it?  Why not generate the assemble script from it then, thereby giving the developer a bit more control over what gets put into the container.

**Comment by kadel** [comment]
> What I was thinking was that given a Dockerfile, one has a lot of the information one needs to generate a builder on the fly so to speak.

What are benefits of this over building finished image directly from Dockerfile? 
If i understand it correctly, `docker build` will have to be used to build builder image, and that builder image will be specific only for this one case.

**Comment by stephanosbacon** [comment]
On OpenShift Online and OpenShift Dedicated, one cannot run docker builds (because as I understand it the docker socket is a security hole), and writing one's own builder image is more involved than writing a Dockerfile.

**Comment by kadel** [comment]
Yes. And for the same reason builder image will have to be build outside of the OpenShift cluster and resulting build image will be specific  for given project.

Than why not build image directly from Dockerfile outside OpenShift and import it to OpenShift as ImageStream?

For me it all sounds like a lot of complicated thinks, with some stuff that I'm not even sure is possible to do,  without any benefits.


Maybe I'm still not getting it. That is also quite possible :blush:

**Comment by stephanosbacon** [comment]
It's entirely likely I'm out in left field, but the builder image would only have to be built once outside of openshift, then imported and re-used to build the project itself multiple times.

What this gets me as a developer is the ability to use my Dockerfile (which presumably isn't going to be changing as frequently as my code) to build a custom builder image for my project (yes, this would have to be built outside of openshift).  This will let me take advantage of s2i builds and build pipelines running entirely in openshift - which I can't do if I'm doing docker builds at least on OpenShift online and dedicated, and I don't have to learn how to create builder images which are kind of arcane and OpenShift-specific.

Ideally kompose would also have flags that tell it to generate build pipelines as well.

**Comment by kadel** [comment]
> What this gets me as a developer is the ability to use my Dockerfile (which presumably isn't going to be changing as frequently as my code) to build a custom builder image for my project (yes, this would have to be built outside of openshift). This will let me take advantage of s2i builds and build pipelines running entirely in openshift - which I can't do if I'm doing docker builds at least on OpenShift online and dedicated, and I don't have to learn how to create builder images which are kind of arcane and OpenShift-specific.

OK, I can see your point. 

Only problem that I can see with this is that it will depend on how well is Dockerfile written. I'm afraid that it won't be possible to do it for any Dockerfile and Dockerfile will have to be written in specific way.
I'll try look into it. It might be interesting.

**Comment by cdrage** [comment]
As what @kadel I don't believe it makes sense to add this to Kompose. Since there hasn't been much discussion on this, let's close this issue and re-open if there is some interest.
