### ISSUE TITLE
kompose binary per merge? (add nightlies)

### ISSUE THREAD

**Issue by containscafeine** [kubernetes/kompose#355]
Hi team,

We are merging PRs to master which result from the issues we face during deployments everyday. This code goes into master and we can build it locally after pulling it.

Is there any way we can host the kompose binary somewhere, resulting from the current state of master?

This would help in making the conversion and deployment automated by simply downloading the binary and running it instead of building the code locally from master and then do the deployments.

Some place where maybe Travis can push the binary after each merge, like AWS S3 or Dropbox or Google Drive?

Thoughts?

**Comment by kadel** [comment]
Long time ago, I created something like this for Henge:
https://github.com/kadel/henge/blob/travis-deploy/hack/upload-master-builds-to-dropbox.sh

**Comment by pradeepto** [comment]
Throwing this in the ring. https://docs.travis-ci.com/user/deployment/releases/ Basically, uploading the binary to GH releases via Travis.

**Comment by kadel** [comment]
> Throwing this in the ring. https://docs.travis-ci.com/user/deployment/releases/ Basically, uploading the binary to GH releases via Travis.

Looks good. This would be better than dropbox/drive... If we plan to keep only latest binary (nigtly).

But if we want keep history of binaries (for every PR), than I think other place would be better, as github releases page might become chaotic.

**Comment by cdrage** [comment]
this has been added!
