### ISSUE TITLE
wrong git revision number in version output

### ISSUE THREAD

**Issue by kadel** [kubernetes/kompose#422]
code revision from which binary is build is wrong.

```
▶ make
go build -ldflags="-w -X github.com/kubernetes-incubator/kompose/version.GITCOMMIT=be042c7" -o kompose main.go

▶ ./kompose version
0.2.0 (64433fd)

▶ git rev-parse --short HEAD
be042c7
```

`kompose version` should output same revision as current source.
 It looks like there is commitid inside [version.go](https://github.com/kubernetes-incubator/kompose/blob/master/cmd/version.go#L29)  Shouldn't this show HEAD as default or something like this?
 
What if we get rid of this? Do we need to show  commit id in version output?

**Comment by cdrage** [comment]
Ahhh.. I changed it to show the Git Commit for the current version instead of HEAD... Should we just get rid of this instead?

**Comment by surajssd** [comment]
@kadel you re-opened this? Why is that so?

**Comment by kadel** [comment]
I hoped that we might discuss here if maybe we wan't to get rid of whole commitid (showing commit id in `kompose version` output)

**Comment by cdrage** [comment]
@kadel Should we close this? Having the hash in the ID has actually helped in terms of releases as well as troubleshooting (whether or not it's been compiled locally against master, etc.)
