### ISSUE TITLE
move functional tests to golang

### ISSUE THREAD

**Issue by containscafeine** [kubernetes/kompose#432]
Hi,

Currently, currently all the functional tests being run by `make test-cmd` are written in shell scripts, which are very difficult to maintain, debug and produce _a lot_ of false positives e.g. #431, etc.

Should we move these to golang for better testing?

(thinking out loud: how about python which has a rich set of testing libraries e.g. `py.test`)?

Thoughts?

**Comment by kadel** [comment]
:+1:  for writing them in go.


> (thinking out loud: how about python which has a rich set of testing libraries e.g. py.test)?

I think it is better to avoid adding new language with additional dependencies, even if it is just for testing.

**Comment by procrypt** [comment]
@containscafeine @kadel I'm taking this up.

**Comment by surajssd** [comment]
I am :+1: for Python but it's just that people should know one more language for doing any contribution.

But if you know Python it will be very easier.

**Comment by kadel** [comment]
Please no Python, no other language. 
I would rather stick with bash rather than introducing another language.

**Comment by containscafeine** [comment]
Ack, let's move all of 'em to golang :metal:

**Comment by surajssd** [comment]
maybe we can look at this framework https://github.com/DATA-DOG/godog it is for doing golang functional testing.

**Comment by procrypt** [comment]
@surajssd Do we really need to use a Framework for it, I mean we are just comparing the output.

**Comment by surajssd** [comment]
@procrypt not really if we can achieve what we do now without any framework then it's good.
