### ISSUE TITLE
Support for: isolation

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#438]
No error / warning when using this key.

**Comment by procrypt** [comment]
@cdrage `isolation` has only one value for Linux which is `default` and for windows it has a some value to pick from like `process`, `hyperv` and `default`. The doc says this option is useful in situations where you are running Docker containers on Windows.
Do we need to add support for this? [Reference](https://docs.docker.com/engine/reference/commandline/run/#specify-isolation-technology-for-container---isolation)

**Comment by kadel** [comment]
It doesn't make sense to map this to Kubernetes. We can display warning if it is set to something else than default.
But I wouldn't worry about that for now. I don't think that this is used.

**Comment by procrypt** [comment]
Can we close this issue?

**Comment by kadel** [comment]
I note here. `issolation` is in compose version 2.1 and up. 
2.1 is not yet supported by libcompose.

**Comment by procrypt** [comment]
@kadel adding it to the list of unsupported keys.

**Comment by surajnarwade** [comment]
@kadel , @cdrage  label, `compose v2.1` needed

**Comment by cdrage** [comment]
Closing this as we are not supporting it :+1:
