### ISSUE TITLE
Support for sysctls

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#441]
```
▶ kompose convert --stdout
ERRO Could not parse config for project wikus : Unsupported config option for redis service: 'sysctls' 
FATA Failed to load compose file: Unsupported config option for redis service: 'sysctls' 
```

**Comment by procrypt** [comment]
@cdrage want to work on it.

**Comment by procrypt** [comment]
@cdrage I want to work on it, after we finish up with the discussion :)

**Comment by cdrage** [comment]
Yeah :) I think that we *shouldn't* support sysctls as I can't find anything compareable in Kubernetes.

**Comment by cdrage** [comment]
Adding it to list of unsupported keys would be helpful.

**Comment by procrypt** [comment]
@cdrage `kompose convert -f sample.yml --stdout` 
```bash
ERRO Could not parse config for project komposefiles : Unsupported config option for web service: 'sysctls' 
FATA Failed to load compose file: Unsupported config option for web service: 'sysctls'
```
This is libcompose issue.

**Comment by cdrage** [comment]
thanks @procrypt :) I'll subscribe to that issue.

**Comment by cdrage** [comment]
woops, closed by accident

**Comment by surajssd** [comment]
this was again closed by accident it seems @procrypt @cdrage ?

**Comment by surajssd** [comment]
because #459 never fixed this issue, it only added this directive to unsupported keys?

**Comment by kadel** [comment]
@surajssd You are right. it was not fixed in #459

There is different problem with `sysctls` - it is only in docker-compose v2.1 that is not supported by libcompose

**Comment by kadel** [comment]
I probably shouldn't reopen it as this is more about adding support for v2.1 :smile:

**Comment by cdrage** [comment]
I found a 1-1 mapping for this within Kubernetes: https://kubernetes.io/docs/concepts/cluster-administration/sysctl-cluster/ and thus we can implement it :+1:

**Comment by cdrage** [comment]
Okay, two problems:

1. sysctls is not yet supported / added to libcompose
2. since sysctls is ignored by docker/cli, it is also not supported:
```
github.com/kubernetes/kompose  add-sysctls ✗                                                                                                                4h3m ◒  ⍉
▶ ./kompose convert --stdout -f script/test/fixtures/sysctls/docker-compose.yaml
FATA net.core.somaxconn Additional property net.core.somaxconn is not allowed 
```

**Comment by cdrage** [comment]
This is wayyyyy too little of a use-case. I'm going to close this for now.
