### ISSUE TITLE
Support for: userns_mode

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#443]
No error / warning when using this key

**Comment by procrypt** [comment]
@cdrage This is libcompose issue.
```bash
$ libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
ERRO[0000] Could not parse config for project komposefiles : Unsupported config option for web service: 'userns_mode' 
FATA[0000] Failed to read project: Unsupported config option for web service: 'userns_mode' 
```

Issue created on `libcompose` https://github.com/docker/libcompose/issues/444

**Comment by cdrage** [comment]
Closing this as I've updated the conversion document to reflect that this is not supported in Kubernetes and this key is also dropped in Docker Compose Version 3.
