### ISSUE TITLE
Support for private Docker registry ImageStream

### ISSUE THREAD

**Issue by dkarlovi** [kubernetes/kompose#446]
I'm trying to setup OS to pull images from my private registry:

    # docker-compose.yml
    services:
      web:
        image: registry.example.com/my/example.com:latest
        build:
          context: .
          dockerfile: ./.infra/docker/nginx/Dockerfile

My desired output would be:

    apiVersion: v1
    kind: ImageStream
    spec:
        tags:
        -
            from:
                kind: DockerImage
                name: registry.example.com/my/example.com:latest
            name: latest

without the `BuildConfig` because I wish to use pre-made images instead of making them on the OS cluster. The way I see it, currently `kompose` always uses source to image builder strategy, it would be cool to allow for this behavior too.

Please note I'm quite new to Openshift and` kompose` (much more experience with `docker-compose`) so if this doesn't make sense in this context, feel free to correct me. Thanks.

**Comment by containscafeine** [comment]
Hey @dkarlovi,

Currently we do not have an option not to generate a BuildConfig if `build:` section is there in the docker compose file, so for this use case, it'd make sense to comment out the `build:` section in the docker compose file (that's what I do).

Also, the issue title says `Support for private repository ImageStream`, I'm not sure what does this mean? If you are talking about a private Docker or Git registry, then if your node can access that endpoint, everything should work.
If you are talking about an insecure registry, then you might have to run something like `oc patch is $imagestream -p '{"metadata":{"annotations":{"openshift.io/image.insecureRepository": "true"}}}}'` for the ImageStream to work.

Does this help?

**Comment by dkarlovi** [comment]
@containscafeine thanks for your reply.

I'm talking about private Docker registry, not private Git repository, changed the title to reflect that, sorry about the confusion.

Idea is, my CI process builds the images and runs the whole process on them, it makes sense to use those exact images when actually running your production.

The poiint of this issue is to allow for additional semantic when converting, ie.
> My `docker-compose.yml` has a build section, but I'd like to use the Docker image based `ImageStream` instead of a source-to-image `BuildConfig`.

Ssay `--use-docker-image-stream` or similar? If it does exactly that by commenting out the build section, that's fine as a workaround, but why not enable it fully?

**Comment by surajssd** [comment]
@dkarlovi that can be done I think need to add some checks here, that is:

if `image` and `build` given we can pick up the image name directly and not create `bc`

only if `build` provided create a `bc`.

WDYT @kadel @containscafeine @rtnpro  ? thoughts

**Comment by dkarlovi** [comment]
@surajssd sounds good to me.

**Comment by cdrage** [comment]
I believe we should still implement this in the future. Let's freeze this.

**Comment by dkarlovi** [comment]
@cdrage typo. :)

**Comment by cdrage** [comment]
5 year old issue that we haven't had much discussion on or requests for it being added, so going to close this! sorry!
