### ISSUE TITLE
using kompose as a library

### ISSUE THREAD

**Issue by concaf** [kubernetes/kompose#464]
Is it possible to use `kompose` as a go library, which can just be imported and used.

Something like `artifacts := kompose.Convert("/app1/docker-compose.yml", "kubernetes")`.

It would be very useful to be able to use kompose as a library, we should investigate that :)

CC: @kadel

**Comment by surajssd** [comment]
:+1:

**Comment by cdrage** [comment]
This is going to take *a lot* of effort. Let's label this as a help wanted. I'll try and work on it this upcoming month.

**Comment by xianlubird** [comment]
@hangyan 靠你了，哈哈

**Comment by Vibzy19** [comment]
I would like to work on this @hangyan @containscafeine

**Comment by cdrage** [comment]
@Vibzy19 Honestly, it's a huge task / epic, but feel free to try :+1: it may take way longer than expected.

**Comment by Vibzy19** [comment]
@cdrage Thank you for the heads up :) I have already started working on it, let's see till where can I take this.
