### ISSUE TITLE
Docker build fails:  Failed to push image: unauthized:authentication required

### ISSUE THREAD

**Issue by stephanosbacon** [kubernetes/kompose#496]
Pushing image 172.30.46.106:5000/chat/chatback:latest ...
Pushed 0/20 layers, 0% complete
error: build error: Failed to push image: unauthorized: authentication required

After running kompose convert, and editing the resulting buildconfig such that it has a dockerfilePath (dunno if this should make a difference), the resulting build fails with the above failure.

The relevant test case is at:  https://github.com/stephanosbacon/chatBack/tree/master/build/kompose

**Comment by stephanosbacon** [comment]
If I delete the buildconfig, re-create it via oc-new-build, and then go edit the yaml to set the dockerfilePath, I get the following, which works:

apiVersion: v1
kind: BuildConfig
metadata:
  name: chatback
  namespace: chat
  selfLink: /oapi/v1/namespaces/chat/buildconfigs/chatback
  uid: 2de0fe2a-0a71-11e7-8156-f20cfd71a2ac
  resourceVersion: '1329'
  creationTimestamp: '2017-03-16T17:51:27Z'
  labels:
    build: chatback
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
spec:
  triggers:
    - type: GitHub
      github:
        secret: DJO8oSqrmDoNkzj7m4Cf
    - type: Generic
      generic:
        secret: rxdnhyBexz6kPqofQX43
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/stephanosbacon/chatBack.git'
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: build/Dockerfiles/Dockerfile_server
  output:
    to:
      kind: ImageStreamTag
      name: 'chatback:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 2

**Comment by surajnarwade** [comment]
@stephanosbacon , I am trying to reproduce this error, this config also gives me the same error. this error is coming from openshift and is being tracked here https://github.com/openshift/origin/issues/12474

**Comment by kadel** [comment]
Hmm that is strange, I just tried that and it worked for me.

I've skipped `oc login` and `oc adm policy` commands from your `oc_setup` script. 
So it looks like it will be some issue with permissions.

**Comment by kadel** [comment]
New observations.
If I use minishift v0.9.0 it works perfectly.
But with new 1.0.0-beta.5 I get same error. 

Something is different in new minishift :-(

**Comment by kadel** [comment]
It looks like its bug in openshift.

If you create buildconfig first and then imagestream it fails. If imagestream is created first it is ok.

**Comment by stephanosbacon** [comment]
Will OpenCompose work around it?  (It seems to be a combination big deal/low priority to fix on the OpenShift side)

**Comment by kadel** [comment]
with `kompose up` or if you save output to one file ImageStream will always be before BuildConfig. (Or at least it should be if I remember correctly :nerd_face:   )

**Comment by surajnarwade** [comment]
@kadel , that worked :stuck_out_tongue:

**Comment by cdrage** [comment]
Can we close this?

**Comment by surajnarwade** [comment]
cc @stephanosbacon

**Comment by stephanosbacon** [comment]
Sure

**Comment by sp1d3rino** [comment]
Check if the serviceaccount chat/builder with system:image-builder role is missing then add it
