### ISSUE TITLE
make flags global which are common

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#514]
flags like `replicas` and other flags that are repeating should be implemented only once, which means make it global.

This came to my mind after reading #506

**Comment by kadel** [comment]
but `replicas` doesn't make sense for `down` command :-(

Shouldn't be global parameters valid for all (up,down,convert) commands?

**Comment by surajssd** [comment]
@kadel didn't think about that! just thought about the repetition!

**Comment by kadel** [comment]
agreed that repetition is ugly, and we should figure out how to reuse flags between `up` and `convert` so we can define them in only one place.

But solution shouldn't be making it global, because that we will have to ignore for commands where it doesn't make sense, that might be even more confusing :-(

**Comment by cdrage** [comment]
I think we can remove the `--emptyvols` and `--replicas` flags from `kompose down`:

```
▶ kompose down --help
Delete instantiated services/deployments from kubernetes. (default "kubernetes")

Usage:
  kompose down [flags]

Flags:
      --emptyvols      Use Empty Volumes. Do not generate PVCs
      --replicas int   Specify the number of repliaces in the generate resource spec (default 1)
```

**Comment by kadel** [comment]
> I think we can remove the --emptyvols and --replicas flags from kompose down:

yes we should do that.

but we still have same flags defined in two places.
for example `--replicas` is in `up.go` and in `convert.go`

**Comment by cdrage** [comment]
@kadel Unfortunately I don't think there is a way to define a global parameter and remove it from only one particular one. Having it in both up.go and convert.go seems the best bet. At least it's better than how we did it with urfave/cli :+1:

**Comment by kadel** [comment]
I've some ideas that might work, but I have to try it

**Comment by cdrage** [comment]
Hey @kadel emptyvols and replicas was removed from Kompose down, should we close this issue or is there anything else we need to discuss  to refactor this?

**Comment by cdrage** [comment]
Going to close this for now, let's re-open at a later-date if we find a refactor for global flags :+1:
