### ISSUE TITLE
kompose should give warning on providing blank environment variables

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/kompose#545]
Sometimes docker-compose files have environment variables which are not set, In that case, we should give warning to user.

inspired from https://github.com/redhat-developer/opencompose

**Comment by kadel** [comment]
I don't know if this makes sense for docker-compose.
environment variables has one additional feature in docker-compse.
If value is not set for in docker-compose file, than value is taken from environment that runs `docker-compose` command.

**Comment by cdrage** [comment]
@kadel @surajnarwade If a value isn't provided, docker-compose will retrieve it from the host machine.

Should we close this issue?
