### ISSUE TITLE
kompose passes a kubernetes deployment without image 

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#571]
I have a docker-compose service with build specified but without image. So since kompose has no build support with kubernetes so it should error out saying that there is no image provided.

```bash
$ kompose up
WARN Kubernetes provider doesn't support build key - ignoring 
INFO We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 
 
INFO Deploying application in "default" namespace 
INFO Successfully created Service: foo            
FATA Error while deploying application: Deployment.apps "foo" is invalid: spec.template.spec.containers[0].image: Required value 
```

I am using following docker-compose file:

```yaml
$ cat docker-compose.yml 
version: '2'

services:
  foo:
    build: .
```

So I would recommend that we suggest user to add one more additional field called `image` to provide the image name explicitly.

**Comment by procrypt** [comment]
@surajssd Working on this.

**Comment by cdrage** [comment]
I don't believe this is an issue.

If an image key isn't passed, it will use the service name as per how it works in Docker Compose. I work around this in #521 (and thus merging #521 will fix this issue).

For your example, it will build as image "foo".

**Comment by surajssd** [comment]
@cdrage I would not want to do magic here and ask user to specifically provide the image name, because then user might be confused why this is failing!

**Comment by cdrage** [comment]
@surajssd I don't believe it's "magic". This is how Docker Compose does it while building, so I don't see a problem with it converting to Kubernetes and taking the appropriate Docker Image name as the service name.

**Comment by cdrage** [comment]
@surajssd @procrypt Should we close this? Did my comments address the problem?

**Comment by surajssd** [comment]
This should fail now right ?

**Comment by cdrage** [comment]
@surajssd No? I thought my comments address why having no image is still valid with build (it builds the docker container and tags it)
