### ISSUE TITLE
Tracking card for new `deploy` keys in v3

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#644]
We have to cover the new keys in deploy for v3 of Docker Compose, at the moment, we only have mem_limit complete.

New keys:

- [x] mode
- [x] replicas
- [x] placement
- [ ] update_config
- [x] resources
- [x] restart_policy
- [x] labels
- [x] cpus (under 'resources')
- [X] memory (under 'resources')

**Comment by surajnarwade** [comment]
I will take `replicas` key

**Comment by cdrage** [comment]
@surajnarwade I already started work on it, sorry :( I'm setting up a separate function so that we can parse these keys easier.

**Comment by surajnarwade** [comment]
@cdrage okay no worries

**Comment by ashetty1** [comment]
@cdrage also, Ports in long syntax?

**Comment by cdrage** [comment]
@ashetty1 Open up another issue for that. But it's v3.2 and it's not even integrated into moby/moby yet.

**Comment by cdrage** [comment]
Hey @surajnarwade wanna take this up and see how we can implement the `deploy` side of things? I was starting work on this but got side-tracked by the 1.0.0 release

**Comment by surajnarwade** [comment]
@cdrage, sure, can you point me towards where you start

**Comment by cdrage** [comment]
@surajnarwade https://github.com/docker/cli/blob/master/cli/compose/types/types.go#L159 would be a good start. Luckily we're able to easily access the deploy keys via v3.go :smile:

**Comment by surajnarwade** [comment]
I will take `restart-policy` as well

**Comment by surajssd** [comment]
this was closed by #664 this by mistake, if this is a tracking card @surajnarwade please don't add the fixes thing in your PR because this will get closed on the next PR that says that again

**Comment by surajnarwade** [comment]
@cdrage @surajssd , I think `mode` is swarm specific command, it will be better if we can add it to unsupported keys

**Comment by cdrage** [comment]
Three more to-go.

@surajnarwade 

I have added mode here: https://github.com/kubernetes/kompose/pull/771 you said it couldn't be done, but I did it! :+1:

**Comment by surajnarwade** [comment]
@cdrage , that's good.
I have investigated on `placement` key, I found only two mappings,
* `engine.labels.operatingsystem` is equivalent to `beta.kubernetes.io/os`
* `node.hostname` is equivalent to `kubernetes.io/hostname`

Does this makes sense ?
I havn't found any other mappings.

**Comment by cdrage** [comment]
@surajnarwade that makes sense. everything else we can warn / info out.

**Comment by cdrage** [comment]
Placement has been completed. 1 more to-go.

**Comment by surajnarwade** [comment]
@cdrage  since `update_config` has no direct mapping in kubernetes, Let's close this issue

**Comment by cdrage** [comment]
@surajnarwade Before that, we will have to update the conversion matrix documentation.

**Comment by surajnarwade** [comment]
@cdrage since conversion matrix is also updated now, Let's close the issue :)
