### ISSUE TITLE
Clean up and add current example files to integration tests.

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#675]
Two things:

- Test each example to see if they work and convert correctly
- Add integration tests for each one, test against a real Kubernetes cluster

**Comment by surajnarwade** [comment]
I am taking this up

**Comment by surajnarwade** [comment]
As of now, I have tested each  example from our example directory and all are working on minikube.

**Comment by cdrage** [comment]
@surajnarwade 

Thanks, let's add this to our integration tests though.
