### ISSUE TITLE
One Script to Run Them All

### ISSUE THREAD

**Issue by phatlast96** [kubernetes/kompose#683]
Running each individual K8s YAML file is dramatic change for anyone who is used to Docker Swarm, who tends to only run a single 'docker-compose.yaml' file for deployment. 

It'd be nice for kompose to produce a single, executable script that runs all the K8s YAML files it produced. This thus improves the workflow of a former Docker Swarm user in addition to easing their transition to Kubernetes.

There could be an option to opt in or opt out of this feature.

If not, then it'd be nice if all the produced K8s YAML file are organized into a single folder.

**Comment by JadCham** [comment]
@phatlast96  When you convert you can use kompose convert -o output.yaml and the output will be aggregated in one single file. I think this is very close to docker-compose.

**Comment by cdrage** [comment]
What @JadCham said :)

If you do `-o` everything should work correctly in one file.

**Comment by phatlast96** [comment]
Thanks! I did not know that!
