### ISSUE TITLE
Add StatefulSet

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#698]
We've gone DaemonSet, let's add StatefulSet now.

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by yuikns** [comment]
May I know what is the status now?

**Comment by jasi110** [comment]
Is statefulset still being pursued?

**Comment by maxdanilov** [comment]
Is there any update on adding `StatefulSet` support?

**Comment by danetrata-ulap** [comment]
Any idea how to implement this? I don't imagine every service needs to be a stateful set.

**Comment by hangyan** [comment]
closed by #1452
