### ISSUE TITLE
Release process 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kompose#70]
Follow up https://github.com/skippbox/kompose/issues/64#issuecomment-235107109:

> In the release note we can provide checksums and installation guide, something like this:
> ## Installation
> ### Linux
> 
> ```
> curl -Lo kompose https://github.com/skippbox/kompose/releases/download/v0.0.1-beta.1/kompose_linux-amd64 && chmod +x kompose && sudo mv kompose /usr/local/bin/
> ```
> ## Checksums
> ### Linux
> 
> ```
> $ openssl sha1 /usr/local/bin/kompose
> SHA1(/usr/local/bin/kompose)= 826c247a4bdca44d2b68bef48d6649dd86813ef2
> ```

We should have a release process (or did I miss it?)

**Comment by janetkuo** [comment]
Just found it https://github.com/skippbox/kompose/blob/master/RELEASE.md

**Comment by kadel** [comment]
I agree we should have release process defined.

I think that current [RELEASE.md](https://github.com/skippbox/kompose/blob/master/RELEASE.md) is from some kind of Kubernetes repo template that this was this repo based on.

**Comment by janetkuo** [comment]
We should follow [semantic versioning](http://semver.org/) and test if the released binaries will work on different platforms.

**Comment by sebgoa** [comment]
Also discuss schedule of releases

**Comment by kadel** [comment]
How about doing time based releases?

We could do release every month.
Everything that has been merged to master would be included in the release.

Thoughts?
@sebgoa @ericchiang @ngtuna @janetkuo @surajssd @cdrage

**Comment by surajssd** [comment]
:+1: for timely releases @kadel

**Comment by kadel** [comment]
We discussed this at yesterday's  community meeting.
We will try to do release every month, on the last week of the given month. Versioning will follow semantic versioning standard.

**Comment by cdrage** [comment]
I'm going to eventually update the RELEASE.md document to better outline how we do releases (run the script, add SHA, etc.)

**Comment by surajnarwade** [comment]
@cdrage , are we gonna use goreleaser ?

**Comment by cdrage** [comment]
@surajnarwade Eventually :) Right now the release.sh script works wonders

**Comment by surajnarwade** [comment]
@cdrage , cool

**Comment by cdrage** [comment]
With the newest release, I have added SHA256 Sums as well as installation instructions to the `release.sh` script. Hopefully this covers everything!

https://github.com/kubernetes/kompose/releases/tag/v1.0.0
