### ISSUE TITLE
Kompose  latest release version info from version file

### ISSUE THREAD

**Issue by hrishin** [kubernetes/kompose#712]
For fabrica8 maven plugin integration, we need a file which can give latest release version from Http URL.

Now this can be done by consuming github release API  but it will overkill the simplicity.
For the sake of consistency and aligning existing implementations we need the version file under kompose repository.
e.g. gofabric8 https://github.com/fabric8io/gofabric8/blob/master/version/VERSION

It would e great if kompose project can provide similar version file

**Comment by cdrage** [comment]
@hrishin fine by me! should we stick this in the `/build` directory? what do you think?

**Comment by hrishin** [comment]
@cdrage sure, looks good for us :)
Thanks @cdrage  @surajnarwade

**Comment by cdrage** [comment]
@hrishin Feel free to push a PR if you wish!

**Comment by surajnarwade** [comment]
@cdrage @hrishin , I already got some inspiration for this from fabric8, /me taking this.
