### ISSUE TITLE
adding timestamp in k8s artifacts

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/kompose#717]
I was validating results from kompose using [kubeval](https://github.com/garethr/kubeval), I got following output: 

```
$ kubeval frontend-deployment.yaml 
The document frontend-deployment.yaml contains an invalid Deployment
--> spec.template.metadata.creationTimestamp: Invalid type. Expected: string, given: null
--> metadata.creationTimestamp: Invalid type. Expected: string, given: null
```

Should we add timestamp in spec ?
any thoughts, @kadel @surajssd @cdrage

**Comment by kadel** [comment]
I don't think it should be set.

It looks like bug in `kubeval`

If you look at the [reference documentatoin](https://kubernetes.io/docs/api-reference/v1.7/#objectmeta-v1-meta) it says
"**CreationTimestamp is a timestamp representing the server time when this object was created**. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. **Populated by the system.** "

**Comment by surajnarwade** [comment]
@kadel , gotcha, thanks for clarifying

**Comment by surajssd** [comment]
@surajnarwade try to report it in `kubeval` ?

**Comment by garethr** [comment]
Hey, author of `kubeval` here.

According to the Kubernetes spec (https://github.com/garethr/kubernetes-json-schema/blob/master/master-standalone/deployment.json#L3511-L3514) the error is correct. Unfortunately Kubernetes doesn't exactly use this spec internally, so `kubeval` is finding upstream bugs in how the types are output to JSON Schema in the OpenAPI spec in a few places.

I've opened https://github.com/garethr/kubeval/issues/16 to track.

@surajnarwade note that kubeval will shortly be available as a Go library as well, so it might be interesting to build the validation in as an optional step into Kompose?

**Comment by surajnarwade** [comment]
@garethr that will be awesome

**Comment by surajssd** [comment]
@garethr thanks, having a golang binary will help both kompose and [kedge](https://github.com/kedgeproject/kedge/) !

cc: @containscafeine @kadel

**Comment by garethr** [comment]
Usage as a go library is now in master with a little documentation. https://github.com/garethr/kubeval#library

I'd love any feedback on that interface, or other things folks would like to see.

**Comment by garethr** [comment]
@surajnarwade just to let you know I've updated the schemas and the service definition should now work as expected. All the details in https://github.com/garethr/kubeval/issues/16 for anyone following along.

**Comment by surajnarwade** [comment]
@garethr awesome, It's working as expected, Thanks :)
