### ISSUE TITLE
Deprecate Docker Compose Version 2.1, 2.2, and 3.3. Only support 1,2,3,4 (future).

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#725]
See:
https://docs.docker.com/compose/compose-file/compose-versioning/#versioning

I propose that we deprecate any minor versions and only support major versions. 

Problem case is that version 2.1 and 2.2 isn't support by https://github.com/docker/libcompose and we would have to contribute up-stream.

Docker is pushing for Version 3 and is supported by their http://github.com/docker/cli tool, however, 3.1, 3.2 and 3.3 are moving too quick (3.1 and 3.2 aren't even mentioned on https://docs.docker.com/compose/compose-file/compose-versioning/#version-3 anymore).

I suggest we only support major versions (1,2,3) and eventually 4 (in the farrrr future).

**Comment by cdrage** [comment]
ping @kadel @surajnarwade @surajssd @containscafeine for discussion.

**Comment by surajnarwade** [comment]
I think we don't support any minor version in kompose, 
+1 for deprecating minor versions.

**Comment by cdrage** [comment]
I have updated http://kompose.io/conversion/ to outline that we only support major versions.

Can we close this?

@kadel @surajnarwade @surajssd @containscafeine

**Comment by surajnarwade** [comment]
yeah, we can close this

**Comment by mterron** [comment]
Sorry to resurrect a closed issue but what syntax for 2/3 is supported? There's quite a bit of difference between 2, 2.1, 2.4, etc. I have a 2.4 compose with healthcheck for example, how do I map that?

**Comment by cdrage** [comment]
@mterron We support all versions now. If you have troubles, you can always upgrade to version 3 and deploy that. Healthcheck works on there! http://kompose.io/conversion/
