### ISSUE TITLE
Add documentation on Kompose integrations

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#732]
Kompose has been integrated into Fabric8 (see: https://github.com/fabric8io/fabric8-maven-plugin/pull/988) we should effectively document cases where Kompose has been used in other integrations. Whether it's a GUI site or plugin.

**Comment by pradeepto** [comment]
Same applies for integration with DevSuite installer. https://developers.redhat.com/products/devsuite/overview/

**Comment by hrishin** [comment]
We expecting new doc or add it under particular section in existing doc e.g. user guide?

**Comment by surajnarwade** [comment]
@hrishin , maybe under `Introduction` section itself

**Comment by cdrage** [comment]
@surajnarwade @hrishin I'd say separate. Such as "third-party". Adding to Introduction may clutter a few things.

**Comment by cdrage** [comment]
Hey @hrishin do you know where I can find documentation on the Kompose maven plugin? I was unable to find anything on Google or a quick search @ Red Hat.

**Comment by hrishin** [comment]
Hey @cdrage 
Here you go for f8mp and kompose integration documentation https://maven.fabric8.io and look for followin section having Docker Compose keywords.

1.  Introduction
2. [Configuration](https://maven.fabric8.io/#configuration)
3. [Docker Compose](https://maven.fabric8.io/#docker-compose)

Please let me know if its sufficient.

**Comment by pradeepto** [comment]
Perhaps https://www.katacoda.com/courses/kubernetes/deploy-docker-compose-using-kompose this can be added as well.

**Comment by cdrage** [comment]
@pradeepto Personally, I wouldn't like https://www.katacoda.com/courses/kubernetes/deploy-docker-compose-using-kompose added as it forces users to sign-up and give away their information in order to use the tutorial. If there's an alternative site, that would be better.

**Comment by piyush1594** [comment]
Hi @cdrage,
How should be the documentation for Kompose Fabric8-maven Plugin Integration ?
Just add the links in integration or we should create a explicit document for it.

**Comment by piyush1594** [comment]
![sample](https://user-images.githubusercontent.com/19270240/31124367-c91419f2-a861-11e7-8773-e4fbee1aca2f.png)
@cdrage @surajnarwade Right Now, i have done this. Is this fine ?

**Comment by cdrage** [comment]
@piyush1594 ideally create an elaborate example where you can clearly use Kompose. Further increasing the size of integration.md document.

Can you link me those examples?

We may need a better description too for the Fabric8 Maven plugin.

Instead of a screenshot, it would be better to open up a PR for this.

**Comment by piyush1594** [comment]
Hi @cdrage,

Submitted the PR. Lets discuss the exact changes required for plugin documentation.

**Comment by surajnarwade** [comment]
since #836 is merged, we can close this issue
