### ISSUE TITLE
overlapped content on the conversion matrix documentation page

### ISSUE THREAD

**Issue by rickypai** [kubernetes/kompose#765]
In the [Conversion Matrix](http://kompose.io/conversion/) page, when you scroll horizontally on the table, the content will overlap with the menu.

<img width="777" alt="screen shot 2017-08-15 at 4 35 51 pm" src="https://user-images.githubusercontent.com/1469579/29341231-d8928342-81d7-11e7-8681-3f11c0fa2900.png">

**Comment by surajnarwade** [comment]
@rickypai , it maybe your browser issue. works well for me on chrome and firefox

**Comment by cdrage** [comment]
@rickypai I don't see an issue either :( mind telling us what browser you're using?

**Comment by rickypai** [comment]
I tired it on multiple bowsers: chrome, chrome canary, safari, brave, all the same result.

you need to scroll the content horizontally to see the overlap

**Comment by cdrage** [comment]
@rickypai Ohhhhh, I see how. I was able to re-produce this. I'll push a fix out soon.

**Comment by cdrage** [comment]
@rickypai Should be fixed now with #773 and #774 let me know if it's not :+1:
