### ISSUE TITLE
Update to annotations / cli tests + development document

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#770]
So there's two issues I'm encountering with annotations:

1. If there is no `kompose`, it does not error out. For example, if Kompose is not within $GOPATH or /usr/local/bin, then the annotation is blank for VERSION.
2. Tests need to be updated.. Using sed seems like a hack at the moment and it should be refactored (in the future)

Ping @surajnarwade

**Comment by cdrage** [comment]
Another suggestion as well is after fixing issue **1** we implement a small script that passes in a file name and automatically adds the "test" to `tests.sh` as it's fairly difficult / troublesome to manually create all the test outputs as well as modify it so `%VERSION%` and `%CMD% is there for the annotations.

**Comment by surajnarwade** [comment]
@cdrage that script is already on my list

**Comment by ashetty1** [comment]
Taking this up

**Comment by surajnarwade** [comment]
documentation issue: https://github.com/kubernetes/kompose/issues/781
