### ISSUE TITLE
Add testing documentation

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/kompose#781]
As of now, we don't have testing documetation (which is needed for any new contributors)

**Comment by ashetty1** [comment]
@cdrage @surajnarwade I am going write a document on how to write tests for OpenShift / k8s framework that we have. Let me know if you have any inputs.

**Comment by surajnarwade** [comment]
@ashetty1, one of the pointer will be how to test code using commands like `make test` or `make test-cmd` and what they do

**Comment by cdrage** [comment]
Priorities:

 - [ ] Better documentation on how to write tests
 - [ ] Better documentation on how to actually RUN these tests.
