### ISSUE TITLE
Add --controller

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#792]
Add a --controller flag instead of using parameters such as `--daemon-set` `--deployment`, etc.

This allows output based on simply doing `--controller=DaemonSet`

**Comment by surajnarwade** [comment]
I will take this up

**Comment by cdrage** [comment]
@surajnarwade Let's focus on some of the milestones :) https://github.com/kubernetes/kompose/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.1.0+release%22
