### ISSUE TITLE
Up and convert commands are not equal in features

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#798]
For example, we are able to deploy --daemon-set using `convert`, but not with `up`.

We have *some* things such as `--build` which is consistent in `kompose up`, but other aspects such as controllers, etc do not function correctly.

We should have the SAME experience between `up` and `convert`.

It goes against UX/UI having inconsistencies between the commands. One should convert, one should bring those converted up.

List of parameters NOT in `up`:
- [ ] --daemon-set
- [ ] --deployment
- [ ] --chart (I don't think this should be applicable)
- [ ] --replication-controller
- [x] --build-branch
- [x] --build-repo
- [ ] --deployment-config
- [x] --insecure-repository

A couple of these parameters will be deprecated in favour of `--controller` however.

**Comment by surajnarwade** [comment]
Picking `--build-branch` first

**Comment by surajnarwade** [comment]
sending PR for `--build-repo`

**Comment by surajnarwade** [comment]
`--build-repo` is being tracked in PR https://github.com/kubernetes/kompose/pull/824
`--build-branch` is being tracked in PR https://github.com/kubernetes/kompose/pull/820

**Comment by surajnarwade** [comment]
if we are adding `--controller`  and controller flags like `--daemon-set`, `--replication-controller`, we have to implement in `kompose down` as well
