### ISSUE TITLE
Packaging Kompose for debian 

### ISSUE THREAD

**Issue by rahulkrishnanfs** [kubernetes/kompose#806]
Bug#874049: Acknowledgement (ITP: Kompose -- conversion tool for all things compose( namely Docker Compose) to container ochestrators (Kubernetes or Openshift))

**Comment by surajssd** [comment]
@cdrage was looking at this one before IIRC !


@rahulkrishnanfs has filed it in Debian upstream
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874049

**Comment by cdrage** [comment]
Hey @rahulkrishnanfs I can help and become a co-maintainer. I've been wanting to become a Debian developer for a while.

**Comment by rahulkrishnanfs** [comment]
@cdrage thats great

**Comment by cdrage** [comment]
Any updates @rahulkrishnanfs ?

**Comment by joh4nd** [comment]
do you expect revisiting your conclusion?

**Comment by cdrage** [comment]
> do you expect revisiting your conclusion?

If you can become a maintainer of the package + distribute upstream we can revisit it, otherwise we unfortunately do not have the resources to maintain a debian package.

**Comment by rahulkrishnanfs** [comment]
Johan, If you would like to join with me, we can package together.

Regards,
Rahul Ra

**Comment by joh4nd** [comment]
Cheers, cdrage.

Rahul, interesting. What would that entail? Are you already maintaining some debian packages? What's your preferred means of communication, should we want to move it outside this issue?
