### ISSUE TITLE
`--volumes` is not validated 

### ISSUE THREAD

**Issue by kadel** [kubernetes/kompose#814]
If you run `kompose convert --volumes foobar` PVC is created and no error is raised.

This should error out as an invalid value for `--volumes`. Currently, only possible values are `PersistentVolumeClaim` and `emptyDir`

**Comment by surajnarwade** [comment]
This should go into validation of flags, I will look into it

**Comment by surajnarwade** [comment]
@kadel , since #817 is merged now, we can close this
