### ISSUE TITLE
kompose build fails to read the context correctly

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#832]
## Problem

kompose fails to find the `Dockerfile` even if the `dockerfile` is set under `build` and `context` is also set.

## How to reproduce?

Please see the following directory structure    

```console
$ tree
.
├── docker-compose.yml
├── example
│   └── db.json
├── glide.lock
├── glide.yaml
├── LICENSE
├── main.go
├── Makefile
├── output.json
├── parsego.go
├── README.md
├── scripts
│   ├── Dockerfile
│   ├── entrypoint.sh
│   └── k8s-release
├── spec.go
├── swagger.json
└── vendor
    ├── github.com
    │   ├── davecgh
...
```

I am trying to do a build with `Dockerfile` being in `scripts` directory. But my build context is root of the project. Essentially I am running a build command as following:

```console
docker build -t surajd/kedgeschema -f ./scripts/Dockerfile .
```

Above works fine.

To make it easier I have created `docker-compose` file which looks like following:

```yaml
$ cat docker-compose.yml 
version: "2"
services:
  gen:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    image: surajd/kedgeschema
```

docker-compose works on this:

```console
$ docker-compose up
Building gen
Step 1/11 : FROM golang:1.9.0 AS build-env
...
```

But kompose fails as 

```console
$ kompose up
INFO Build key detected. Attempting to build and push image 'surajd/kedgeschema' 
INFO Building image 'surajd/kedgeschema' from directory 'json-schema-generator' 
FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service gen: Unable to build image. For more output, use -v or --verbose when converting.: API error (500): {"message":"Cannot locate specified Dockerfile: Dockerfile"}
```

## Versions

```console
$ kompose version
1.2.0 (8efe274)
```

## Other info

The project I am trying that docker-compose file is https://github.com/kedgeproject/json-schema-generator

**Comment by surajssd** [comment]
In `dockerlib.BuildImageOptions` also set `Dockerfile` field as relative path to `context`.

I have tried something similar in https://github.com/kedgeproject/kedge/pull/295/files#diff-f9c1aac2b0fdb0b76e7a167cb362d95cR93

**Comment by surajnarwade** [comment]
Thanks @surajssd for pointing this out, will send a fix very soon :)

**Comment by surajnarwade** [comment]
we can close this issue now :)
