### ISSUE TITLE
[doc] more tutorial for gcloud?

### ISSUE THREAD

**Issue by u007** [kubernetes/kompose#833]
Hi,

it would be nice if there is a doc for kompose and kubectl with gcloud
this is my configuration, but i could not get external ip from gcloud container.
Any help on external ip?

```
gcloud auth login
gcloud auth application-default login
gcloud components install kubectl
```
setup google compute container on google cloud
click on connect to get instruction
```
...
kubectl proxy
kompose convert
kompose up
kompose replace ...yaml # to update
```

and never ever kompose down as it will delete off volumes

thank you

**Comment by u007** [comment]
okay i found the solution, after kompose up, i have to
```
kubectl delete service web
kubectl expose deployment web --type="LoadBalancer" 
```
assumed web is the service name

**Comment by cdrage** [comment]
@u007 Hey James! thanks for leeting us know the problems with using gcloud. I am going to add a note in our tutorials / user guide for adding `kubectl expose deployment web --type="LoadBalancer"`

**Comment by u007** [comment]
@cdrage nice, that will be awesome 👍 
btw, i my ip was pending because my google cloud is on free trial...
