### ISSUE TITLE
Fix links in docs/README.md

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/kompose#845]
`setup` is 404 as there is `getting-started` file added.
@piyush1594

**Comment by cdrage** [comment]
@surajnarwade I'm really confused. Ummm what?

**Comment by cdrage** [comment]
Seems very small, can you push a PR @surajnarwade ? It's just an update to: https://github.com/kubernetes/kompose/blob/master/docs/README.md

**Comment by piyush1594** [comment]
@cdrage I will do it today. It is just about updating quickstart to getting started and setup to installation.
