### ISSUE TITLE
Not creation of `-service.yaml` when `restart` is present

### ISSUE THREAD

**Issue by gdhgdhgdh** [kubernetes/kompose#851]
Hi, using `1.3.0` of `kompose` and this trivial `docker-compose.yaml`:

```
frontend:
  image: registry:5000/frontend:1.0.0
  ports:
    - "12681:80"
    - "12683:443"
  environment:
    API_URL: "http://10.179.49.0:12603"
  restart: 'no'

redis:
  image: registry:5000/redis:3.0.7
  ports:
    - "12679:6379"
```

```
[root@node1 k]# kompose convert
INFO Kubernetes file "redis-service.yaml" created 
INFO Kubernetes file "frontend-pod.yaml" created  
INFO Kubernetes file "redis-deployment.yaml" created 
```

There's no service for the frontend, which I thought was a bit odd. When I remove the `restart` line completely, I get a different set of files:

```
[root@node1 k]# kompose convert
INFO Kubernetes file "frontend-service.yaml" created 
INFO Kubernetes file "redis-service.yaml" created 
INFO Kubernetes file "frontend-deployment.yaml" created 
INFO Kubernetes file "redis-deployment.yaml" created 
```

Yes, two services and two deployments is what I'd expect. Is this a bug?

**Comment by surajnarwade** [comment]
@gdhgdhgdh , when you mention `restart: no`, kompose will generate pod.
for more reference: http://kompose.io/user-guide/#restart

**Comment by gdhgdhgdh** [comment]
Yeah that makes sense - the question was really that I would still expect a `kind: Service` to be created even if it's pointing to a one-off pod. Is that wide of the mark?

**Comment by surajnarwade** [comment]
@gdhgdhgdh , `restart: no` will give same behaviour as `job`, so it makes no sense to create service, I think

**Comment by hangyan** [comment]
@surajnarwade @cdrage  I thinks the logic should goes to:

1. with ports, create service by default
2. without ports, no service. With labels, create Headless Service

This should cause no confuse any more.

**Comment by cdrage** [comment]
@hangyan I agree with all those points. We should implement a label for a headless service rather than relying on "hidden" features such as `restart: no`. Labels such as specifying to use a Job instead..

**Comment by surajnarwade** [comment]
+1 @hangyan
