### ISSUE TITLE
old Kompose version in Fedora 26

### ISSUE THREAD

**Issue by kadel** [kubernetes/kompose#854]
Fedora 26 still has only Kompose 1.0.0 but currently the latest released version is 1.3.0 :-(

**Comment by surajnarwade** [comment]
cc @surajssd

**Comment by surajssd** [comment]
So the latest is available on centos as:

```
yum install -y centos-release-openshift-origin
yum install -y kompose
```

But for fedora and epel the PR is open https://github.com/dustymabe/fedpkg-kompose/pull/13 and https://github.com/dustymabe/fedpkg-kompose/pull/12
