### ISSUE TITLE
Local volumes (from host) via conversion

### ISSUE THREAD

**Issue by johnament** [kubernetes/kompose#855]
I'm trying to get my feet wet with Kubernetes.  Since we already had a lot of investment in docker-compose I figured I'd try kompose to convert my docker-compose.yml into kubernetes service definitions.

When I do the conversion, I get this warning:

```
WARN Volume mount on the host "/Users/spartan/src/my-app/docker/custom-scripts" isn't supported - ignoring path on the host
```

My volume looks like this in docker-compose

```
    volumes:
      - "../docker/custom-scripts:/custom"
```

Is there another format I should use?

**Comment by surajnarwade** [comment]
we don't support volume mount on host with kompose, you can use `emptyDir`  though

**Comment by johnament** [comment]
That's fine, I don't mind editing the files after the conversion.  Wouldn't I want a `hostPath` though?  Can `hostPath` be relative?

**Comment by cdrage** [comment]
Hey John! Due to how Kubernetes handles volumes, it's difficult to pass in a host volume / root volume. We *are* adding support for hostPath however, as one of our outside contributors is pushing it via PR: https://github.com/kubernetes/kompose/pull/734

**Comment by johnament** [comment]
@cdrage understood.  It's more of a case where I think I can edit the volume definition afterwards.

**Comment by pirate** [comment]
@surajnarwade bump, it looks like this got auto-closed.

**Comment by hangyan** [comment]
close by #1216 . Now convert/up support `--volumes=configMap` to mount the files via configmap
