### ISSUE TITLE
update integration doc

### ISSUE THREAD

**Issue by hrishin** [kubernetes/kompose#857]
Add documentation for
- [ ] Dev. suit installer

Rearrange integration doc
- [ ] Bring f8-m-p integration on the top in the list
- [ ] Dev. suit installer integration second

**Comment by cdrage** [comment]
Documentation for Dev Suite installer has already been added, see: http://kompose.io/getting-started/#rhel-and-kompose

**Comment by cdrage** [comment]
ping @hrishin

**Comment by hrishin** [comment]
@cdrage it would be nice if we add some bits of dev. suit installer under integration document?
@pradeepto what you say?

**Comment by cdrage** [comment]
@hrishin Yup. Just make a PR and push whatever you think is necessary :+1:

**Comment by hrishin** [comment]
@cdrage sure

**Comment by cdrage** [comment]
@hrishin Keep in mind that we already have a tutorial on how to use DevSuite under integrations, but there's no need to have two tutorials in two places. Whatever you think is best, just push to a PR and we can review it.
