### ISSUE TITLE
Bintray links broken in the README

### ISSUE THREAD

**Issue by prein** [kubernetes/kompose#889]
Tiny (and perhaps boring) issue but all Bintray links in the README are not working and I couldn't figure out what would be the correct path.

**Comment by cdrage** [comment]
@kadel any ideas?

**Comment by cdrage** [comment]
@prein Hey! It seems that it fixed itself (which is really odd).

Do you mind trying it again your-end?

**Comment by prein** [comment]
@cdrage Thanks, confirmed, works now.
