### ISSUE TITLE
Allow specifying imagePullSecret

### ISSUE THREAD

**Issue by jmatsushita** [kubernetes/kompose#897]
Hi there,

How would one go about providing the `imagePullSecret` key to a `deployment`?

This could possibly help with #893 ? This might also be part of a broader discussion about "template-supported conversions", which would allow to make custom changes to the conversion outputs...

Cheers,

Jun

**Comment by jmatsushita** [comment]
In fact, instead or in addition to "template-supported conversions", if the helm chart conversion template had a number of `values` interpolated, then the parameters could be passed to `helm` on deploy.

**Comment by Code0x58** [comment]
The issue with that case is the case you liked is that the code tries doing something like `docker push my-namespace/image:tag` instead of `docker push my-registry.com:5000/my-namespace/image:tag`.

I think pod `ImagePullSecrets` fall into the same boat as ingress TLS secrets, so whoever takes this on could use #896 as a point of reference for the code.

**Comment by berryp** [comment]
Does this mean we cannot pull from external private registries right now?

**Comment by Code0x58** [comment]
You can't pull from an private registry if you would need to authenticate from the node to pull an image.

**Comment by hangyan** [comment]
@ysle In kubernetes, you can create a secret for you private registry and add it to the default  serviceaccount ( in the same namespace). After this ,kubernetes will pull the image for you.

Check the doc: https://kubernetes.io/docs/concepts/configuration/secret/#arranging-for-imagepullsecrets-to-be-automatically-attached

**Comment by jankal** [comment]
/reopen
This is important for deploying docker-compose files to a kubernetes cluster.

**Comment by jankal** [comment]
@Code0x58 anything new on this?

**Comment by Code0x58** [comment]
I haven't kept up with the development of Kompose for months, but as I left it [hangyan's comment](https://github.com/kubernetes/kompose/issues/897#issuecomment-395089750) was the best existing solution, but a Kompose fix would have been easy by doing something like #896 to add another [label](https://github.com/kubernetes/kompose/blob/master/docs/user-guide.md#labels) to provide `ImagePullSecret`s similar to #896. #1040 is an active PR on it, so probably worth reviewing for anyone who is interested and has time.
