### ISSUE TITLE
Cannot run in gcloud environment with Kompose CLI

### ISSUE THREAD

**Issue by surajneupane55** [kubernetes/kompose#905]
I want to integrate Kompose CLI inside the container so I can use it as a part of CI/CD pipeline. In gitlab-ci.yml I want to install Kompose in the container so I can use it. So far I am unable to do so. 

Here is my gitlab-ci.yml file:

    image: node:8-alpine

    stages:
      - build

    build_image:
      stage: build
      only: [master]
      image: google/cloud-sdk
      services:
        - docker:dind
      script:
        - echo "$GOOGLE_KEY_SECRET" > key.json # Google Cloud service accounts
        - gcloud auth activate-service-account --key-file key.json
        - gcloud config set project my-web-190118

    // I install Kompose here with following command: curl -L https://github.com/kubernetes/kompose/releases/download/v1.6.0/kompose-linux-amd64 -o kompose 

    //I want to use `- Kompose up` here

**Comment by kadel** [comment]
What error do you get?

**Comment by surajneupane55** [comment]
I found a right approach to do it without using kompose [here](https://stackoverflow.com/questions/47888027/how-to-deploy-staging-in-google-cloud-platform-with-kubernetes-and-gitlab-ci-cd)
