### ISSUE TITLE
extended env_file capability to in-docker-compose.yml substitutions

### ISSUE THREAD

**Issue by darKoram** [kubernetes/kompose#909]
in https://github.com/kubernetes/kompose/pull/799 the tests show the ability to over-ride an 'environment' var with one from a '.env' file which is useful if the container runtime depends on the var.  But another use case for docker-compose .env file is to allow ${var} substitutions in other docker-compose arguments.  A common example would be

    services:
      app:
        image: myapp
        volumes: ${local_path_to_data}:/data
        env_file: 
          - "./.env"

and 
.env 
    local_path_to_data=/home/me/data          # for a linux user
    # or
    local_path_to_data=/Users/me/data           # for a mac user

In my testing, this sort of substitution is not yet supported and gives an error
`* error decoding 'Volumes[0]': invalid spec: :/data empty section between colons`

I would expect the default behavior to be to create a persistent volume named for the rhs of Volumes populated with the data at local_path_to_data specified in the .env file.

**Comment by kbroughton** [comment]
I have a workaround for this now:
// this gets the .env files stamped into the -out.yml file
docker-compose config -f docker-compose.yml > docker-compose-out.yml
kompose convert -f docker-compose-out.yml

perhaps kompose should be loading based off of docker-compose config  output?

**Comment by cpcundill** [comment]
Same problem for me.  The workaround helps @kbroughton but the `docker-compose config` output changes the version from '2' in the original to '2.0' which isn't supported by `kompose`

**Comment by vikasgubbi** [comment]
If the environment variable file need to be placed in the application config location , what needs  to be done

**Comment by vikasgubbi** [comment]
Correction

If the environment variable file need to be placed in the **custom** application config location , what needs to be done

**Comment by chiqui3d** [comment]
I just tried it for the first time and I got this error: I guess it's because of the` .env` file or` env` variable?

` error decoding 'Volumes[0]': invalid spec: ./app:: empty section between colons`

```
volumes:
      - ./app:${APP_SYMFONY_DIRECTORY}
```

**Comment by ayoubbensakhria** [comment]
docker-compose version: '3.7' --> doesn't work 
docker-compose version: '2' --> it works

**Comment by nikhilpanchal123** [comment]
> in #799 the tests show the ability to over-ride an 'environment' var with one from a '.env' file which is useful if the container runtime depends on the var. But another use case for docker-compose .env file is to allow ${var} substitutions in other docker-compose arguments. A common example would be
> 
> ```
> services:
>   app:
>     image: myapp
>     volumes: ${local_path_to_data}:/data
>     env_file: 
>       - "./.env"
> ```
> 
> and .env local_path_to_data=/home/me/data # for a linux user # or local_path_to_data=/Users/me/data # for a mac user
> 
> In my testing, this sort of substitution is not yet supported and gives an error `* error decoding 'Volumes[0]': invalid spec: :/data empty section between colons`
> 
> I would expect the default behavior to be to create a persistent volume named for the rhs of Volumes populated with the data at local_path_to_data specified in the .env file.

plzz give  me windows path
