### ISSUE TITLE
Unable to push Docker image for service web: Unable to retrieve .docker/config.json authentication details. 

### ISSUE THREAD

**Issue by ruddra** [kubernetes/kompose#911]
I got this error while running: `kompose up`
I have been using the following docker-compose.yml:

> version: '3'
> 
> services:
>   db:
>     image: mysql:5.5
>     container_name: db-container
>     ports:
>       - "3406:3306"
>     environment:
>       MYSQL_ROOT_PASSWORD: mypassword
>       MYSQL_USER: root
>       MYSQL_DATABASE: mydb
>   web:
>     build: .
>     container_name: web-container
>     command: python3 manage.py runserver 0.0.0.0:8000
>     volumes:
>       - .:/code
>     image: "ruddra/web-image"
>     ports:
>       - "8000:8000"
>     depends_on:
>       - db

I ran the following commands:
>kompose convert --provider=openshift
>kompose up --provider=openshift

I was able to push to my dockerhub repository using: 
`docker-compose push`

**Comment by cdrage** [comment]
Hey @ruddra I've been trying to diagnose this issue.

I'm assuming you're using OS X?

**Comment by ruddra** [comment]
I am using macOS high sierra :)

**Comment by cdrage** [comment]
@ruddra That'd be why :) Docker is running in a VM and I believe they changed the configuration location. I'll have to investigate.

**Comment by ruddra** [comment]
In '~/.docker/config.json'

**Comment by coodix** [comment]
Same issue for me. Trying use local private repo, but even after docker login keep getting error "FATA Error while deploying application: k.Transform failed: Unable to push Docker image for service proxy: Unable to retrieve .docker/config.json authentication details. Check that 'docker login' works successfully on the command line.: Failed to read authentication from dockercfg".

~/.docker/config.json is in place

**Comment by cdrage** [comment]
Hey @coodix @ruddra @kbroughton

I got time this week to get around to this issue, unfortunately, I don't have a Mac and I'm unable to run a VM (against licensing :() to diagnose it. So I need your help. 

I'd like you all (or at least one of you) to these two things:

From this issue (https://github.com/pachyderm/pachyderm/issues/2446) , let's try this:

1. Can you please output what your DOCKER_CONFIG variable is for me. If it's blank, try the command below the run Kompose again and see if it succeeds.

```sh
echo $DOCKER_CONFIG
export DOCKER_CONFIG=~/.docker/ 
```

From this issue (https://github.com/fsouza/go-dockerclient/issues/677)

2. Can you output your `.docker/config.json` details for me and see if it contains `osxkeychain`? If you decide to comment in this issue with the configuration details, make sure you omit the `auth` variable :+1: 

I'm going to see if I can borrow a friends Mac or at least find one at the company lab which has one I can remote into!

Seems at the moment this issue is only affected Mac users.

Many thanks :100:

**Comment by coodix** [comment]
@cdrage , $DOCKER_CONFIG is empty by default. I tried to set it to "~/.docker/" but it didn't help. Same error appeared.
Content of my ~/.docker/config.json:
`{
	"auths": {
		"https://index.docker.io/v1/": {},
		"localhost:5000": {}
	},
	"credsStore": "osxkeychain"
}`

But it became so after I execute "docker login localhost:5000" trying to make it work. In all cases same error.

**Comment by coodix** [comment]
@cdrage , I've found out what's the problem. It's because dockerclient isn't integrated with osxkeychain. See https://github.com/fsouza/go-dockerclient/issues/677

**Comment by coodix** [comment]
Also it relates to https://github.com/docker/for-mac/issues/1584
Docker for Mac by default uses osxkeychain for storing credentials.

**Comment by coodix** [comment]
So the current solution is to edit config.json:
`{ "auths": { "localhost:5000": { "auth": "...base64encoded credentials..." } }, "credsStore": "osxkeychain" }`
And need to ensure that there are no auths without auth string (https://github.com/fsouza/go-dockerclient/issues/677#issuecomment-360269441 ).

**Comment by coodix** [comment]
@cdrage , do you consider adding empty AuthConfiguration as it stated in comment for PushImage method (github.com/fsouza/go-dockerclient/image.go):
`
// An empty instance of AuthConfiguration may be used for unauthenticated
// pushes.
//
// See https://goo.gl/zPtZaT for more details.
func (c *Client) PushImage(opts PushImageOptions, auth AuthConfiguration) error {
`

At least in case if no one auth was found by dockerlib.NewAuthConfigurationsFromDockerCfg?

**Comment by cdrage** [comment]
@coodix Yeah, that's for investigating.. It's difficult with `oxskeychain`, we'd have to either contribute an upstream change to the go-dockerclient library or implement Docker's client library. 

We can try to do empty authentication to fix it.

**Comment by geekflyer** [comment]
I'm having the same issue on OSX when trying to push to `gcr.io` using the gcr credential helper.
I'm trying to update my pipeline with 
`pc update-pipeline -f pipeline.json --push-images`
and are getting 
`error parsing auth: open /Users/geekflyer/.dockercfg: no such file or directory, try running docker login`

my `~/.docker/config.json` looks like this:

```
{
	"auths": {
		"gcr.io": {},
		"https://registry.gitlab.com": {},
		"registry.gitlab.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.09.0-ce (darwin)"
	},
	"credsStore": "osxkeychain",
	"credHelpers": {
		"asia.gcr.io": "gcr",
		"eu.gcr.io": "gcr",
		"gcr.io": "gcr",
		"staging-k8s.gcr.io": "gcr",
		"us.gcr.io": "gcr"
	}
}% 
```

What is the workaround for this? This is really blocking me to iterate on some pipelines.

**Comment by geekflyer** [comment]
on a related issue. While digging I found that the podspec pachyderm creates for pipeline workers contains `imagePullPolicy: IfNotPresent` . Wouldn't it be better to simply specify `imagePullPolicy: Always` which would make specifying the `--push-images` flag obsolete?

**Comment by huntal** [comment]
I'm getting this issue on my project. I'm from Linux and there is my ~./docker/config.json : 
```{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "<somekey>="
                },
                "registry.gitlab.com": {
                        "auth": "<somekey>="
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.02.0-ce (linux)"
        }
}
```
Here's my try to push the image : 
```
➜  ultra-devops git:(kuberpod) ✗ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a DockerID, head over to https://hub.docker.com to create one.
Username (hystenal): hystenal
Password:
Login Succeeded

➜  ultra-devops git:(kuberpod) ✗ docker-compose push
Pushing agon (agonnode:tag)...
The push refers to repository [docker.io/library/agonnode]
070ea77bff68: Preparing
8760e8a8ec65: Preparing
89f1160177db: Preparing
64a60834482b: Preparing
ce26c278ee53: Preparing
b30530a0b009: Waiting
7c4b5f9422c0: Waiting
26fac7fe251e: Waiting
db584c622b50: Waiting
52a7ea2bb533: Waiting
52f389ea437e: Waiting
88888b9b1b5b: Waiting
a94e0d5a7c40: Waiting
ERROR: denied: requested access to the resource is denied

➜  ultra-devops git:(kuberpod) ✗ kompose up
WARN Unsupported hostname key - ignoring
INFO Container name in service "agon" has been changed from "Agon_iri" to "Agon-iri"
INFO Build key detected. Attempting to build and push image 'agonnode:tag'
INFO Building image 'agonnode:tag' from directory 'agon'
INFO Image 'agonnode:tag' from directory 'agon' built successfully
INFO Pushing image 'library/agonnode:tag' to registry 'docker.io'
INFO Multiple authentication credentials detected. Will try each configuration.
INFO Attempting authentication credentials 'registry.gitlab.com
ERRO Unable to push image 'library/agonnode:tag' to registry 'docker.io'. Error: unauthorized: incorrect username or password
INFO Attempting authentication credentials 'https://index.docker.io/v1/
ERRO Unable to push image 'library/agonnode:tag' to registry 'docker.io'. Error: denied: requested access to the resource is denied
FATA Error while deploying application: k.Transform failed: Unable to push Docker image for service agon: unable to push docker image(s). Check that `docker login` works successfully on the command line
```

**Comment by hangyan** [comment]
@huntal seems like not a kompose issue, because docker-compose push is not working too. Maybe wrong dockerhub user namespace. The output shows that you are trying to push to `library`, this is the official image account.. The image format is `<you-user-name>/<image-name>:<tag>` I think.

**Comment by huntal** [comment]
Yup you were right my bad, just add to change the `image` tag key to your format @hangyan thanks again

**Comment by PeterBocan** [comment]
This is still not working properly. I have no idea what's the problem (permissions? corrupted cache?)

```
INFO Build key detected. Attempting to build and push image 'x/fetcher'
INFO Building image 'x/coinapi-fetcher' from directory 'x-fetcher'
INFO Image 'x/fetcher' from directory 'x-fetcher' built successfully
INFO Pushing image 'x/fetcher:latest' to registry 'docker.io'
WARN Unable to retrieve .docker/config.json authentication details. Check that 'docker login' works successfully on the command line.: Failed to read authentication from dockercfg
INFO Authentication credentials are not detected. Will try push without authentication.
INFO Attempting authentication credentials 'docker.io
ERRO Unable to push image 'x/fetcher:latest' to registry 'docker.io'. Error: denied: requested access to the resource is denied
FATA Error while deploying application: k.Transform failed: Unable to push Docker image for service fetcher: unable to push docker image(s). Check that `docker login` works successfully on the command line
```

**Comment by eic-aibee** [comment]
> @cdrage , I've found out what's the problem. It's because dockerclient isn't integrated with osxkeychain. See [fsouza/go-dockerclient#677](https://github.com/fsouza/go-dockerclient/issues/677)
> 
> Also it relates to [docker/for-mac#1584](https://github.com/docker/for-mac/issues/1584)
> Docker for Mac by default uses osxkeychain for storing credentials.
> 
> So the current solution is to edit config.json:
> `{ "auths": { "localhost:5000": { "auth": "...base64encoded credentials..." } }, "credsStore": "osxkeychain" }`
> And need to ensure that there are no auths without auth string ([fsouza/go-dockerclient#677 (comment)](https://github.com/fsouza/go-dockerclient/issues/677#issuecomment-360269441) ).

"base64encoded credentials" can be generated by  
echo -n "username:password" | base64 
-n used to omit '\n' which added by echo

**Comment by alanbly** [comment]
So I'd like to add a bit to what everyone else has said. The message `WARN Unable to retrieve .docker/config.json authentication details` seems to be caused by there being ANY empty `auth` objects in the `~/.docker/config.json` file. `docker login` in many cases seems to create empty `auth` blocks so doing as the warning tells you can actually make this problem happen. Now if you, like me, do not want to put your personal google credentials into a text file, there is a way to make this work for a JSON key file (as described here https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file).
Once you have the key file, you can generate a base-64-encoded auth block using the same method they use for the `docker login` command. Combining that with the answer above from @eic-aibee , what you want to do is run this command: `echo -n "_json_key:$(cat key.json)" | base64` which will spit out the auth block to the console.

**Comment by wuestkamp** [comment]
So I solved this on OSX by disabling the keychain password storage:

1. `rm ~/.docker/config.json`
2. in Docker for Mac preferences, untick "Securely store Docker logins in macOS keychain"
3. restart Docker for Mac
4. `docker login`

Or for glcoud and pushing to gcr:
`gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io`

now your `~/.docker/config.json` should contain base64 encoded passwords. Working, not safe though!

If someone gets the keychain storage to work that would be nice...
