### ISSUE TITLE
kompose does not indicate key not line number when printing error

### ISSUE THREAD

**Issue by alexanderkjeldaas** [kubernetes/kompose#915]
This output:

```
 $ kompose convert -f ./docker-compose.yml
FATA configs Additional property configs is not allowed
```

Gives mostly no information:

1. No line number information
2. No yaml key
3. No `jq` style location
4. No excerpt from the input file.
5. It refers to "property config" where none of those words appear in the input.

**Comment by alexanderkjeldaas** [comment]
Ah, the `configs` is the key apparently.   I suggest adding line numbers for this to understandable.

**Comment by fentas** [comment]
Meaning that `configs` is not supported yet? Having the same problem.
