### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference" when using environment unset variables

### ISSUE THREAD

**Issue by niQo** [kubernetes/kompose#918]
when using a compose file containing an unset environment var, kompose crash with:
```
kompose up -f docker-compose.yml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1621e4b]
```

example:
```
version: '3'

services:
  jenkins:
    image: jenkins
    environment:
      - DEBUG
```

Note: if the environment var is set, everything work as expected. example:
```
version: '3'

services:
  jenkins:
    image: jenkins
    environment:
      - DEBUG=1
```

**Comment by cdrage** [comment]
Yeah.. this is currently an outstanding issue. For now, you'll have to change the `version` to 2 and try again.

**Comment by hangyan** [comment]
@cdrage @niQo  I have create and PR to fix this issue, it works files. you can check if out if you want
