### ISSUE TITLE
Support for multi-port services

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes/kompose#941]
From the documentation it sounds like multi-port services aren't supported?

http://kompose.io/user-guide/#labels
> If multiple ports are defined in a service, the first one is chosen to be the exposed.

https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services

This seems like a pretty basic feature, and the simplest example requirement is an http service that allows redirect from port 80 to 443. Any reason why only 1 port is supported, and if there are plans on supporting multi-port services?

**Comment by wrfly** [comment]
Actually it support multi-port services for me(I'm using the latest version).

You can try to convert one docker-compose file and then close this issue ;)

**Comment by surajnarwade** [comment]
@ghostsquad , as @wrfly mentioned, it does support multi-port services

**Comment by royshadmon** [comment]
Can anyone provide an example on how to do this so the answers here are more complete? 

I tried:
`    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 9376
      - name: https
        protocol: TCP
        port: 443
        targetPort: 9377`
and I am getting the following error: FATA [service].ports.0 Additional property port is not allowed.
Thanks in advance!
