### ISSUE TITLE
Add HTTPS support for download URLs

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/kompose#945]
HTTPS on https://kompose.io/ is broken. Because GitHub doesn't support HTTPS on custom domains - https://stackoverflow.com/questions/42172216/is-it-possible-to-use-https-ssl-on-github-pages-sites-with-a-custom-domain - one of the solutions is to use Netlify - https://www.netlify.com/docs/ssl/

**Comment by surajnarwade** [comment]
Thanks @abitrolly :) for the useful information.
cc: @cdrage

**Comment by abitrolly** [comment]
This now can be fixed properly by projects admins https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by abitrolly** [comment]
Now there could be a redirection from http://kompose.io/ to https version.
