### ISSUE TITLE
Correct DL-link to latest kompose in installation guide

### ISSUE THREAD

**Issue by marziman** [kubernetes/kompose#952]
Hi kompose-Team,

thanks for your efforts. I just figured out that your bintray is not available, but you point your installation guide on it.
Or am I missing something?

BR Mehmet

**Comment by cdrage** [comment]
Hi @marziman we've been having problems lately with Bintray.

I would suggest installing `kompose` via one of our latest releases or alternatively, you can build it from master.

A fix should go into the `README.md` in the next few days.

Many thanks.

**Comment by cdrage** [comment]
Hi @marziman I've opened up PR https://github.com/kubernetes/kompose/pull/953 to remove installation instructions. I will be investigating an alternative platform for go-to nightly / master builds.
