### ISSUE TITLE
How do I Specify the instance count via docker -compose file for Kompose

### ISSUE THREAD

**Issue by VenkateshSrini** [kubernetes/kompose#958]
Hi,
I have a docker compose file as below

`version: '3'
services:
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 6`

Will kompose automatically specify as by replica count in deployment yaml file ? If not what is the way to achieve this ?

Thanks

**Comment by surajnarwade** [comment]
kompose will take replica from docker-compose file, if you still want to override that value. you can mention it using `--replicas` flag
