### ISSUE TITLE
kompose up is not able to mount configmap volume

### ISSUE THREAD

**Issue by abhi-vaidya** [kubernetes/kompose#962]
kompose up
←[36mINFO←[0m We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources,
 use the 'kompose convert' and 'kubectl create -f' commands instead.

volumeMounts:
        - name: my-appl-path
          mountPath: /opt/app/properties
      volumes:
        - name: my-appl-path
          configMap:
            name: my-app-1

I have created config map with kubectl create configmap.
is my yaml file.  Could you please check this issue

**Comment by cdrage** [comment]
Hi, are you able to post your full `docker-compose.yaml` file? @abhi-vaidya so we may test it out / diagnose the issue?
