### ISSUE TITLE
Create Rolling updates using Kompose tool

### ISSUE THREAD

**Issue by VenkateshSrini** [kubernetes/kompose#965]
Hi ,
I had deployed a service in Kubernetes using Kompose Up <Dockerfile>. Now my docker image has changed and I want to update the container image in the already deployed Pod. If I perform Kompose up from the same dockerfile will that patch my container  ? If not what should I do to perform the image patching alone.

**Comment by cdrage** [comment]
@VenkateshSrini Good question.

The answer is using `kubectl apply`.

Using: `kompose convert --stdout | kubectl apply -f -` you can redeploy / apply your docker-compose.yaml file.

Perhaps in the future we should add a `kompose update` command to Kompose.

**Comment by pom11** [comment]
+1
