### ISSUE TITLE
Minor typos in Makefile

### ISSUE THREAD

**Issue by jaden-young** [kubernetes/kompose#971]
https://github.com/kubernetes/kompose/blob/39ad6140c33d35954aed38a66155f4ac392ce547/Makefile#L70-L71
Should probably be
```Makefile
.PHONY gen-cmd
gen-cmd:
```
and
https://github.com/kubernetes/kompose/blob/39ad6140c33d35954aed38a66155f4ac392ce547/Makefile#L129
Should probably be
```Makefile
.PHONY test-k8s
```

**Comment by hangyan** [comment]
@jaden-young Thanks for point out this ! Would you mind to create a PR to fix this?
